#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=35

ENV_FILE=/etc/asia-unhurried-deploy.conf
SITE_DIR=/srv/asia-unhurried
BARE_REPO=/srv/git/asia-unhurried.git

banner "部署 asia-unhurried 到阿里云"

# ── Stage 1: inputs & environment sanity ──────────────────────────────────
stage "基本信息与环境检查" 3

if [[ "$(id -u)" -ne 0 ]]; then
  warn "当前不是 root。请用 root 运行,或确保以下命令都走 sudo。"
  pause "确认后继续"
fi

say "这个脚本在你的阿里云服务器上执行,会把站点部署到:"
note "  代码目录   $SITE_DIR"
note "  裸仓库     $BARE_REPO  (本地 git push 到这里,钩子自动构建)"
note "  配置记录   $ENV_FILE"
echo

# Detect package manager
if   command -v dnf >/dev/null 2>&1; then PKG=dnf
elif command -v yum >/dev/null 2>&1; then PKG=yum
elif command -v apt >/dev/null 2>&1; then PKG=apt
else PKG=""; fi
if [[ -z "$PKG" ]]; then
  warn "没认出系统包管理器(dnf/yum/apt 都没有)。脚本无法继续。"
  exit 1
fi
printf '  %s✓%s 包管理器: %s\n' "$GREEN" "$RESET" "$PKG"

# Guess public IP: the address you SSH'd to, then Aliyun metadata, then ip.sb
SERVER_IP_GUESS=""
if [[ -n "${SSH_CONNECTION:-}" ]]; then
  SERVER_IP_GUESS=$(printf '%s' "$SSH_CONNECTION" | awk '{print $3}')
fi
if [[ -z "$SERVER_IP_GUESS" ]]; then
  SERVER_IP_GUESS=$(curl -m5 -s http://100.100.100.200/latest/meta-data/eipv4 2>/dev/null || true)
fi
if [[ -z "$SERVER_IP_GUESS" ]]; then
  SERVER_IP_GUESS=$(curl -m5 -s https://ip.sb 2>/dev/null || true)
fi
note "检测到的公网 IP: ${SERVER_IP_GUESS:-未知}"

ask DOMAIN "你的域名(已备案的那个,例如 example.com):"
ask EMAIL "邮箱(申请 HTTPS 证书用):"
ask SERVER_IP "服务器公网 IP [默认 ${SERVER_IP_GUESS:-无}]:"
[[ -z "$SERVER_IP" ]] && SERVER_IP="$SERVER_IP_GUESS"

write_env DOMAIN "$DOMAIN"
write_env EMAIL "$EMAIL"
write_env SERVER_IP "$SERVER_IP"
write_env SITE_DIR "$SITE_DIR"
write_env BARE_REPO "$BARE_REPO"

# ── Stage 2: DNS A record ─────────────────────────────────────────────────
stage "DNS 解析(阿里云控制台)" 4

say "在你的电脑浏览器里操作(本脚本在服务器上,开不了浏览器):"
step "打开 https://dns.console.aliyun.com/ → 找到 $DOMAIN → 解析设置"
step "添加 A 记录:主机记录 @ ,记录值 $SERVER_IP"
step "如果希望 www.$DOMAIN 也能访问,再加一条:主机记录 www ,记录值 $SERVER_IP"
note "新增解析一般 10 分钟内生效;改已有的记录看 TTL。"
pause "添加完成后按 Enter,我来验证解析"

DNS_OK=""
for _ in 1 2 3; do
  RESOLVED=$(getent hosts "$DOMAIN" 2>/dev/null | awk '{print $1}' | head -n1 || true)
  if [[ "$RESOLVED" == "$SERVER_IP" ]]; then DNS_OK=1; break; fi
  warn "解析到 ${RESOLVED:-无} ,还不是 $SERVER_IP"
  pause "DNS 生效可能要几分钟,改好/等一会儿再按 Enter 重试"
  RESOLVED=$(getent hosts "$DOMAIN" 2>/dev/null | awk '{print $1}' | head -n1 || true)
  [[ "$RESOLVED" == "$SERVER_IP" ]] && DNS_OK=1 && break
done
if [[ -n "$DNS_OK" ]]; then
  printf '  %s✓%s %s → %s\n' "$GREEN" "$RESET" "$DOMAIN" "$SERVER_IP"
else
  warn "DNS 还没生效,先继续;HTTPS 签发前必须生效,否则会卡在那一步。"
  SKIPPED+=("DNS A 记录未生效,HTTPS 阶段前再确认: getent hosts $DOMAIN")
fi

# ── Stage 3: security group ───────────────────────────────────────────────
stage "安全组放行端口(阿里云控制台)" 3

say "在你的电脑浏览器里操作:"
step "打开 https://ecs.console.aliyun.com/ → 实例 → 你的服务器 → 安全组"
step "入方向规则确认有:TCP 22(SSH)、TCP 80(HTTP)、TCP 443(HTTPS)"
step "没有就手动添加:授权策略 允许,协议 TCP,端口 80/80 与 443/443,授权对象 0.0.0.0/0"
pause "放行后按 Enter 继续"

# ── Stage 4: system packages + nginx ──────────────────────────────────────
stage "安装 git / nginx" 4

say "安装 git、nginx、curl(用 $PKG)。"
if [[ "$PKG" == "apt" ]]; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git nginx curl
else
  $PKG install -y -q git nginx curl
fi
systemctl enable --now nginx
printf '  %s✓%s nginx 已启动并设为开机自启\n' "$GREEN" "$RESET"

# ── Stage 5: Node.js via npmmirror (fast in mainland) ────────────────────
stage "安装 Node.js(npmmirror 国内源)" 4

if command -v node >/dev/null 2>&1 && [[ "$(node -v)" == v2[2-9]* || "$(node -v)" == v[3-9]* ]]; then
  printf '  %s✓%s 已有 %s,跳过安装\n' "$GREEN" "$RESET" "$(node -v)"
else
  ARCH=$(uname -m)
  case "$ARCH" in
    x86_64)        NODE_ARCH=linux-x64 ;;
    aarch64|arm64) NODE_ARCH=linux-arm64 ;;
    *) warn "不支持的架构 $ARCH"; exit 1 ;;
  esac
  say "从 npmmirror 解析 Node 22 LTS 最新版 ($NODE_ARCH)…"
  NODE_TARBALL=$(curl -m15 -s "https://registry.npmmirror.com/-/binary/node/latest-v22.x/" \
    | grep -o "node-v[0-9.]*-${NODE_ARCH}\.tar\.gz" | head -n1)
  if [[ -z "$NODE_TARBALL" ]]; then
    warn "解析 Node 版本失败。可手动到 https://registry.npmmirror.com/binary.html 下载 v22 $NODE_ARCH 包,解压后把 node/npm/npx 链接到 /usr/local/bin,再重跑本脚本。"
    exit 1
  fi
  note "下载 $NODE_TARBALL"
  curl -m300 -fsSL -o /tmp/node.tar.gz "https://registry.npmmirror.com/-/binary/node/latest-v22.x/$NODE_TARBALL"
  mkdir -p /opt/node
  tar -xzf /tmp/node.tar.gz -C /opt/node --strip-components=1
  ln -sf /opt/node/bin/node /usr/local/bin/node
  ln -sf /opt/node/bin/npm  /usr/local/bin/npm
  ln -sf /opt/node/bin/npx  /usr/local/bin/npx
  rm -f /tmp/node.tar.gz
fi
printf '  %s✓%s node %s · npm %s\n' "$GREEN" "$RESET" "$(node -v)" "$(npm -v)"

# ── Stage 6: bare repo + build hook, then local push ─────────────────────
stage "建裸仓库与自动构建钩子" 5

MEM_MB=$(free -m | awk '/^Mem:/{print $2}')
if [[ "$MEM_MB" -lt 2000 ]] && ! swapon --show | grep -q .; then
  warn "内存只有 ${MEM_MB}MB,vite build 可能不够。"
  if confirm "创建 2G swap 交换文件?(推荐)"; then
    fallocate -l 2G /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=2048
    chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
    grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
    printf '  %s✓%s 2G swap 已启用\n' "$GREEN" "$RESET"
  fi
fi

mkdir -p "$SITE_DIR" "$(dirname "$BARE_REPO")"
if [[ ! -d "$BARE_REPO" ]]; then
  git init --bare "$BARE_REPO" >/dev/null
fi

cat > "$BARE_REPO/hooks/post-receive" <<'HOOK'
#!/usr/bin/env bash
set -euo pipefail
export PATH=/usr/local/bin:/usr/bin:/bin:$PATH
SITE_DIR=/srv/asia-unhurried
BARE_REPO=/srv/git/asia-unhurried.git
DEPLOY_BRANCH=main

while read -r oldrev newrev refname; do
  [[ "$refname" == "refs/heads/$DEPLOY_BRANCH" ]] || continue
  echo "→ 检出 $DEPLOY_BRANCH 到 $SITE_DIR"
  git --work-tree="$SITE_DIR" --git-dir="$BARE_REPO" checkout -f "$DEPLOY_BRANCH"
  cd "$SITE_DIR"
  echo "→ npm ci(国内镜像源)"
  npm ci --registry=https://registry.npmmirror.com --no-audit --no-fund
  echo "→ npm run build"
  npm run build
  echo "✓ 构建完成,nginx 直接服务 $SITE_DIR/dist"
done
HOOK
chmod +x "$BARE_REPO/hooks/post-receive"
printf '  %s✓%s 裸仓库与 post-receive 钩子就绪\n' "$GREEN" "$RESET"

echo
say "现在回到【你的电脑】,在项目目录 D:\\asia-unhurried 里执行:"
echo
printf '    %sgit remote add aliyun ssh://root@%s%s%s\n' "$BOLD" "$SERVER_IP" "$BARE_REPO" "$RESET"
printf '    %sgit push aliyun main%s\n' "$BOLD" "$RESET"
echo
note "首次 push 约 500MB,走国内 SSH 链路,耐心等。推送时服务器会自动"
note "npm ci + build,输出会实时回显在你电脑上。"
note "如果之前 add 过同名 remote,先 git remote remove aliyun。"
pause "push 完成、看到构建成功提示后,按 Enter 继续"

if [[ -f "$SITE_DIR/dist/index.html" ]]; then
  printf '  %s✓%s 构建产物就位: %s/dist/index.html\n' "$GREEN" "$RESET" "$SITE_DIR"
else
  warn "没看到 $SITE_DIR/dist/index.html —— push 或构建可能没成功。"
  warn "确认后继续;也可以 Ctrl-C 退出,修好再重跑本脚本。"
  pause "按 Enter 继续"
fi

# ── Stage 7: nginx site config ────────────────────────────────────────────
stage "配置 Nginx(SPA 回退)" 3

WWW_NAME=""
if confirm "同时服务 www.$DOMAIN ?(需 DNS 已加 www 记录)"; then
  WWW_NAME=" www.$DOMAIN"
  write_env WWW "yes"
else
  write_env WWW "no"
fi

cat > /etc/nginx/conf.d/asia-unhurried.conf <<NGINX
server {
    listen 80;
    server_name $DOMAIN$WWW_NAME;

    root $SITE_DIR/dist;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1k;

    location /assets/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
    location /images/ {
        expires 7d;
    }
    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINX

nginx -t
systemctl reload nginx
printf '  %s✓%s nginx 配置已生效\n' "$GREEN" "$RESET"

HTTP_CODE=$(curl -m10 -s -o /dev/null -w '%{http_code}' "http://$DOMAIN/" || true)
if [[ "$HTTP_CODE" == "200" ]]; then
  printf '  %s✓%s http://%s 已可访问 (200)\n' "$GREEN" "$RESET" "$DOMAIN"
else
  warn "curl http://$DOMAIN/ 返回 ${HTTP_CODE:-失败}"
  note "常见原因: DNS 未生效 / 安全组 80 未放行 / nginx 未运行"
  note "自查: getent hosts $DOMAIN ; systemctl status nginx"
fi

# ── Stage 8: HTTPS certificate ────────────────────────────────────────────
stage "HTTPS 证书(Let's Encrypt)" 6

if [[ -n "$DNS_OK" ]] || confirm "DNS 当时未验证成功。现在 $DOMAIN 已解析到服务器了吗"; then
  if ! command -v certbot >/dev/null 2>&1; then
    say "安装 certbot…"
    if [[ "$PKG" == "apt" ]]; then
      DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot python3-certbot-nginx
    else
      $PKG install -y -q epel-release 2>/dev/null || true
      $PKG install -y -q certbot python3-certbot-nginx
    fi
  fi

  CERT_DOMAINS="-d $DOMAIN"
  [[ -n "$WWW_NAME" ]] && CERT_DOMAINS="$CERT_DOMAINS -d www.$DOMAIN"

  if certbot --nginx --non-interactive --agree-tos -m "$EMAIL" \
      --redirect $CERT_DOMAINS; then
    HTTPS_CODE=$(curl -m10 -s -o /dev/null -w '%{http_code}' "https://$DOMAIN/" || true)
    if [[ "$HTTPS_CODE" == "200" ]]; then
      printf '  %s✓%s https://%s 上线成功!\n' "$GREEN" "$RESET" "$DOMAIN"
    else
      warn "证书装好了,但 https 访问返回 ${HTTPS_CODE:-失败} —— 检查安全组 443 是否放行。"
    fi
  else
    warn "certbot 签发失败(常见:DNS 未生效 / 80 端口未通)。"
    SKIPPED+=("HTTPS 证书:修好 DNS/安全组后重跑: certbot --nginx -d $DOMAIN")
  fi
else
  warn "跳过 HTTPS。DNS 生效后执行: certbot --nginx -d $DOMAIN"
  SKIPPED+=("HTTPS 证书(certbot --nginx -d $DOMAIN)")
fi

# ──────────────────────────────────────────────────────────────────────────
finish

DOMAIN_SHOWN=$(_existing DOMAIN || echo "你的域名")
cat <<EOF
  站点: https://$DOMAIN_SHOWN

  以后更新网站,在你电脑上只需两步:
    git push origin main     # 备份到 GitHub(可选)
    git push aliyun main     # 推送到服务器,自动重新构建上线

  服务器上的关键位置:
    站点文件   $SITE_DIR/dist
    裸仓库     $BARE_REPO (post-receive 钩子在 hooks/ 下)
    nginx 配置 /etc/nginx/conf.d/asia-unhurried.conf
    部署记录   $ENV_FILE
EOF
