import type { CityContent } from './types'
import { EAT_CRITERIA, EAT_EXCLUDE, HELP_PHRASES, consularHotline, consularUse } from './shared'
import { cityImages } from './photoData'
import { CONTENT_CITIES } from '../directory'

const city = (slug: string) => {
  const c = CONTENT_CITIES.find((x) => x.slug === slug)
  if (!c) throw new Error(`missing directory city: ${slug}`)
  return c
}

const jnto = { label: '日本国家旅游局 JNTO', url: 'https://www.japan.travel/' }
const mofa = { label: '日本外务省：签证信息', url: 'https://www.mofa.go.jp/' }
const vjw = { label: 'Visit Japan Web', url: 'https://vjw-lp.digital.go.jp/' }
const jma = { label: '日本气象厅', url: 'https://www.jma.go.jp/' }
const consular = { label: '中国领事服务网', url: 'https://cs.mfa.gov.cn/' }

const japanDocuments = {
  id: 'documents',
  title: '证件与入境',
  summary: '护照有效期、签证与 Visit Japan Web，出发前分开核对。',
  stage: 'before' as const,
  recommendation:
    '日本对不同护照的入境政策不同：先按自己的证件在外务省或使领馆页面核对签证要求，再订不可退的交通与住宿。入境与海关申报可提前用 Visit Japan Web 线上完成。',
  steps: [
    {
      title: '先按证件查签证要求，不按攻略',
      body: '同一行程，不同护照的要求不同。在日本外务省或就近使领馆页面按国籍／证件核对；政策可能调整，以官方页面当前版本为准。',
    },
    {
      title: '护照与返程材料放一起',
      body: '核对护照有效期是否覆盖行程并有富余。保存返程机票订单、首晚酒店名称与地址、同行人联系方式，入境时可能被询问。',
    },
    {
      title: '提前填 Visit Japan Web',
      body: '官网注册后填写入境记录与海关申报，生成二维码。截图离线保存；不会用英文界面时，换行到现场填写纸质卡也有效。',
    },
    {
      title: '落地后走对应通道',
      body: '持 QR 码按现场指引走电子通道或人工通道。收好入境许可信息，按获准停留期限离境。',
    },
  ],
  done: '签证要求已按本人证件核实，Visit Japan Web 已填好或确认可现场办理，订单离线可查。',
  fallback: '签证材料有疑问时先联系使领馆或签证受理机构，不要到机场再处理；线上系统故障时备纸质填写方案。',
  sources: [mofa, vjw, consular],
}

const japanMobile = (airportName: string) => ({
  id: 'mobile',
  title: '上网与手机',
  summary: '先确认手机支持什么方案，再决定 eSIM、实体卡还是漫游。',
  stage: 'before' as const,
  recommendation:
    '国内运营商漫游包最省事；需要当地流量可选 eSIM（先确认手机支持）或落地后买实体游客卡／随身 Wi-Fi。日本机场到达厅均有运营商柜台。',
  steps: [
    {
      title: '先查手机支持哪类方案',
      body: 'eSIM 只在部分机型可用，国内购买的国行手机多数不支持。查厂商说明再下单，不要只看商品页宣传。',
    },
    {
      title: '按天数比一次总价',
      body: '把国内漫游包总价、eSIM 套餐、机场游客卡按你的天数逐项比较；注意计时起点（购买日／激活日／首次连接）。',
    },
    {
      title: '保留一条备用路',
      body: `在${airportName}到达厅仍有运营商柜台和随身 Wi-Fi 租赁；方案失败时落地再办。出发前截图保存酒店地址与地图。`,
    },
    {
      title: '落地先测网络再离开柜台',
      body: '关掉 Wi-Fi 打开地图，给同行人发条消息；用当地卡时关闭国内卡的数据漫游，避免双卡互抢。',
    },
  ],
  done: '离开 Wi-Fi 能开地图、发消息；知道套餐何时到期。',
  fallback: '无网时先连机场免费 Wi-Fi 联系客服；备用国内漫游包可应急。',
  sources: [jnto],
})

const japanStay = (areas: string) => ({
  id: 'stay',
  title: '住宿与入住',
  summary: '选一处枢纽旁住稳，确认晚到取钥匙的方案。',
  stage: 'before' as const,
  recommendation: `日本酒店多按「人头」计价而非按房，订房时如实填人数。优先选${areas}一带、靠近轨道交通站的住处；小城市房间普遍紧凑，订前看平米数与床宽。`,
  steps: [
    {
      title: '用晚间返程路线筛区域',
      body: '把酒店放在你晚上吃饭和散步的片区内，再看离车站的实际步行路径——「距地铁 300 米」可能含楼梯与坡道。',
    },
    {
      title: '核对房型与人数规则',
      body: '日本酒店按入住人数计费，加人可能加价或换房型。核对平米数、床宽、独立卫浴、电梯是否到楼层；温泉旅馆看是否含餐、入浴时间。',
    },
    {
      title: '确认总价与取消规则',
      body: '付款页看含税总价、住宿税（部分城市另收）与取消截止；截图保存最终金额。',
    },
    {
      title: '把晚到问题提前解决',
      body: '给小旅馆发消息确认晚到取钥匙方式；保存日文地址与电话，离线可给司机或路人看。',
    },
  ],
  done: '总价、人数规则、晚到方案、从车站到门口的路线都已确认。',
  fallback: '酒店无法说明晚到流程时改订可取消的住处；现场无房先联系预订平台协调。',
  sources: [jnto],
})

const japanAlerts = (cityName: string) => [
  {
    title: '地震与台风',
    body: '日本地震多发，夏秋有台风。落地后留意酒店逃生指示；手机可装官方或可信的灾害速报应用，行程中关注气象厅预警。',
    source: jma,
  },
  {
    title: '末班轨道交通较早',
    body: '多数线路末班在午夜前后，错过末班出租车费高。晚上出门先查返程末班，留一趟可走的备用路线。',
    source: jnto,
  },
  {
    title: '闹市拉客与高价店',
    body: `${cityName}闹市区的主动拉客、模糊报价的酒吧与「陪酒」场所是常见纠纷来源。不进无明码标价的店，不接受街头带路。`,
    source: jnto,
  },
  {
    title: '温泉与公共浴场规则',
    body: '入浴前先冲洗，长发盘起，毛巾不入池；部分浴场对有纹身者有限制，先查设施规定。',
    source: jnto,
  },
]

export const tokyo: CityContent = {
  city: city('tokyo'),
  checkedAt: '2026-09-14',
  meta: [
    { label: '最佳季节', value: '春秋为主；夏天湿热，冬天干冷但晴天多。樱枫季人多价高，提前订。' },
    { label: '机场', value: '羽田（HND）近市区；成田（NRT）国际线多，进城需一小时上下。' },
    { label: '建议停留', value: '4–6 晚。3 晚只够两三个片区；按片区住稳比跨城打卡有用。' },
    { label: '地区标签', value: '东亚' },
    { label: '气质', value: '片区制大都市：下町、丸之内、山手西侧各有节奏' },
  ],
  essentials: [
    {
      title: '机场 → 市区',
      body: '成田进城主流是京成 Skyliner（到上野）与 JR 成田特快 N\'EX（到新宿／东京站），另有 Access 特急与机场巴士；羽田用京急线或东京单轨。先定酒店片区再选线，别只看车程——算上车站到酒店的一段。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [
        { label: '京成电铁', url: 'https://www.keisei.co.jp/' },
        { label: 'JR 东日本', url: 'https://www.jreast.co.jp/' },
      ],
    },
    {
      title: '建议住哪',
      body: '第一次来，新宿（西口方向换乘多、吃饭方便）或上野（往北接成田、邻谷根千散步区）都好住。想安静选日本桥／神保町方向。全程住一处，不要为追景点换酒店。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '3 晚安排抵达、两个片区和离开；5 晚再加一个生活区（吉祥寺或中野）与一次留白。每天只定一个主方向，地铁连接其余。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '东京不是一座城，是一串片区：新宿、上野、浅草、银座各有各的节奏。慢旅行的做法是把其中一个片区当作「住处」，其余每天只去一个方向。',
    '山手线成环，大部分片区都在环上或环内。住新宿意味着晚上有饭吃、有站可回；住上野意味着向北去成田、向老下町散步都顺。',
    '馆与公园不要连着排：国立博物馆半天、新宿御苑半天，中间留一顿正经午饭。东京的密度会奖励「少排一件事」。',
    '别把「东京」当作可以走完的清单。本页只按片区组织：选住处、选每天的方向、留一顿认真吃的饭。',
  ],
  gettingThere: {
    intro: [
      '成田（NRT）进城约一小时：京成 Skyliner 到日暮里／上野，JR 成田特快 N\'EX 到东京站／新宿方向，Access 特急与机场巴士是备选。羽田（HND）近市区，京急线到品川接 JR，或东京单轨到滨松町。',
      '市内以 JR 山手线 + 地铁为主，配一张 Suica 或 Pasmo 刷卡进出；手机可加电子卡。东京地铁有 24／48／72 小时通票（Tokyo Subway Ticket），按你的出行密度决定是否划算。',
      '出租车贵且末班轨道早，夜间出门前查返程末班。高峰时段的站内换乘步行可能很长，行李多就避开。',
    ],
    links: [
      { label: '东京地铁通票', url: 'https://www.tokyometro.jp/' },
      { label: 'JR 东日本 Suica', url: 'https://www.jreast.co.jp/' },
    ],
    verifyReminders: [
      '成田特快 N\'EX 当前停靠站与是否仍需全车指定席',
      '京成 Skyliner 与 Access 特急的票价差、到上野的实际用时',
      '东京地铁通票的适用范围（不含 JR）与售价',
      'Welcome Suica 等无押金游客卡的当前发售情况',
    ],
  },
  neighborhoods: [
    {
      id: 'shinjuku',
      title: '新宿',
      suited: '第一次来、要换乘方便、晚上有饭吃的人。',
      image: cityImages['tokyo-shinjuku'],
      body: '新宿是枢纽也是片区：西口接机场巴士与京王线，东口是闹市区，南边有新宿御苑。把它当住处，不当景点——每天从这里出发，晚上回来吃饭。',
      visit: {
        duration: '散步 1–2 小时；新宿御苑另留半天。',
        entry: 'JR／地铁新宿站；站内极大，先选一个出口（西口、东口或南口）再动身。',
        walk: '新宿站 → 新宿御苑（或西口都厅方向），闹市区晚上看，不必白天排进去。',
        return: '回新宿站；末班前查线路，深夜出租车从新宿出发很贵。',
        stay: '适合多数第一次来的人；核对酒店离哪个出口近，站内换乘本身耗体力。',
        source: { label: '东京官方旅游指南 Go Tokyo', url: 'https://www.gotokyo.org/' },
      },
    },
    {
      id: 'ueno',
      title: '上野与谷根千',
      suited: '想看博物馆、又想在老街区慢慢走的人。',
      image: cityImages['tokyo-ueno'],
      body: '上野公园集中了国立博物馆等馆舍；公园北侧的谷中、根津、千驮木是保留下来的老街区，坡道小店适合下午散步。Skyliner 到上野，北向行程顺。',
      visit: {
        duration: '博物馆半天 + 谷根千 1.5–2 小时，分开排。',
        entry: 'JR／地铁上野站；谷根千从日暮里站或千驮木站进入。',
        walk: '上野公园馆内选一两处 → 午后往谷中银座方向走，坡道下行多，慢走。',
        return: '日暮里站或上野站返回；谷中商店街傍晚收得早，别排太晚。',
        stay: '住上野去成田方便；酒店比新宿便宜但夜里安静，适合早睡的人。',
        source: { label: '东京国立博物馆', url: 'https://www.tnm.jp/' },
      },
    },
    {
      id: 'asakusa',
      title: '浅草与藏前',
      suited: '想看下町风情、早起逛寺的人。',
      image: cityImages['tokyo-asakusa'],
      body: '浅草寺清晨比白天好走；雷门商业街白天人多，拐进旁边的藏前手作街区反而安静。把浅草排在一个早上，不把整片闹市当下午。',
      visit: {
        duration: '2–3 小时；清晨走最好。',
        entry: '银座线／浅草线浅草站。',
        walk: '浅草寺 → 仲见世通拐出 → 藏前方向小店街。',
        return: '浅草站返回；上午走完回住处午睡或去上野。',
        stay: '浅草有旅馆但离多数片区远，住这里等于把每天的第一程固定成进城。',
        source: { label: '浅草寺官网', url: 'https://www.senso-ji.jp/' },
      },
    },
    {
      id: 'nihonbashi-ginza',
      title: '日本桥与银座',
      suited: '想安静逛街区、看老百货与画廊的人。',
      image: cityImages['tokyo-nihonbashi'],
      body: '日本桥是旧街道起点，银座的老百货和背街画廊密度高。这个方向节奏比新宿慢，适合把「逛街」本身当作半天内容。',
      visit: {
        duration: '2–3 小时。',
        entry: '地铁日本桥站或银座站。',
        walk: '日本桥 → 室町／京桥背街 → 银座并木通；周末银座有步行者天国时段（以官网为准）。',
        return: '银座站返回；晚餐可在这一带解决，但热门店要早去。',
        stay: '商务区周末安静，酒店价格浮动大；去东京站方便。',
        source: { label: '东京官方旅游指南 Go Tokyo', url: 'https://www.gotokyo.org/' },
      },
    },
    {
      id: 'kichijoji',
      title: '吉祥寺与中野',
      suited: '多住几晚、想看生活区的人。',
      image: cityImages['tokyo-kichijoji'],
      body: '中央线向西，吉祥寺有井之头公园和商店街，中野是平民小商圈。这个方向不是景点，是东京人日常生活的样子——第五晚以后值得花一天。',
      visit: {
        duration: '半天到一天。',
        entry: 'JR 中央线吉祥寺站或中野站。',
        walk: '吉祥寺：井之头公园 → 口琴横丁小巷；中野：中野百老汇商店街。',
        return: '中央线回新宿方向；两站同在一条线上，别硬塞进同一个下午。',
        stay: '没必要为此换住处；从新宿出发单程约 15–20 分钟。',
        source: { label: '东京官方旅游指南 Go Tokyo', url: 'https://www.gotokyo.org/' },
      },
    },
  ],
  stay: {
    checkedAt: '2026-09-14',
    intro:
      '东京先选「圈」再选房：山手线圈内、地铁站步行十分钟内是默认答案。酒店多按人头计价而非按房，订时如实填人数；房间普遍紧凑，平米数和床宽比广角照片可信。',
    budgetNote:
      '以 ¥700–800/晚为上限：在东京是紧凑中档——多数日期够到连锁商务酒店的双人房；樱花、红叶季与大型活动期明显上浮，那段时间要么早订可取消，要么错开日期。',
    anchors: [
      { title: '山手线圈内 + 站旁十分钟', body: '不看「距市中心几公里」，看离哪条线、哪个站、步行几分钟；站内换乘本身耗体力，住处到闸机越短越好。' },
      { title: '按行程重心选半边城', body: '吃与逛偏东（上野、浅草、银座方向）还是偏西（新宿、涩谷方向）？住同一侧，每天少一次大换乘。' },
      { title: '按到达机场定方向', body: '成田抵达看 Skyliner／N\'EX 沿线（上野、东京站方向）；羽田抵达看京急／单轨衔接（品川、滨松町方向）。' },
    ],
    areas: [
      {
        id: 'ueno-asakusa-stay',
        title: '上野 – 浅草',
        suitsIf: '想省钱、吃老东京、成田进出的人。',
        budgetFeel: '这档预算选择最多，同价房间明显大。',
        band: { low: 400, high: 820 },
        transit: '上野站（山手线、京成 Skyliner）；浅草站（银座线、浅草线）。',
        food: '下町老街食肆、立饮屋密集，日常餐便宜。',
        tradeoff: '去新宿／涩谷方向单程半小时以上；夜里比西岸安静得早。',
        neighborhoodIds: ['ueno', 'asakusa'],
      },
      {
        id: 'shinjuku-stay',
        title: '新宿',
        suitsIf: '想要枢纽、晚到、去哪都直达的人。',
        budgetFeel: '同预算多为小房；歌舞伎町一侧要挑街。',
        band: { low: 680, high: 1280 },
        transit: '新宿站：山手线＋多线交汇，机场利木津巴士直达方向多。',
        food: '密度极高但游客价也多，往巷子里走更日常。',
        tradeoff: '车站巨大易迷路；周末深夜嘈杂。',
        skipIf: '怕吵、带老人小孩、想要早睡的片区。',
        neighborhoodIds: ['shinjuku'],
      },
      {
        id: 'nihonbashi-tokyostation',
        title: '日本桥 – 东京站',
        suitsIf: '早班新干线／成田特快、行程偏「看」的人。',
        budgetFeel: '这档预算偏紧，多为紧凑商务房。',
        band: { low: 550, high: 1350 },
        transit: '东京站：新干线与成田特快；日本桥、京桥各线步行圈内。',
        food: '百货地下与名店多；日常平价店往有乐町／京桥背街找。',
        tradeoff: '商务区晚上安静得快；同价房间比上野小。',
        neighborhoodIds: ['nihonbashi-ginza'],
      },
      {
        id: 'ikebukuro-stay',
        title: '池袋',
        suitsIf: '预算优先又要枢纽的人。',
        budgetFeel: '同预算房间比新宿大，连锁商务酒店多。',
        band: { low: 550, high: 1000 },
        transit: '池袋站：山手线＋私铁，机场巴士方向也有。',
        food: '百货食街够用，巷子店分散要挑。',
        tradeoff: '东口夜生活杂；选房靠西口或公园一侧更安静。',
      },
    ],
  },
  dayTrips: [
    { direction: '镰仓 · 江之岛', how: '新宿小田急或 JR 湘南新宿线约一小时', worth: '海岸加寺社，能走一天。周末人多，平日去；别和热海塞进同一天。' },
    { direction: '横滨', how: 'JR／东急约 30–40 分钟', worth: '港未来海旁加中华街，半天到一天；比镰仓轻松，适合阴雨天换口味。' },
    { direction: '日光', how: '东武／JR 约两小时', worth: '东照宫与山地，值得一天但路程长；五晚以上再考虑。' },
  ],
  dayTripNote: '镰仓与横滨平日更松；日光路程长，五晚以上再排。班次与天气当天早上看。',
  eatIntro:
    '东京的吃不需要追榜单：便利店解决早餐、中午吃定食、晚上认真坐一顿。拉面与立食寿司是快餐逻辑，居酒屋是坐下来的时段——分清楚再进。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'ramen', title: '拉面与蘸面',
      intro: '东京拉面是快餐逻辑：食券机先买票，吃完让座。蘸面（つけ麺）是东京发源的另一条线——浓汤配粗面，排大队是常态。',
      restaurants: [
        {
          id: 'rokurinsha', name: '六厘舍', nameEn: 'Rokurinsha', neighborhood: '东京站一番街',
          location: { address: '東京駅一番街 B1 東京ラーメンストリート内', areaId: 'nihonbashi-ginza', connection: 'JR 东京站八重洲地下口进一番街即达', source: { label: '官网', url: 'https://www.rokurinsha.com/' } },
          order: ['招牌つけ麺（蘸面）', '加叉烧／大盛在食券机上选好'],
          whyLinger: '东京蘸面的代表店：鱼介豚骨浓汤配特粗面。它在东京站地下街里，专程去吃一顿而不是路过。',
          practical: '食券机购票；营业时间随东京站一番街，以官网为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.rokurinsha.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=六厘舎+東京駅一番街' }],
          queueNote: '开门前后与 15 点后队最短；高峰排队 30–60 分钟。',
        },
        {
          id: 'fuunji', name: '风云儿', nameEn: 'Fuunji', neighborhood: '新宿',
          location: { address: '東京都渋谷区代々木 2-14-1', areaId: 'shinjuku', connection: 'JR 新宿站南口／都营大江户线新宿站步行约 5 分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=風雲児+新宿' } },
          order: ['つけ麺（蘸面）', '特製加全部配料'],
          whyLinger: '新宿一侧最著名的蘸面小店，浓汤挂面力极强。店面小、翻台快，当快餐吃。',
          practical: '食券机购票、店外排队；座位约十席，吃完让座是规矩。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=風雲児+新宿' }],
          queueNote: '饭点常排 20–40 分钟；开门时段人最少。',
        },
      ],
    },
    {
      id: 'sushi', title: '寿司与回转',
      intro: '寿司分几个层级：回转、立食、午市套餐、晚间おまかせ。第一次来从回转或午市开始，不必直接挑战高价柜台。',
      restaurants: [
        {
          id: 'midori-sushi', name: '美登利寿司', nameEn: 'Umegaoka Sushi no Midori', neighborhood: '涩谷',
          location: { address: '渋谷マークシティ（渋谷店）／总店在世田谷梅丘', connection: '渋谷店在 Mark City 内；总店离市区较远', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=美登利寿司+渋谷' } },
          order: ['当季推荐握寿司套餐', '穴子（星鳗）是招牌之一'],
          whyLinger: '价格与品质比出名的回转寿司——美登利从鱼市起家，同样预算吃到的东西高一档。',
          practical: '等位制，饭点拿号等 30–60 分钟常见；分店不止一家，以官网店址为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=美登利寿司+渋谷' }],
          queueNote: '饭点必排；取号后可以在 Mark City 内先逛。',
        },
        {
          id: 'nemuro-hanamaru', name: '根室花丸', nameEn: 'Nemuro Hanamaru', neighborhood: '丸之内 KITTE',
          location: { address: 'KITTE丸の内 B1', areaId: 'nihonbashi-ginza', connection: 'JR 东京站丸之内口步行即到', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=根室花まる+KITTE丸の内' } },
          order: ['按盘子颜色计价，随转随拿', '北海道产贝类与牡丹虾'],
          whyLinger: '北海道发源的回转寿司，鲜度与价格比一般东京回转高半档；KITTE 店交通极方便。',
          practical: '取号等位；盘子颜色计价。以现场与官网店址为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=根室花まる+KITTE丸の内' }],
          queueNote: '晚餐高峰排队；开门时段进最稳。',
        },
      ],
    },
    {
      id: 'teishoku', title: '定食与炸猪排',
      intro: '一饭一汤三菜的定食是上班族午餐，也是旅行者最划算的正餐；炸猪排是定食里的「硬菜」线。',
      restaurants: [
        {
          id: 'maisen', name: '舞泉', nameEn: 'Tonkatsu Maisen', neighborhood: '表参道',
          location: { address: '東京都渋谷区神宮前 4-8-5', connection: '表参道站 A2 口步行约 5 分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=まい泉+表参道' } },
          order: ['黒豚炸猪排定食', '炸虾或里脊定食'],
          whyLinger: '东京最著名的炸猪排店之一，本店是旧澡堂改建——空间本身就是内容。猪肉嫩到用筷子能切断是店家的招牌说法。',
          practical: '本店席位较多翻台不慢；菜单有图，点单不难。营业时间以官网为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=まい泉+表参道' }],
        },
        {
          id: 'ootoya', name: '大户屋', nameEn: 'Ootoya', neighborhood: '全国连锁',
          location: { address: '各主要车站与商圈均有门店', connection: '按住处附近搜「大戸屋」', source: { label: '官网', url: 'https://www.ohtoya.com/' } },
          order: ['炭火烧鱼定食', '鸡肉蔬菜黑醋定食'],
          whyLinger: '连锁保底项：现做的定食连锁，菜单有中文/英文，一个人吃也不尴尬。不是体验，是托底。',
          practical: '店内点餐付现金或卡；午间定食最划算。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.ohtoya.com/' }],
        },
      ],
    },
    {
      id: 'izakaya', title: '酒场与居酒屋',
      intro: '居酒屋是晚上坐下来的地方：先上收费小菜（お通し），再点烤串、刺身、炸物。连锁店价格透明，老酒场看黑板。',
      restaurants: [
        {
          id: 'kamiya-bar', name: '神谷 Bar', nameEn: 'Kamiya Bar', neighborhood: '浅草',
          location: { address: '東京都台東区浅草 1-1-1', areaId: 'asakusa', connection: '浅草站步行约 3 分钟，雷门方向', source: { label: '官网', url: 'https://www.kamiya-bar.com/' } },
          order: ['电气ブラン（Denki Bran）', '炖牛肉（ビーフシチュー）'],
          whyLinger: '1880 年创业的老酒场——日本最早的 Bar 之一，自酿的「电气白兰地」是招牌。浅草逛完在这里收尾，比回市区再吃好。',
          practical: '吧台与桌席；电气ブラン是甜口烈酒，别当普通白兰地喝。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.kamiya-bar.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=神谷バー+浅草' }],
        },
        {
          id: 'torikizoku', name: '鸟贵族', nameEn: 'Torikizoku', neighborhood: '全国连锁',
          location: { address: '各主要商圈均有门店', connection: '按住处附近搜「鳥貴族」', source: { label: '官网', url: 'https://www.torikizoku.co.jp/' } },
          order: ['烤鸡肉串（焼鳥）', '卷心菜无限续'],
          whyLinger: '统一价的连锁居酒屋：菜均一价（以店内现价为准），看不懂菜单也点不坏。保底项，不是体验项。',
          practical: '平板点单；先按人头点饮料是默认规则。お通し费已含在价内。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.torikizoku.co.jp/' }],
        },
      ],
    },
    {
      id: 'tsukiji', title: '筑地场外与带走吃',
      intro: '场外市场仍在原址做游客与街坊生意：玉子烧串、海鲜饭、牛杂煮——当早餐加散步，不当正餐。',
      restaurants: [
        {
          id: 'kitsuneya', name: '狐狸屋', nameEn: 'Kitsuneya', neighborhood: '筑地场外',
          location: { address: '築地場外市場内（築地 4 丁目）', connection: '日比谷线筑地站步行约 5 分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=きつねや+築地' } },
          order: ['牛丼', '肉豆腐'],
          whyLinger: '筑地最有名的站着吃的牛丼老摊——一锅牛肉豆腐煮了几十年。市场早餐的定番。',
          practical: '摊位式小店现金为主；早上开、卖完收，午后可能已关。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=きつねや+築地' }],
        },
        {
          id: 'marutake', name: '丸武', nameEn: 'Marutake', neighborhood: '筑地场外',
          location: { address: '築地場外市場内', connection: '与狐狸屋同在市场巷内', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=丸武+築地' } },
          order: ['玉子烧串（现烤）'],
          whyLinger: '筑地玉子烧的定番店——现烤的厚玉子串在竹签上边烤边卖，100 日元档的散步小吃。',
          practical: '现金小摊；一串就是一口量，别指望吃饱。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=丸武+築地' }],
        },
      ],
    },
  ],
  howToOrder: [
    '食券机店：先在门口机器买票再入座，多数机器只收现金或 IC 卡。',
    '拉面店翻台快：想好再排，吃完不逗留；加面（替玉）点单时说。',
    '居酒屋：坐下会先收お通し小菜费；按人数点酒再点菜。',
    '寿司店：午市套餐（ランチ）比晚市便宜很多；回转店按盘子颜色计价。',
    '便利店：买好东西在收银台说要点餐加热（あたため），袋子自取。',
  ],
  avoid: [
    '别为社交媒体名店横穿全城排队——同品类在住处附近找一家，差别没有路程大。',
    '新宿歌舞伎町、六本木方向的主动拉客与模糊报价店不进；看清门口标价再进。',
    '筑地「场内市场」已迁丰洲，导航时认准「场外市场」，别跑空。',
    '景区门口的「会讲中文」招牌店不等于本地日常，按上面品类选。',
  ],
  eatRhythm:
    '早餐用便利店或咖啡馆解决；中午走到哪就在哪吃定食或一碗面；晚上只认真坐一顿——居酒屋或当天片区里看得顺眼的店。一天不排两家需要排队的店。',
  allergies: [
    '出汁（だし）几乎普遍含鲣鱼，素食与鱼过敏要逐店确认。',
    '酱油普遍含麸质；荞麦面可能混小麦粉。',
    '「アレルギー」三字写下来给店员看，比口头说可靠。',
  ],
  guide: {
    city: '东京',
    checkedAt: '2026-09-14',
    scope: '以公共交通为主的首次东京行程；签证与入境按本人证件另核官方要求',
    intro: '第一次来东京，先把入境、网络、支付和住处安排好。以下按 4–6 晚、住单一片区写；每项写到能完成一次操作。',
    topics: [
      japanDocuments,
      japanMobile('成田／羽田机场'),
      {
        id: 'payment',
        title: '支付与现金',
        summary: '东京刷卡普及但现金仍常用，再配一张交通 IC 卡。',
        stage: 'before',
        recommendation: '大城市店铺多数收卡与电子支付，但小店、食券机、神社寺院仍以现金为主。带一张可境外取现的卡备日元现金，再加一张 Suica／Pasmo 处理交通与小额付款。',
        steps: [
          { title: '出发前确认银行卡境外功能', body: '在发卡行 App 确认境外刷卡与 ATM 取现已开通、限额与手续费；带本人实体卡。' },
          { title: '备首日现金', body: '按机场交通、两餐与小额消费估算；日本便利店 ATM（7-11 等）普遍支持境外卡取现，作为补充方案。' },
          { title: '落地先拿一张 IC 卡', body: '机场或车站买 Welcome Suica／Pasmo，或按官方指引在手机上添加电子卡；交通、便利店、自动贩卖机都能刷。' },
          { title: '刷卡时看币种', body: '机器若提示「换成人民币计价」，选当地货币 JPY 更稳；保存大额消费收据。' },
        ],
        done: '现金够首日、IC 卡可用、银行卡确认能刷能取。',
        fallback: 'IC 卡买不到时用现金买票；取现失败换 7-11 等便利店 ATM 再试。',
        sources: [{ label: 'JR 东日本：Suica', url: 'https://www.jreast.co.jp/' }, jnto],
      },
      japanStay('新宿或上野'),
      {
        id: 'arrival',
        title: '机场 → 酒店',
        summary: '成田与羽田是两条不同的进城线，先按住处片区选。',
        stage: 'arrival',
        recommendation: '成田落地：住处在上野／日暮里方向选京成 Skyliner，在新宿／东京站方向选成田特快 N\'EX；行李多或深夜到选机场巴士或正规出租车。羽田落地：京急线到品川转 JR，或单轨到滨松町。',
        choices: [
          { title: '成田（NRT）', body: 'Skyliner 到上野约 40 分钟；N\'EX 到东京站／新宿约一小时。Access 特急便宜但慢；机场巴士按酒店片区选线。' },
          { title: '羽田（HND）', body: '京急线到品川约 15–20 分钟再转 JR；单轨到滨松町接山手线。深夜到达选出租车或确认末班。' },
        ],
        steps: [
          { title: '落地前把路线截图存好', body: '记下交通方式、下车站、站内换乘与末班时间；用预计出关时间而不是降落时间判断。' },
          { title: '先连网再离开到达厅', body: '打开地图确认酒店地址与所选线路；需要买 IC 卡或 SIM 在到达厅一次办完。' },
          { title: '按标识找对应车站', body: '成田的京成与 JR 是不同站口；买票时说清终点站名，看不懂售票机就去人工窗口。' },
          { title: '下车后用导航走完最后一段', body: '新宿等大站出口多，出站先找地面再导航；深夜到站优先出租车补完最后一段。' },
        ],
        done: '人与行李到酒店，知道回程从哪里出发、末班几点。',
        fallback: '错过末班时，机场与主要车站有正规出租车排队区；不要跟主动揽客的人走。',
        sources: [
          { label: '成田机场交通', url: 'https://www.narita-airport.jp/' },
          { label: '羽田机场交通', url: 'https://tokyo-haneda.com/' },
          { label: '京成电铁', url: 'https://www.keisei.co.jp/' },
        ],
      },
      {
        id: 'transit',
        title: '市内交通',
        summary: 'JR 山手线加地铁，一张 IC 卡刷到底。',
        stage: 'during',
        recommendation: '日常移动靠 JR 山手线、地铁与步行。东京地铁通票（24／48／72 小时）只覆盖地铁两家，不含 JR——先按你每天的坐车次数算是否划算，不盲目买。',
        steps: [
          { title: '查路线分清 JR 与地铁', body: '同一出发到达可能有两家线路；IC 卡两家通刷，通票只覆盖地铁。进出闸用同一张卡。' },
          { title: '大站换乘当一段路算', body: '新宿、东京、池袋站内换乘可能走十分钟以上；带行李避开高峰。' },
          { title: '记住末班大约在午夜', body: '出门晚餐前先查回程末班；错过末班改正规出租车，不进揽客车。' },
          { title: '出站先认出口编号', body: '大站按出口编号（A1、西口等）对照地图；错了出口可能要多走一公里。' },
        ],
        done: '会用 IC 卡进出、会查末班、知道酒店最近出口。',
        fallback: '迷路时回最近车站闸口看站内地图；出租车扬招点与车站前排队区最可靠。',
        sources: [{ label: '东京地铁', url: 'https://www.tokyometro.jp/' }, { label: 'JR 东日本', url: 'https://www.jreast.co.jp/' }],
      },
    ],
    checklist: [
      { id: 'c-docs', text: '签证要求已按本人证件核实；Visit Japan Web 已填或确认可现场填', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效期覆盖行程并有富余；返程订单与首晚酒店信息离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '手机上网方案已选定（漫游／eSIM／落地购买），备用方案明确', topic: '上网与手机' },
      { id: 'c-pay', text: '银行卡境外功能已开通；备有首日日元现金', topic: '支付与现金' },
      { id: 'c-ic', text: 'Suica／Pasmo 的购买或手机添加方式已确认', topic: '支付与现金' },
      { id: 'c-stay', text: '酒店总价、人数规则、晚到取钥匙方式已书面确认', topic: '住宿与入住' },
      { id: 'c-arrival', text: '机场到酒店的线路、下车站与末班时间已截图', topic: '机场 → 酒店' },
      { id: 'c-last', text: '已查酒店附近的末班轨道时间并保存', topic: '市内交通' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：一个片区住稳',
      note: '全程一家酒店。每天一个主方向，不追打卡；第三天按航班时间收尾。',
      days: [
        { day: '第一天', body: '抵达、入住，只在住处附近散步和吃一顿饭。', time: '按落地时间安排；晚上早睡', start: '机场 → 酒店', return: '住处附近晚餐后回', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '上午浅草方向，午后上野公园或谷根千散步。晚上回住处附近吃。', time: '上午出门、下午慢走', start: '住处 → 浅草', return: '上野／日暮里一带返回', links: [{ label: '上野与谷根千', href: '?tab=places#area-ueno' }] },
        { day: '第三天', body: '明治神宫或新宿御苑散步，留返程缓冲去机场。', time: '上午散步，午后取行李', start: '住处 → 明治神宫方向', return: '酒店取行李 → 机场', links: [{ label: '看点速览', href: '?tab=places' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加一个生活区',
      note: '在 3 晚骨架上加一天生活区与一天留白；留白用来补天气或体力，不追加打卡点。',
      days: [
        { day: '第一天', body: '抵达、入住，住处附近吃饭早睡。', time: '按落地时间安排', start: '机场 → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '浅草 + 上野方向，一天只走这一条线。', time: '上午浅草、下午谷根千', start: '住处 → 浅草', return: '上野返回', links: [{ label: '浅草与藏前', href: '?tab=places#area-asakusa' }] },
        { day: '第三天', body: '明治神宫 + 新宿方向；晚上就在住处一带吃。', time: '上午散步、下午自由', start: '住处 → 明治神宫', return: '新宿一带', links: [{ label: '新宿', href: '?tab=places#area-shinjuku' }] },
        { day: '第四天', body: '吉祥寺或中野半天生活区散步；下午留白或补买。', time: '半天出门、半天留白', start: '中央线向西', return: '回住处方向', links: [{ label: '吉祥寺与中野', href: '?tab=places#area-kichijoji' }] },
        { day: '第五天', body: '筑地场外早餐 + 日本桥／银座散步，按航班收尾。', time: '上午市场、午后收尾', start: '住处 → 筑地', return: '酒店 → 机场', links: [{ label: '日本桥与银座', href: '?tab=places#area-nihonbashi-ginza' }] },
      ],
    },
  },
  safety: {
    city: '东京',
    checkedAt: '2026-09-14',
    emergencyNote: '东京治安总体好，真正要准备的是灾害与就医流程。保存酒店地址与日文地址，必要时给路人或工作人员看。',
    contacts: [
      { name: '报警', number: '110', dial: '110', use: '盗窃、遗失、交通事故、人身安全问题', source: { label: '警视厅', url: 'https://www.keishicho.metro.tokyo.lg.jp/' }, urgent: true },
      { name: '急救 / 火灾', number: '119', dial: '119', use: '急救车与火警；说明地点、症状、人数', source: { label: '东京消防厅', url: 'https://www.tfd.metro.tokyo.lg.jp/' }, urgent: true },
      { name: 'JNTO 游客热线', number: '050-3816-2787', dial: '+815038162787', use: '24 小时多语种旅游咨询与紧急情况协助', source: jnto },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '护照、签证材料、订单截图离线保存一份；云端再存一份。',
      '保存酒店日文地址与电话，迷路时给人看。',
      '下载离线地图与翻译应用；确认手机在无网时仍能出示凭证。',
      '购买含境外医疗的旅行保险，保单号与救援电话另存。',
      '装一个灾害速报应用（如官方 Safety tips 或 NERV），打开通知权限。',
      '记熟 110 / 119；只有流量的套餐不能打普通电话，想好替代求助路径。',
    ],
    alerts: japanAlerts('东京'),
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['先到最近交番（派出所）或警署报失，拿遗失证明。', '联系中国驻日使领馆补办旅行证件（先电话预约）。', '通知保险公司并保留报失证明作理赔材料。', '行程改签前确认新证件的出入境可用性。'], sources: [consular, { label: '中国驻日本大使馆', url: 'https://jp.china-embassy.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急情况拨 119 叫救护车；说清地点与症状。', '非紧急先问酒店前台推荐会英语的诊所。', '保留所有收据与诊断证明，回国走保险理赔。', '常用药自带原包装与处方说明。'], sources: [jnto] },
      { id: 'safety-disaster', title: '地震或台风', steps: ['地震时先护头、远离玻璃与货架，晃动停后再移动。', '听酒店与站内广播，按指引避难；不盲目冲出建筑。', '台风天取消户外与离岛行程，轨道交通可能计划性停运。', '用 JNTO 热线或酒店确认交通恢复情况再出门。'], sources: [jma, jnto] },
      { id: 'safety-fraud', title: '遇到拉客或疑似诈骗', steps: ['不跟街头拉客进无标价店铺；已进店的先核对账单再付。', '刷卡前看金额与币种；账单异常先拍照留证再交涉。', '遇到自称警察查证件、要求转账的，先拨 110 核实。', '损失已发生时报警并保留凭证，联系发卡行止付。'], sources: [{ label: '警视厅', url: 'https://www.keishicho.metro.tokyo.lg.jp/' }] },
      { id: 'safety-transport', title: '错过末班或迷路', steps: ['先回最近车站闸口，看站内地图确认方向。', '错过末班用车站前正规出租车排队区，不上揽客车。', '手机没电就找便利店或车站工作人员求助。', '给酒店打电话报位置，很多酒店能帮忙叫车。'], sources: [{ label: '东京地铁', url: 'https://www.tokyometro.jp/' }] },
    ],
  },
  relatedGuides: [
    '京都城市页 → /places/japan/kyoto',
    '日本国家页 → /places/japan',
    '香港城市页 → /places/hong-kong',
  ],
  sourcesNote: [
    '街区、看点、交通与入境信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('tokyo').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}

export const kyoto: CityContent = {
  city: city('kyoto'),
  checkedAt: '2026-09-14',
  meta: [
    { label: '最佳季节', value: '春秋；樱花与红叶季人最多、住宿最贵，需早订。夏天湿热，冬天阴冷但人少。' },
    { label: '机场', value: '无本市机场；最近是关西国际（KIX），JR Haruka 特急直达京都站。' },
    { label: '建议停留', value: '3–4 晚。古都内容密度高但片区集中，不必排满每天。' },
    { label: '地区标签', value: '东亚' },
    { label: '气质', value: '寺院、町家、鸭川；早起比多排一个景点有用' },
  ],
  essentials: [
    {
      title: '机场 → 市区',
      body: '关西机场（KIX）到京都站最省事是 JR 特急 Haruka，直达约 80 分钟；机场巴士与南海电铁+换乘是备选。到京都站后再按住处位置选地铁、巴士或步行。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: 'JR 西日本', url: 'https://www.westjr.co.jp/' }],
    },
    {
      title: '建议住哪',
      body: '第一次来住京都站—乌丸／河原町一带最顺手：交通集中、晚上有饭吃。想安静选冈崎／左京区方向，但进出靠巴士。旺季（樱枫）提前两三个月订。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '3 晚排东山一天、北部或岚山一天、留白一天；4 晚加市区慢走。寺院神社不要一天连排超过三处——审美疲劳比体力先出问题。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '京都的内容密度高，但片区集中：东山一线（清水、祇园、八坂）、北部（金阁寺、龙安寺）、西部岚山、南部伏见。按片区分天，不按清单打卡。',
    '旺季的人潮集中在中午。慢旅行的答案不是早起打卡所有点，而是每天只选一两处，把清晨留给寺院、下午留给街区。',
    '京都站—河原町是生活与交通的骨架；鸭川是休息的骨架。走累了坐到河边，是这座城市自带的节奏。',
    '别把京都当「日本的古城主题公园」——它是活着的城市。町家咖啡馆、早市和澡堂，和寺院一样值得时间。',
  ],
  gettingThere: {
    intro: [
      '飞关西国际（KIX）：JR 特急 Haruka 直达京都站约 80 分钟是最省心的方案；机场巴士有京都线；南海电铁便宜但要换车，行李多不推荐。',
      '从东京／大阪方向来：新干线到京都站。市内靠地铁两线 + 巴士 + 步行；巴士有统一票价区间但高峰拥挤，能走就走。',
      'IC 卡（ICOCA／Suica 互通）地铁巴士通用。出租车站前与景区门口都有排队点，短途代步合理。',
    ],
    links: [
      { label: '关西机场', url: 'https://www.kansai-airport.or.jp/' },
      { label: '京都市官方旅游指南', url: 'https://kyoto.travel/' },
    ],
    verifyReminders: [
      'Haruka 当前票价、指定席规则与京都站停靠情况',
      '京都市巴士统一票价区间与一日券是否仍在售',
      '寺院特别公开（夜间拝観）的日程与购票方式',
      '旺季热门寺院是否改为预约制或限流',
    ],
  },
  neighborhoods: [
    {
      id: 'kyoto-station-karasuma',
      title: '京都站—乌丸',
      suited: '多数第一次来的人；要交通与吃饭都顺手。',
      image: cityImages['kyoto-station'],
      body: '以京都站为门、乌丸通为轴的市区。酒店选择多，夜间餐饮集中，往北接地铁乌丸线。把住处放这里，每天的出发和回来都省一段。',
      visit: {
        duration: '这一带是住处不是景点；逛街区另去河原町。',
        entry: '京都站（新干线、JR、地铁乌丸线交汇）。',
        walk: '京都站 → 乌丸通往北 → 四条河原町；全程平直好走。',
        return: '地铁乌丸线或步行回京都站方向。',
        stay: '首选居住区；核对酒店离京都站或乌丸线站点的实际步行距离。',
        source: { label: '京都市官方旅游指南', url: 'https://kyoto.travel/' },
      },
    },
    {
      id: 'higashiyama',
      title: '东山（清水—祇园）',
      suited: '想看寺院与老街区的人；请赶早。',
      image: cityImages['kyoto-higashiyama'],
      body: '清水寺、二年坂三年坂、八坂神社到祇园是一条经典步行线。早上八点前是另一座城；十点后把主街让给别人，拐进石塀小路一类背街。',
      visit: {
        duration: '半天；清晨版 2–3 小时。',
        entry: '巴士清水道或祇园四条站／京阪祇园四条站。',
        walk: '清水寺 → 二年坂・三年坂 → 八坂神社 → 祇园；全程下坡为主。',
        return: '祇园四条站返回；累了从八坂神社前直接打车。',
        stay: '不建议住景区内（早晚安静但出入不便）；住河原町步行可达。',
        source: { label: '京都市官方旅游指南', url: 'https://kyoto.travel/' },
      },
    },
    {
      id: 'arashiyama',
      title: '岚山',
      suited: '留一整天给竹林、寺院与河边的人。',
      image: cityImages['kyoto-arashiyama'],
      body: '竹林小径清晨最静；渡月桥一带中午拥挤。把岚山当一整天：早到走竹林与寺院，午后河边坐下，不回市区赶第二场。',
      visit: {
        duration: '大半天到一天。',
        entry: 'JR 嵯峨岚山站／阪急岚山站／京福电铁岚山站，按住处选线。',
        walk: '竹林小径 → 天龙寺或常寂光寺选一 → 渡月桥河边。',
        return: '按来路回；傍晚河边风大，带件外层。',
        stay: '住市区，岚山当一天外出行程。',
        source: { label: '京都市官方旅游指南', url: 'https://kyoto.travel/' },
      },
    },
    {
      id: 'kita-ginkakuji',
      title: '北部（金阁寺—银阁寺）',
      suited: '想看名寺院、能接受巴士移动的人。',
      image: cityImages['kyoto-kita'],
      body: '金阁寺与银阁寺分居北西与北东，巴士连接但别硬塞同一天——各配一处安静寺院（龙安寺／哲学之道）比两处打卡更像京都。',
      visit: {
        duration: '每处 1–1.5 小时 + 巴士时间。',
        entry: '巴士为主；金阁寺道／银阁寺道站下车。',
        walk: '金阁寺配龙安寺（相邻）；银阁寺配哲学之道散步。',
        return: '巴士回市区；高峰巴士排队，错峰走。',
        stay: '住市区；这一带不作居住区。',
        source: { label: '京都市官方旅游指南', url: 'https://kyoto.travel/' },
      },
    },
    {
      id: 'okazaki',
      title: '冈崎与左京',
      suited: '多住几晚、喜欢馆与咖啡馆的人。',
      image: cityImages['kyoto-okazaki'],
      body: '冈崎集中了近代美术馆群与平安神宫的大鸟居；左京区有出町柳、下鸭神社方向的生活街区。节奏比东山慢，适合第二次来或长住。',
      visit: {
        duration: '半天到一天。',
        entry: '地铁东西线东山站／巴士冈崎一带。',
        walk: '平安神宫 → 美术馆群选一 → 鸭川三角洲方向。',
        return: '地铁或沿鸭川走回市区。',
        stay: '想安静可住这里；进出靠巴士与地铁东西线。',
        source: { label: '京都市官方旅游指南', url: 'https://kyoto.travel/' },
      },
    },
  ],
  stay: {
    checkedAt: '2026-09-14',
    intro:
      '京都先定「枢纽还是散步圈」：住京都站每天坐车进出，住河原町则把东山散步与晚饭圈放在脚下。酒店同样多按人头计价，订时如实填人数。',
    budgetNote:
      '以 ¥700–800/晚为上限：在京都够用但不宽裕——京都站—乌丸一带平日可住中档；樱花季（3 月底–4 月中）与红叶季（11 月中–12 月初）全城上浮三成以上，旺季要么早订可取消，要么按 ¥1100 以上做预算。',
    anchors: [
      { title: '两条轨道定方向', body: '乌丸线（京都站—四条北上）与东西线（二条—乌丸御池—东山）；河原町另靠阪急与京阪。住处离任一站点步行十分钟内。' },
      { title: '枢纽型还是散步圈', body: '京都站进出城最顺但站外吃饭圈弱；四条河原町—祇园口把晚饭与散步放脚下，代价是每天进出景区更挤。' },
      { title: '町屋与老楼先看硬件', body: '町屋旅馆和老建筑多楼梯、隔音一般；带箱子或老人优先看电梯与楼层。' },
    ],
    areas: [
      {
        id: 'kyoto-station-stay',
        title: '京都站 – 乌丸',
        suitsIf: '第一次来、以京都为基地每天外出的；晚到或赶早班车的人。',
        budgetFeel: '平日 ¥600–900 有中档商务酒店；旺季上浮明显。',
        band: { low: 450, high: 950 },
        transit: '新干线＋JR＋地铁乌丸线＋巴士总站全部在站内；乌丸线北上约十分钟到四条。',
        food: '站内拉面小路、伊势丹食街够用；站外步行圈深夜店少。',
        tradeoff: '每天去景点先坐车 15–25 分钟；站周边城市感弱。',
        neighborhoodIds: ['kyoto-station-karasuma'],
      },
      {
        id: 'kawaramachi-gion-stay',
        title: '河原町 – 祇园口',
        suitsIf: '把重心放在东山散步与晚饭圈的人。',
        budgetFeel: '这档预算处于下限；町屋旅馆与鸭川侧房间普遍超四位数。',
        band: { low: 550, high: 1600 },
        transit: '阪急京都河原町＋京阪祇园四条双终点；去京都站需巴士或阪急换乘。',
        food: '锦市场、先斗町、祇园晚饭圈步行内——吃的密度全城最高。',
        tradeoff: '周末与花季晚上拥挤；早上去景区比住京都站慢一拍。',
        skipIf: '按寺庙开门时间早出晚归、晚饭从简——住京都站更顺。',
        neighborhoodIds: ['higashiyama'],
      },
      {
        id: 'okazaki-stay',
        title: '冈崎 – 南禅寺外缘',
        suitsIf: '第二次来、想住安静的人；长住型。',
        budgetFeel: '这档预算可住到不错的中档；房源少，旺季先于市区订完。',
        band: { low: 730, high: 1450 },
        transit: '地铁东西线东山站；到京都站约 20 分钟。',
        food: '南禅寺参道有几家汤豆腐名店；日常吃饭靠自行车活动半径。',
        tradeoff: '没有商圈与夜生活；进出靠东西线或巴士。',
        neighborhoodIds: ['okazaki'],
      },
    ],
  },
  dayTrips: [
    { direction: '宇治', how: 'JR 奈良线约 20–30 分钟', worth: '平等院与茶店老街，半天够；茶店当下午茶，不当午餐。' },
    { direction: '奈良', how: '近铁或 JR 约 45–60 分钟', worth: '东大寺与鹿园值得一天；与宇治可以同线但不推荐同日塞两处。' },
    { direction: '贵船・鞍马', how: '睿山电铁约 30 分钟起', worth: '夏季川床与山地寺院；雨季与冬季开放情况先查官网。' },
  ],
  dayTripNote: '宇治半天、奈良一天、贵船看季节；一班只挑一个方向，别同日塞两处。',
  eatIntro:
    '京都的吃分两类：町家里的慢餐（汤豆腐、精进料理、咖啡馆）和市场的快吃（锦市场、站前）。把「坐下来」留给前者，后者当散步补给。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'soba', title: '荞麦面与老铺',
      intro: '京都的老铺荞麦面是坐下来的版本：不靠翻台，一碗面配小店空间。看店外暖帘与木牌点单。',
      restaurants: [
        {
          id: 'owariya', name: '本家尾张屋', nameEn: 'Honke Owariya', neighborhood: '寺町通／锦市场旁',
          location: { address: '京都市中京区車屋町通二条下ル', areaId: 'kyoto-station-karasuma', connection: '地铁乌丸御池站步行约 5 分钟；近锦市场西口', source: { label: '官网', url: 'https://www.honke-owariya.co.jp/' } },
          order: ['宝来そば（五层荞麦盒）', '天妇罗荞麦面'],
          whyLinger: '1465 年创业的荞麦面老铺，建筑本身就是町家遗产。宝来そば是把五种配料分成五层的招牌吃法。',
          practical: '本店与分店多处；饭点等位常见。以官网店址与营业时间为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.honke-owariya.co.jp/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=本家尾張屋+京都' }],
        },
      ],
    },
    {
      id: 'tofu', title: '汤豆腐与精进料理',
      intro: '南禅寺方向的汤豆腐是京都「半餐半体验」的代表：一锅昆布水煮豆腐配几个小碟。价格偏高，安排一次就够。',
      restaurants: [
        {
          id: 'junsei', name: '南禅寺顺正', nameEn: 'Junsei', neighborhood: '南禅寺',
          location: { address: '京都市左京区南禅寺門前', connection: '地铁东西线蹴上站步行约 10 分钟；南禅寺山门外', source: { label: '官网', url: 'https://www.to-fu.co.jp/' } },
          order: ['汤豆腐套餐（湯豆腐会席）', '追加豆腐皮与炸豆腐'],
          whyLinger: '南禅寺山门的汤豆腐名店——寺院旁的庭院里吃一锅白汤豆腐，是京都式的慢餐。庭院可看。',
          practical: '旺季建议预约；套餐制按人数点。以官网为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.to-fu.co.jp/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=南禅寺順正' }],
        },
        {
          id: 'okutan', name: '奥丹', nameEn: 'Okutan', neighborhood: '南禅寺',
          location: { address: '京都市左京区南禅寺福地町', connection: '南禅寺山门旁，与顺正同片区', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=奥丹+南禅寺' } },
          order: ['汤豆腐套餐'],
          whyLinger: '与顺正并称的南禅寺汤豆腐老铺，更老派更小——炭火小锅与庭院席位。两家选一家即可。',
          practical: '店小席位有限，旺季建议预约；现金与卡情况以现场为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=奥丹+南禅寺' }],
        },
      ],
    },
    {
      id: 'matcha', title: '抹茶与和菓子',
      intro: '茶寮的一碗抹茶配当季和菓子是京都的下午茶形态。上午走寺、下午坐茶寮是最顺的组合。',
      restaurants: [
        {
          id: 'nakamura-tokichi', name: '中村藤吉', nameEn: 'Nakamura Tokichi', neighborhood: '京都站／宇治本店',
          location: { address: 'JR 京都站内（以官网店址为准）；本店在宇治', connection: '京都站店在站内，宇治本店距 JR 宇治站步行可达', source: { label: '官网', url: 'https://www.tokichi.jp/' } },
          order: ['抹茶圣代或生茶ゼリイ', '抹茶荞麦／茶渍饭（午间）'],
          whyLinger: '1854 年创业的宇治茶老铺。京都站店省去专程跑宇治——等车时吃一顿抹茶刚好。',
          practical: '京都站店等位常见；本店在宇治，若排宇治行程可在本店吃。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.tokichi.jp/' }],
        },
        {
          id: 'tsujiri', name: '祇园辻利', nameEn: 'Tsujiri', neighborhood: '祇园四条',
          location: { address: '京都市東山区四条通（祇园本店）', areaId: 'higashiyama', connection: '祇园四条站步行约 3 分钟', source: { label: '官网', url: 'https://www.tsujiri.com/' } },
          order: ['抹茶芭菲（都路里パフェ）', '抹茶单品与和菓子'],
          whyLinger: '祇园路口的抹茶老店，本店楼上茶寮的「都路里」芭菲是招牌。祇园散步的收尾点。',
          practical: '本店茶寮等位常见；伴手礼在一楼。以官网为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.tsujiri.com/' }],
        },
      ],
    },
    {
      id: 'cafe', title: '喫茶与町家咖啡',
      intro: '老屋改建的咖啡馆与昭和喫茶店是京都的休息方式——走累了找一家坐下，比便利店门口站着强。',
      restaurants: [
        {
          id: 'inoda-coffee', name: 'Inoda Coffee', nameEn: 'イノダコーヒ', neighborhood: '三条通',
          location: { address: '京都市中京区三条通（本店）', connection: '地铁乌丸御池站步行约 5 分钟；分店多处', source: { label: '官网', url: 'https://www.inoda-coffee.co.jp/' } },
          order: ['アラビアの真珠（招牌深焙）', '三明治或蛋糕早餐'],
          whyLinger: '1940 年创业的京都喫茶老店——本店的本馆是银行职员与作家们用了八十年的早餐厅。',
          practical: '早餐时段最值；分店多处，本店最有气氛。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.inoda-coffee.co.jp/' }],
        },
        {
          id: 'smart-coffee', name: 'Smart Coffee', nameEn: 'スマート珈琲店', neighborhood: '寺町通',
          location: { address: '京都市中京区寺町通三条上ル', connection: '寺町通商店街内；近三条', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=スマート珈琲店+京都' } },
          order: ['法式吐司（フレンチトースト）', '咖啡'],
          whyLinger: '1932 年创业的喫茶店，法式吐司与玉子烧三明治是招牌——比 Inoda 更小更旧，更像时间胶囊。',
          practical: '店小等位常见；现金为主。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=スマート珈琲店+京都' }],
        },
      ],
    },
    {
      id: 'nishiki', title: '锦市场与商店街',
      intro: '锦市场适合边走边吃小份：玉子烧、豆乳甜甜圈、漬物——当上午散步的一部分，别当正餐。',
      restaurants: [
        {
          id: 'miki-keiran', name: '三木鸡卵', nameEn: 'Miki Keiran', neighborhood: '锦市场',
          location: { address: '京都市中京区錦小路通', connection: '锦市场内中段；阪急河原町站步行约 5 分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=三木鶏卵+錦市場' } },
          order: ['玉子烧（一串）', '出汁卷'],
          whyLinger: '市场里的玉子烧老铺，一串厚玉子是锦市场的定番小吃。',
          practical: '摊位现做；现金为主，一串即走。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=三木鶏卵+錦市場' }],
        },
        {
          id: 'konna-monja', name: 'Konna Monja', nameEn: 'こんなもんじゃ', neighborhood: '锦市场',
          location: { address: '京都市中京区錦小路通', connection: '锦市场内；豆乳甜甜圈摊', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=こんなもんじゃ+錦市場' } },
          order: ['豆乳甜甜圈（现炸）', '豆乳冰淇淋'],
          whyLinger: '锦市场最有名的边走边吃小摊——现炸豆乳甜甜圈一口一个。',
          practical: '现金小摊；排队买一串即走。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=こんなもんじゃ+錦市場' }],
        },
      ],
    },
  ],
  howToOrder: [
    '町家与茶寮多数安静入座，看当日菜单或套餐；不确定就问店员推荐。',
    '市场小吃现买现吃，窄街别堵路口。',
    '寺院周边的汤豆腐店多有套餐制，按人数点。',
    '咖啡馆不少收现金为主；备零钱。',
  ],
  avoid: [
    '别把清水寺—祇园主街上的「抹茶主题店」当成全部——背街与町家里的更好坐。',
    '旺季正午的东山一带餐饮店全在排队，把饭点错开或回河原町吃。',
    '锦市场不是正餐场所，边走边吃一圈就够，别饿着进去指望吃饱。',
  ],
  eatRhythm:
    '早餐在住处附近咖啡馆或便利店解决；上午走寺院，中午找町家或食堂；下午安排一次茶寮；晚上在河原町或住处附近吃家常菜。',
  allergies: [
    '京料理用出汁多（鲣鱼、昆布），鱼过敏逐店确认。',
    '精进料理基本全素但可能含麸质（面筋／麸）。',
    '和菓子常见豆沙、糯米；坚果与蛋奶需问。',
  ],
  guide: {
    city: '京都',
    checkedAt: '2026-09-14',
    scope: '以公共交通为主的首次京都行程；签证与入境按本人证件另核官方要求',
    intro: '京都的骨架很简单：京都站进城，巴士与地铁分天去不同片区。以下按 3–4 晚、住市区写。',
    topics: [
      japanDocuments,
      japanMobile('关西机场'),
      {
        id: 'payment',
        title: '支付与现金',
        summary: '寺院拝観料与小店以现金为主，再配 IC 卡。',
        stage: 'before',
        recommendation: '京都比东京更依赖现金：寺院拝観料、小店、部分巴士找零都要用。备足日元现金，IC 卡（ICOCA／Suica 互通）处理交通与便利店。',
        steps: [
          { title: '出发前确认银行卡境外功能', body: '开通境外刷卡与 ATM 取现；日本便利店 ATM 支持境外卡，作为补充。' },
          { title: '多备小额现金', body: '寺院拝観料多为现金小额；准备千円札与硬币，不把大额支付全压在刷卡上。' },
          { title: '拿一张 IC 卡', body: '关西发 ICOCA，与 Suica 互通；机场或车站可买，手机添加方式按官方指引。' },
        ],
        done: '现金够两天门票餐食、IC 卡可用、银行卡确认能取现。',
        fallback: '现金不够时找 7-11 等便利店 ATM；小店不收卡就换一家。',
        sources: [{ label: 'JR 西日本 ICOCA', url: 'https://www.westjr.co.jp/' }, jnto],
      },
      japanStay('京都站—河原町'),
      {
        id: 'arrival',
        title: '关西机场 → 京都',
        summary: 'Haruka 直达京都站最省心，行李多再看巴士。',
        stage: 'arrival',
        recommendation: '关西机场（KIX）落地：JR 特急 Haruka 直达京都站约 80 分钟是首选；机场巴士有京都线但受路况影响；南海电铁便宜但需换车，不适合大件行李。',
        steps: [
          { title: '落地前先定进城方案', body: 'Haruka 在机场二楼 JR 闸口旁车站；核对当前票价与指定席规则，旺季现场买票可能等位，可提前网上订。' },
          { title: '先连网再离开到达厅', body: '确认酒店地址与京都站到住处的衔接（地铁乌丸线／巴士／出租车）；需要 IC 卡可在机场一次办好。' },
          { title: '到京都站后分流出站', body: '京都站很大：八条口与乌丸口方向不同，先找住处所在侧再出站。' },
          { title: '最后一段别硬走', body: '行李多直接出租车到酒店；京都站前出租车排队规范，短途价格合理。' },
        ],
        done: '人与行李到酒店，回程知道去京都站坐 Haruka。',
        fallback: 'Haruka 停运或售罄时改机场巴士京都线；深夜到达先住机场或大阪，不硬赶。',
        sources: [{ label: '关西机场交通', url: 'https://www.kansai-airport.or.jp/' }, { label: 'JR 西日本', url: 'https://www.westjr.co.jp/' }],
      },
      {
        id: 'transit',
        title: '市内交通',
        summary: '地铁两线加巴士，能走的片区尽量走。',
        stage: 'during',
        recommendation: '京都市内是地铁乌丸线・东西线 + 市巴士 + 步行。巴士有统一票价区间但高峰极挤；住处若在地铁沿线，优先地铁，巴士留给东山、北部方向。',
        steps: [
          { title: '按片区选交通', body: '东山方向巴士或京阪；北部金阁寺方向巴士；岚山可选 JR／阪急／京福；市区南北走地铁乌丸线。' },
          { title: '巴士从后门上前门下', body: '下车时付款或刷卡；高峰排队上车会等好几班，错峰或改地铁＋步行。' },
          { title: '一日券先算再买的', body: '巴士／地铁一日券是否划算取决于当天坐几次，多数慢行程不划算。' },
          { title: '雨天改室内', body: '寺院雨天体验打折；备好馆（京都国立博物馆、漫画博物馆等）作雨天替换。' },
        ],
        done: '知道住处附近地铁站与巴士站，会用 IC 卡上下车。',
        fallback: '巴士挤不上时改地铁＋步行或出租车；景区门口出租车扬招点多。',
        sources: [{ label: '京都市交通局', url: 'https://www.city.kyoto.lg.jp/kotsu/' }, { label: '京都市官方旅游指南', url: 'https://kyoto.travel/' }],
      },
    ],
    checklist: [
      { id: 'c-docs', text: '签证要求已按本人证件核实；Visit Japan Web 已填或确认可现场填', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效期覆盖行程；返程订单与酒店信息离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '上网方案已选定，备用方案明确', topic: '上网与手机' },
      { id: 'c-cash', text: '备足日元现金（寺院拝観料与小店以现金为主）', topic: '支付与现金' },
      { id: 'c-ic', text: 'ICOCA／Suica 的购买或添加方式已确认', topic: '支付与现金' },
      { id: 'c-stay', text: '酒店总价、人数规则、晚到方案已书面确认', topic: '住宿与入住' },
      { id: 'c-haruka', text: 'Haruka 或机场巴士的当前票价与乘车方法已截图', topic: '关西机场 → 京都' },
      { id: 'c-bus', text: '已查住处附近的地铁站与巴士站位置', topic: '市内交通' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：东山一天，北边一天',
      note: '住京都站—河原町一带。寺院一天不超过三处，清晨留给最想看的那一处。',
      days: [
        { day: '第一天', body: '抵达京都站、入住，河原町一带吃晚饭，早睡。', time: '按落地时间安排', start: 'KIX／京都站 → 酒店', return: '河原町附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '清晨清水寺 → 二年坂・三年坂 → 八坂神社 → 祇园；午后回市区休息或锦市场。', time: '早起，午后慢下来', start: '巴士／京阪 → 清水', return: '祇园四条返回', links: [{ label: '东山一带', href: '?tab=places#area-higashiyama' }] },
        { day: '第三天', body: '上午伏见稻荷（早到）或金阁寺选一，午后按返程交通收尾。', time: '上午一处、午后收尾', start: '住处 → 所选一处', return: '京都站 → 返程', links: [{ label: '北部一带', href: '?tab=places#area-kita-ginkakuji' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加岚山与留白',
      note: '在 3 晚骨架上加岚山一天、冈崎或市区慢走一天；留白补体力。',
      days: [
        { day: '第一天', body: '抵达入住，河原町吃晚饭早睡。', time: '按落地时间安排', start: 'KIX／京都站 → 酒店', return: '河原町附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '东山一天（清水—祇园线），清晨进清水寺。', time: '早起一天', start: '清水道', return: '祇园四条', links: [{ label: '东山一带', href: '?tab=places#area-higashiyama' }] },
        { day: '第三天', body: '岚山一天：竹林小径、天龙寺或常寂光寺、渡月桥河边。', time: '一整天', start: 'JR 嵯峨岚山方向', return: '按来路回市区', links: [{ label: '岚山', href: '?tab=places#area-arashiyama' }] },
        { day: '第四天', body: '北部选一处（金阁寺或银阁寺）＋ 相邻寺院或哲学之道；下午留白。', time: '半天外出、半天留白', start: '巴士往北部', return: '回市区', links: [{ label: '北部一带', href: '?tab=places#area-kita-ginkakuji' }] },
        { day: '第五天', body: '冈崎／出町柳方向慢走或锦市场早餐，按返程收尾。', time: '上午慢走、午后收尾', start: '冈崎方向', return: '京都站 → 返程', links: [{ label: '冈崎与左京', href: '?tab=places#area-okazaki' }] },
      ],
    },
  },
  safety: {
    city: '京都',
    checkedAt: '2026-09-14',
    emergencyNote: '京都治安好，主要准备灾害与旺季人流。寺院石阶与山地步道按体力安排，雨天防滑。',
    contacts: [
      { name: '报警', number: '110', dial: '110', use: '盗窃、遗失、交通事故', source: { label: '京都府警察', url: 'https://www.pref.kyoto.jp/fukei/' }, urgent: true },
      { name: '急救 / 火灾', number: '119', dial: '119', use: '急救车与火警', source: { label: '京都市消防局', url: 'https://www.city.kyoto.lg.jp/shobo/' }, urgent: true },
      { name: 'JNTO 游客热线', number: '050-3816-2787', dial: '+815038162787', use: '24 小时多语种旅游咨询与紧急协助', source: jnto },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '护照、签证材料与订单截图离线保存。',
      '保存酒店日文地址；京都站分八条口与乌丸口，认清住处所在侧。',
      '旺季（樱枫）寺院人多，贵重物品贴身放。',
      '境外医疗保险与救援电话另存。',
      '灾害速报应用装好；台风季关注气象厅预警。',
      '记熟 110 / 119；纯流量卡不能打电话，想好替代求助。',
    ],
    alerts: japanAlerts('京都'),
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['到最近交番或警署报失拿证明。', '联系中国驻大阪总领馆（京都领区多归大阪）补办旅行证件。', '保留报失证明用于保险理赔。', '确认新证件出入境可用再改签。'], sources: [consular, { label: '中国驻大阪总领馆', url: 'http://osaka.china-consulate.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 119。', '非紧急请酒店推荐会英语的诊所。', '保留收据与诊断证明走保险。', '寺院山地扭伤先休息，不硬走完全程。'], sources: [jnto] },
      { id: 'safety-disaster', title: '地震、台风或暴雨', steps: ['京都盆地周边有山地，暴雨时避开河川与山区步道（贵船、鞍马方向）。', '台风天巴士与电车可能计划停运，按酒店指引留在室内。', '地震后听站内与馆内广播，不盲目冲楼梯。'], sources: [jma, jnto] },
      { id: 'safety-fraud', title: '疑似诈骗或纠纷', steps: ['寺庙外「算命」「兜售护身符」的生人搭讪不理。', '账单争议先拍照留证再交涉。', '自称执法人员要求转账的一律拨 110 核实。'], sources: [jnto] },
      { id: 'safety-transport', title: '巴士坐过站或迷路', steps: ['京都巴士按站名下车，坐过站到下一站下再导航。', '迷路时找便利店或派出所（交番）问路。', '夜间景区周边出租车少，回大路上再叫车。'], sources: [{ label: '京都市交通局', url: 'https://www.city.kyoto.lg.jp/kotsu/' }] },
    ],
  },
  relatedGuides: [
    '东京城市页 → /places/japan/tokyo',
    '日本国家页 → /places/japan',
    '香港城市页 → /places/hong-kong',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('kyoto').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}


export const osaka: CityContent = {
  city: city('osaka'),
  checkedAt: '2026-09-15',
  meta: [
    { label: '最佳季节', value: '春秋为主；夏湿热、冬干冷。比东京更热一点。' },
    { label: '机场', value: '关西（KIX）国际线为主，南海电铁或利木津巴士进城；伊丹（ITM）多国内线，离市区近。' },
    { label: '建议停留', value: '2–4 晚。2 晚走南（难波—新世界）加城公园；4 晚加中之岛与一顿认真吃的正餐。' },
    { label: '地区标签', value: '东亚 · 关西' },
    { label: '气质', value: '吃比逛重要，下町与商场之间' },
  ],
  essentials: [
    {
      title: '机场 → 市区',
      body: '关西机场进城两条主线：南海电铁直达难波（约 45 分钟）或 JR 关空快速到大阪站方向；住梅田选 JR，住难波选南海。深夜有利木津巴士。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: '关西机场', url: 'https://www.kansai-airport.or.jp/' }],
    },
    {
      title: '建议住哪',
      body: '第一次来住难波—心斋桥（道顿堀、黑门市场步行半径，南海直达机场）或梅田（JR 枢纽，去京都神户方便）。全程一处，不为换片区换酒店。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '2 晚排南市区一天、大阪城加中之岛一天；4 晚加新世界半天与留白。大阪的重点在餐桌，别把行程排满。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '大阪分北（キタ・梅田）与南（ミナミ・难波）两座市中心，御堂筋与地铁把它们串成一条轴。慢旅行的做法：住一侧，每天只走一段轴。',
    '南边的密度最高：道顿堀的霓虹与蟹道乐招牌是游客面，法善寺横丁与黑门市场是更老的一层。新世界通天阁一带是下町，旧、乱、便宜，半天够。',
    '大阪城在东侧，公园大、人多，早上去；中之岛在西边，是这座城最安静的一段水岸，适合下午。',
    '大阪人自认「吃到倒」——粉物、乌冬、市场海鲜、咖啡馆轮换着吃，比排队追店更接近这座城。',
  ],
  gettingThere: {
    intro: [
      '关西机场（KIX）：南海电铁特急 rapid 到难波约 45 分钟；JR 关空快速到大阪站（梅田）约 70 分钟。利木津巴士按片区分线。',
      '伊丹机场（ITM）多国内线，离市区近，单轨电车接地铁或机场巴士约 30 分钟到梅田。',
      '市内地铁为主，御堂筋线是主轴；IC 卡（ICOCA／Suica 互通）直接刷。难波站有南海、近铁、地铁、JR 多套系统，换乘看清运营公司。',
    ],
    links: [
      { label: '关西机场交通', url: 'https://www.kansai-airport.or.jp/' },
      { label: '大阪观光局', url: 'https://osaka-info.com/' },
    ],
    verifyReminders: [
      '南海 rapid 与 JR 关空快速当前票价与班次',
      '难波各运营公司站厅的相对位置（南海难波 vs 地铁难波）',
      '利木津巴士深夜线当前停靠站',
      '地铁末班时间（御堂筋线约午夜前后）',
    ],
  },
  neighborhoods: [
    {
      id: 'namba-dotonbori',
      title: '难波与道顿堀',
      suited: '第一次来、想住在吃与散步半径里的人。',
      image: cityImages['osaka-namba'],
      body: '道顿堀运河边的霓虹是明信片面；拐进法善寺横丁就是石板路与小馆。心斋桥筋是商店街，走一段就够。',
      visit: {
        duration: '半天加一晚；夜景比白天好。',
        entry: '地铁御堂筋线难波站或心斋桥站。',
        walk: '黑门市场 → 法善寺横丁 → 道顿堀运河 → 心斋桥筋一段。',
        return: '难波站返回；夜里人挤，看紧随身物。',
        stay: '首选居住区；南海难波直达机场，拖着箱子最顺。',
        source: { label: 'Osaka Info', url: 'https://osaka-info.com/' },
      },
    },
    {
      id: 'shinsekai-tennoji',
      title: '新世界与天王寺',
      suited: '想看老大阪下町、吃便宜串炸的人。',
      image: cityImages['osaka-shinsekai'],
      body: '通天阁周边是昭和下町：串炸店、将棋馆、复古招牌。脏与旧是它的一部分，半天走走停停刚好；天王寺动物园与四天王寺在同一片区。',
      visit: {
        duration: '半天。',
        entry: '地铁堺筋线惠美须町站或动物园前站。',
        walk: '惠美须町站 → 通天阁本通 → ジャンジャン横丁 → 四天王寺方向。',
        return: '天王寺站或动物园前站返回。',
        stay: '可当住宿预算选项；夜间人流杂，选靠地铁站的楼。',
        source: { label: 'Osaka Info', url: 'https://osaka-info.com/' },
      },
    },
    {
      id: 'osaka-castle-park',
      title: '大阪城与森之宫',
      suited: '想要大片公园与一段历史的人。',
      image: cityImages['osaka-castle'],
      body: '大阪城天守阁是重建建筑，看点在石垣与整座公园。护城河一圈适合晨走，森之宫一侧有便利店与小餐馆。',
      visit: {
        duration: '半天；天守阁登不登看兴致。',
        entry: 'JR 大阪环状线大阪城公园站，或地铁谷町四丁目站。',
        walk: '谷町四丁目入口 → 护城河 → 天守阁 → 森之宫出口。',
        return: '森之宫站或大阪城公园站返回。',
        stay: '不建议住公园旁（晚上没饭吃）；回难波或梅田住。',
        source: { label: 'Osaka Info', url: 'https://osaka-info.com/' },
      },
    },
    {
      id: 'umeda-kita',
      title: '梅田（北）',
      suited: '要跑京都、神户方向联游的人。',
      image: cityImages['osaka-umeda'],
      body: 'JR 大阪站与阪急、阪神、地铁挤在同一处，地下街极复杂。商场多，蓝天大厦空中庭园在河畔一侧。',
      visit: {
        duration: '半天；主要是交通与商场。',
        entry: 'JR 大阪站或地铁梅田站。',
        walk: '大阪站 → 茶屋町一带 → 蓝天大厦方向。',
        return: '原站返回；地下街先上地面再导航。',
        stay: '交通枢纽型住处；比难波安静，去机场与京都都顺。',
        source: { label: 'Osaka Info', url: 'https://osaka-info.com/' },
      },
    },
    {
      id: 'nakanoshima',
      title: '中之岛',
      suited: '想在美术馆与水岸之间过半天的人。',
      image: cityImages['osaka-nakanoshima'],
      body: '两条河夹出的岛：中之岛公园、中央公会堂、国立国际美术馆都在步行半径。是大阪最不像大阪的一段——安静、慢。',
      visit: {
        duration: '半天。',
        entry: '地铁／京阪难波桥站或淀屋桥站。',
        walk: '淀屋桥 → 中央公会堂 → 美术馆 → 沿河边往西走。',
        return: '渡边桥站或肥后桥站返回。',
        stay: '不作居住建议；当下午留白。',
        source: { label: 'Osaka Info', url: 'https://osaka-info.com/' },
      },
    },
  ],
  stay: {
    checkedAt: '2026-09-14',
    intro:
      '大阪先定「住南还是住北」：难波吃和玩在脚下、南海直达机场；梅田是铁路枢纽、去京都神户顺。新世界是预算兜底。',
    budgetNote:
      '以 ¥700–800/晚为上限：在大阪偏宽裕——难波、梅田的中档酒店平日 ¥550–900 常见；周末与樱花／红叶季上浮，新世界一带始终便宜一档。',
    anchors: [
      { title: '贴御堂筋线选', body: '梅田—难波—天王寺一条红线串完八成移动，住处贴着这条线的站选。' },
      { title: '按进出方式选南或北', body: '南海难波直达关西机场，拖箱子优先难波；乘 JR 跑京都、神户、奈良则梅田更顺。' },
      { title: '新世界要挑楼', body: '便宜但夜间人流杂，只选紧贴地铁站出口的楼，巷子深处的不考虑。' },
    ],
    areas: [
      {
        id: 'namba-stay',
        title: '难波 – 道顿堀',
        suitsIf: '第一次来、以吃为主轴的人；拖箱子直达机场的人。',
        budgetFeel: '这档预算可住到中档；离道顿堀越近周末越贵。',
        band: { low: 450, high: 910 },
        transit: '南海电铁直达关空；地铁御堂筋、千日前、四桥三线交汇。',
        food: '道顿堀、法善寺、黑门市场全部步行内。',
        tradeoff: '晚上闹、游客密度最高；主干道上的房间注意隔音。',
        neighborhoodIds: ['namba-dotonbori'],
      },
      {
        id: 'umeda-stay',
        title: '梅田（北）',
        suitsIf: '以大阪为基地跑京都、神户、奈良的人。',
        budgetFeel: '这档预算处于中位；JR 站前老牌酒店偏上档。',
        band: { low: 550, high: 1140 },
        transit: 'JR 大阪站＋阪急阪神＋地铁御堂筋梅田站；去京都新快速约 30 分钟。',
        food: '站屋食街与地下街密集；地道小店密度低于难波。',
        tradeoff: '地下街容易迷路；街区商务感强、晚上安静得快。',
        neighborhoodIds: ['umeda-kita'],
      },
      {
        id: 'shinsekai-tennoji-stay',
        title: '新世界 – 天王寺',
        suitsIf: '预算优先、对街区环境不敏感的人。',
        budgetFeel: '这档预算在这里明显超配，¥400–550 就有正经中档。',
        band: { low: 320, high: 640 },
        transit: 'JR 天王寺站＋地铁御堂筋动物园前；去关空乘 JR 约 50 分钟。',
        food: '串炸横丁与天王寺地下食街；店铺收摊早。',
        tradeoff: '夜间人流杂、部分街区氛围粗粝；离难波两站地铁。',
        skipIf: '对夜间街区氛围敏感，或带家人想住得省心。',
        neighborhoodIds: ['shinsekai-tennoji'],
      },
    ],
  },
  dayTrips: [
    { direction: '京都', how: 'JR 新快速或阪急约 30–45 分钟', worth: '大阪当关西基地，京都当天来回可行；但京都值得单住，别两头赶。' },
    { direction: '奈良', how: '近铁约 40 分钟到近铁奈良', worth: '东大寺与鹿公园半天到一天；早去避团客。' },
    { direction: '神户', how: 'JR 新快速约 25 分钟', worth: '港町散步与北野异人馆；半天轻松。' },
  ],
  dayTripNote: '关西三城都近：大阪当基地最顺，京都奈良神户当日往返，不排成同一天。',
  eatIntro:
    '大阪的底色是粉物：大阪烧、章鱼烧、串炸。正餐选一处认真吃（乌冬老铺或市场海鲜），法善寺横丁的甜品店与心斋桥的咖啡馆负责坐住的时段。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'konamono', title: '粉物（大阪烧·章鱼烧·串炸）',
      intro: '面粉做的热食是大阪的方言。大阪烧自己煎或店员煎，章鱼烧趁热，串炸「酱汁只能蘸一次」是基本规则。',
      restaurants: [
        {
          id: 'mizuno', name: '美津の', nameEn: 'Mizuno', neighborhood: '道顿堀',
          location: { address: '大阪市中央区道顿堀1-4-15', areaId: 'namba-dotonbori', connection: '地铁难波站14号口步行约5分钟', source: { label: '官网', url: 'https://mizuno-osaka.com/' } },
          order: ['山芋烧（山药泥大阪烧）', '综合大阪烧'],
          whyLinger: '道顿堀最有名的大阪烧老铺之一——山芋泥版本轻、蓬松，是第一次吃大阪烧的稳妥起点。',
          practical: '常年排队；店门口看板看当前等候。午市比晚市松。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '官网', url: 'https://mizuno-osaka.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=美津の+道頓堀' }],
          queueNote: '饭点排 30–60 分钟常见；开门前到最稳。',
        },
        {
          id: 'kougaryu', name: '甲贺流', nameEn: 'Kougaryu', neighborhood: '心斋桥美国村',
          location: { address: '大阪市中央区西心斋桥2-18-4', areaId: 'namba-dotonbori', connection: '心斋桥筋美国村一侧', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=甲賀流+心斎橋' } },
          order: ['章鱼烧（たこ焼き）', '葱蛋黄酱口味'],
          whyLinger: '美国村口的章鱼烧老店——外脆内浆、章鱼大块，站边吃是道顿堀散步的固定一站。',
          practical: '即点即走；烫，先放凉一两分钟。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=甲賀流+心斎橋' }],
        },
        {
          id: 'daruma-shinsekai', name: '串炸达摩 新世界总本店', nameEn: 'Kushikatsu Daruma Shinsekai', neighborhood: '新世界',
          location: { address: '大阪市浪速区惠美须东2-3-9', areaId: 'shinsekai-tennoji', connection: '通天阁本通旁；地铁惠美须町站步行约3分钟', source: { label: '官网', url: 'https://www.kushikatu-daruma.com/' } },
          order: ['串炸组合（牛·虾·笋·蛋）', 'どて烧（味噌炖牛筋）'],
          whyLinger: '「酱汁禁蘸两次」规则的发源地——坐在通天阁脚下吃现炸串，是新世界散步的正餐选项。',
          practical: '炸篮直接来，酱汁缸共用、只蘸一次；排队按门口看板。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '官网', url: 'https://www.kushikatu-daruma.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=串かつだるま+新世界' }],
        },
      ],
    },
    {
      id: 'udon', title: '乌冬与老铺定食',
      intro: '大阪乌冬汤头清淡带昆布香，和东京的浓口酱油不同。粉物吃腻后的解法是坐进老铺点一碗。',
      restaurants: [
        {
          id: 'imai', name: '道顿堀今井', nameEn: 'Dotonbori Imai', neighborhood: '道顿堀',
          location: { address: '大阪市中央区道顿堀1-7-22', areaId: 'namba-dotonbori', connection: '法善寺横丁旁；地铁难波站步行约5分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=道頓堀今井' } },
          order: ['きつね乌冬（油豆腐）', 'うどんすき（锅烧乌冬，冬季）'],
          whyLinger: '道顿堀的乌冬老铺——被霓虹包围却安静，汤头是教科书的关西风。',
          practical: '店面低调容易走过；定休与时间以现场为准。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=道頓堀今井' }],
        },
      ],
    },
    {
      id: 'market', title: '黑门市场',
      intro: '黑门市场是大阪的厨房：海鲜、烤扇贝、和牛串边走边吃。近年游客化明显，早上去、挑老店。',
      restaurants: [
        {
          id: 'kuromon-sanpei', name: '黑门三平', nameEn: 'Kuromon Sanpei', neighborhood: '黑门市场',
          location: { address: '大阪市中央区日本桥1-22-25', areaId: 'namba-dotonbori', connection: '地铁日本桥站步行约5分钟进市场', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=黒門三平' } },
          order: ['生鱼片拼盘', '烤扇贝·蟹腿'],
          whyLinger: '市场里最大的鲜鱼店——自选现切现吃，站着或坐店内区，是黑门市场最扎实的一顿。',
          practical: '先结账取号牌再取餐；现金与卡均可。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=黒門三平' }],
        },
      ],
    },
    {
      id: 'cafe-sweets', title: '甜品与咖啡',
      intro: '法善寺横丁的红豆汤和心斋桥的精品咖啡，负责把下午的散步收住。',
      restaurants: [
        {
          id: 'meoto-zenzai', name: '夫妇善哉', nameEn: 'Meoto Zenzai', neighborhood: '法善寺横丁',
          location: { address: '大阪市中央区难波1-2-10 法善寺めおと处', areaId: 'namba-dotonbori', connection: '法善寺横丁内', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=夫婦善哉+法善寺' } },
          order: ['善哉（红豆汤配年糕）', '冰善哉（夏）'],
          whyLinger: '文学作品里走出来的甜品老铺——一人份的善哉分成两小盏，石板路与苔藓就在店外。',
          practical: '分量小，当散步收尾而非正餐；现金为主。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=夫婦善哉+法善寺' }],
        },
        {
          id: 'lilo-coffee', name: 'Lilo Coffee Roasters', nameEn: 'Lilo Coffee Roasters', neighborhood: '心斋桥',
          location: { address: '大阪市中央区西心斋桥1-10-28', areaId: 'namba-dotonbori', connection: '心斋桥筋西侧巷内', source: { label: '官网', url: 'https://lilocoffee.com/' } },
          order: ['手冲单品', '埃塞或亚洲产豆'],
          whyLinger: '大阪精品咖啡的代表店——亚洲榜上常客，吧台小、豆子选择多，是心斋桥逛街间隙的坐住点。',
          practical: '店内席位少，高峰外带更顺。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '官网', url: 'https://lilocoffee.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Lilo+Coffee+Roasters' }],
        },
      ],
    },
  ],
  howToOrder: [
    '大阪烧店先选口味再追加配料；铁板自己煎的店按店员示范来。',
    '串炸酱汁缸共用，一串只能蘸一次——标志写得到处都是。',
    '市场里先问能不能边走边吃，很多店要求店内或店口吃完。',
    '一人食在粉物店、立食乌冬最顺；老铺乌冬一份一碗刚好。',
  ],
  avoid: [
    '道顿堀主街的拉客店与「游客套餐」偏贵；巷子里同样的东西便宜。',
    '新世界个别店卫生观感一般，按自己接受度挑。',
    '别把每一餐都排成名店排队——大阪的正确吃法是附近找同类。',
  ],
  eatRhythm:
    '早餐便利店或市场；午餐粉物或乌冬；下午咖啡馆或甜品收尾；晚上串炸或市场海鲜。一天最多排一家要排队的名店。',
  allergies: [
    '大阪烧与章鱼烧含蛋、小麦、海鲜出汁——忌甲壳类先确认面糊。',
    '串炸油与面衣共用，海鲜过敏注意交叉。',
    '乌冬汤底是昆布鲣鱼，纯素者需单点确认。',
  ],
  guide: {
    city: '大阪',
    checkedAt: '2026-09-15',
    scope: '以公共交通为主的首次大阪行程；签证与入境按本人证件另核官方要求',
    intro: '先把入境资格、网络、交通卡与住处安排好。以下按 2–4 晚、住难波或梅田写。',
    topics: [
      japanDocuments,
      japanMobile('关西／伊丹机场'),
      {
        id: 'payment', title: '支付与交通卡', summary: 'IC 卡全国互通，现金留给小店。',
        stage: 'before' as const,
        recommendation: '关西发 ICOCA，与 Suica 等全国互通，地铁私铁便利店都能用。大阪小店与市场现金仍常见，备小额纸币。',
        steps: [
          { title: '确认银行卡境外功能', body: '开通境外刷卡；多数商场与大店收卡，市场与老铺偏现金。' },
          { title: '落地办 IC 卡', body: '关西机场 JR／南海窗口或售票机可买 ICOCA；手机钱包绑定已有 IC 卡更省事。' },
          { title: '备小额现金', body: '1000 円纸币与硬币好用；市场摊位、神社老铺常见只收现金。' },
        ],
        done: 'IC 卡可用、银行卡确认能刷、备有小额现金。',
        fallback: 'IC 卡余额不足可在站内充值机现金补；卡刷不过用现金。',
        sources: [jnto],
      },
      japanStay('难波—心斋桥或梅田'),
      {
        id: 'arrival', title: '关西机场 → 酒店', summary: '住难波选南海，住梅田选 JR；深夜靠巴士。',
        stage: 'arrival' as const,
        recommendation: '住难波：南海电铁 rapid 直达约 45 分钟。住梅田：JR 关空快速到大阪站方向。深夜到达看利木津巴士当前班次或正规出租车。',
        choices: [
          { title: '南海电铁（难波方向）', body: 'rapid 特急到难波约 45 分钟；普通车更便宜站站停。南海难波站与地铁难波站不同栋，看清指示。' },
          { title: 'JR 关空快速（梅田方向）', body: '经天王寺到大阪站约 70 分钟；无指定席，持 IC 卡直接刷。' },
          { title: '利木津巴士', body: '按片区选线（难波、梅田、新阪急等）；深夜班次以官网当前为准。' },
        ],
        steps: [
          { title: '落地前存好整条路线', body: '交通方式、下车站、末班时间截图；用预计出关时间判断。' },
          { title: '到达厅一次办完小事', body: '买 IC 卡、确认上网、看酒店地址。' },
          { title: '按运营公司找站台', body: '南海与 JR 闸口分开；巴士按站台编号。' },
          { title: '难波站先上地面', body: '南海、地铁、近铁、JR 在此交汇，地下容易迷向，上地面再导航到酒店。' },
        ],
        done: '到酒店，知道返程在哪个公司站台上车。',
        fallback: '深夜到达用利木津或正规出租车；不坐揽客车。',
        sources: [{ label: '关西机场交通', url: 'https://www.kansai-airport.or.jp/' }],
      },
      {
        id: 'transit', title: '市内交通', summary: '地铁御堂筋是主轴，IC 卡一刷到底。',
        stage: 'during' as const,
        recommendation: '地铁覆盖主要片区；御堂筋线串梅田—心斋桥—难波—天王寺。难波、梅田站多家公司站厅相邻不相通，换乘看清运营公司。',
        steps: [
          { title: '记一条主轴', body: '御堂筋线（红线）解决八成移动；换乘站按公司找闸口。' },
          { title: '难波站防迷路', body: '南海难波、地铁难波、近铁／阪神难波、JR 难波是四个不同位置，出站前先确认公司名。' },
          { title: '末班约午夜', body: '各线末班不同；深夜出租车可用但贵，先查返程末班再出门。' },
          { title: 'JR 环状线去城公园', body: '大阪城公园站在环状线上；与地铁站不共站，按公司换乘。' },
        ],
        done: '会用 IC 卡坐地铁私铁、分清难波各公司站厅、查过末班。',
        fallback: '迷路先上地面；出租车亮空车灯才停。',
        sources: [jnto, { label: '大阪观光局', url: 'https://osaka-info.com/' }],
      },
    ],
    checklist: [
      { id: 'c-visa', text: '签证要求已按本人证件核实；Visit Japan Web 已填或确认现场可办', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效期覆盖行程；返程与酒店订单离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '上网方案已选定并有备用', topic: '上网与手机' },
      { id: 'c-ic', text: 'IC 卡购买或绑定方案已确认', topic: '支付与交通卡' },
      { id: 'c-cash', text: '银行卡境外功能开通；备有小额现金', topic: '支付与交通卡' },
      { id: 'c-stay', text: '入住时间、寄存与晚到方案已确认', topic: '住宿与入住' },
      { id: 'c-arrival', text: '南海／JR／巴士路线与下车站已截图', topic: '关西机场 → 酒店' },
      { id: 'c-last', text: '已查住处附近地铁末班', topic: '市内交通' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：南一天，城一天',
      note: '住难波。第一天抵达，第二天南市区，第三天大阪城加返程。',
      days: [
        { day: '第一天', body: '抵达入住，道顿堀走一段吃晚饭。', time: '按落地安排', start: 'KIX → 酒店', return: '难波', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '黑门市场早餐 → 法善寺横丁 → 心斋桥；傍晚新世界加通天阁，串炸当晚饭。', time: '全天南市区', start: '黑门市场', return: '新世界／难波', links: [{ label: '难波与道顿堀', href: '?tab=places#area-namba-dotonbori' }] },
        { day: '第三天', body: '大阪城公园晨走，中之岛美术馆或咖啡，按航班收尾。', time: '上午城、午后收尾', start: '大阪城', return: '酒店 → 机场', links: [{ label: '看点', href: '?tab=places' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加一天留白与联游',
      note: '3 晚骨架上加中之岛半天、新世界独立半天或京都／奈良当日往返。',
      days: [
        { day: '第一天', body: '抵达入住早睡。', time: '按落地安排', start: 'KIX → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '黑门市场 → 法善寺 → 道顿堀夜景。', time: '全天', start: '黑门市场', return: '难波', links: [{ label: '难波与道顿堀', href: '?tab=places#area-namba-dotonbori' }] },
        { day: '第三天', body: '大阪城公园半天 → 中之岛美术馆与河边咖啡。', time: '上午城、下午岛', start: '谷町四丁目', return: '淀屋桥方向', links: [{ label: '大阪城与森之宫', href: '?tab=places#area-osaka-castle-park' }] },
        { day: '第四天', body: '新世界半天（通天阁 + 串炸）或京都当日往返。', time: '半天或一天', start: '惠美须町', return: '按路线', links: [{ label: '新世界与天王寺', href: '?tab=places#area-shinsekai-tennoji' }] },
        { day: '第五天', body: '梅田补买或留白，按航班去机场。', time: '上午慢走、午后收尾', start: '住处附近', return: '酒店 → 机场', links: [{ label: '梅田', href: '?tab=places#area-umeda-kita' }] },
      ],
    },
  },
  safety: {
    city: '大阪',
    checkedAt: '2026-09-15',
    emergencyNote: '大阪治安整体好，留意闹市区拉客与夜间纠纷。保存酒店日文地址。',
    contacts: [
      { name: '报警', number: '110', dial: '110', use: '盗窃、纠纷、交通事故', source: { label: '日本警察厅', url: 'https://www.npa.go.jp/' }, urgent: true },
      { name: '急救 / 火灾', number: '119', dial: '119', use: '急救车与火警', source: jnto, urgent: true },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '护照与入境许可信息离线保存。',
      '保存酒店日文地址与电话。',
      '境外医疗保险与救援电话另存。',
      '记熟 110／119；纯流量卡不能打电话。',
      '地震与台风季关注气象厅预警。',
    ],
    alerts: japanAlerts('大阪'),
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['到最近交番（派出所）报失拿证明。', '联系中国驻大阪总领事馆补办旅行证件（先预约）。', '保留报失证明理赔。', '确认新证件出入境可用再改签。'], sources: [consular, { label: '中国驻大阪总领事馆', url: 'http://osaka.china-consulate.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 119。', '非紧急请酒店推荐诊所或综合医院。', '保留收据与诊断证明走保险。'], sources: [jnto] },
      { id: 'safety-fraud', title: '拉客或消费纠纷', steps: ['不接受街头带路与模糊报价。', '账单争议先拍照再交涉；拒绝支付明显虚高费用。', '纠纷升级拨 110。'], sources: [jnto] },
      { id: 'safety-transport', title: '错过末班或迷路', steps: ['回最近地铁站闸口看地图。', '深夜用正规出租车排队区或叫车应用。', '手机没电找便利店或交番求助。'], sources: [jnto] },
    ],
  },
  relatedGuides: [
    '日本国家页 → /places/japan',
    '京都城市页 → /places/japan/kyoto',
    '福冈城市页 → /places/japan/fukuoka',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('osaka').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}

export const fukuoka: CityContent = {
  city: city('fukuoka'),
  checkedAt: '2026-09-15',
  meta: [
    { label: '最佳季节', value: '春秋最舒服；夏湿热，冬阴冷少雪。' },
    { label: '机场', value: '福冈机场（FUK）离博多站地铁两站、十分钟上下，是全日本离市区最近的机场之一。' },
    { label: '建议停留', value: '2–3 晚。市区一天半，太宰府半天，剩下的留给吃。' },
    { label: '地区标签', value: '东亚 · 九州' },
    { label: '气质', value: '机场贴城的港町，拉面与屋台' },
  ],
  essentials: [
    {
      title: '机场 → 市区',
      body: '福冈机场国际线与国内线分栋，地铁直通国内线航站楼下；国际线先乘免费联络巴士到国内线再换地铁，或打车直达博多／天神（车程短）。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: '福冈机场', url: 'https://www.fukuoka-airport.jp/' }],
    },
    {
      title: '建议住哪',
      body: '第一次来住博多站（新干线与机场线交汇）或天神（商场与餐馆密）。中洲夹在中间，夜里热闹但偏吵。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '2 晚排市区一天、太宰府半天加屋台一晚；3 晚加大濠公园与百道海滨。福冈不靠大景点，靠吃与近郊。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '福冈的尺度对慢旅行友好：机场在城里，博多站到天神地铁几分钟，大部分内容步行加一两站地铁能到。',
    '博多旧市街有栉田神社与川端商店街，是这座城的老底子；天神是商场与咖啡馆；中洲的屋台（路边摊）只在夜里出现。',
    '大濠公园与福冈城迹是白天留白的好去处；太宰府天满宫在市外半小时，平日去最顺。',
    '这座城的名气在吃：博多拉面、明太子、鳗鱼饭、屋台。行程排松一点，把胃口留给市场与小店。',
  ],
  gettingThere: {
    intro: [
      '福冈机场（FUK）：国内线航站楼下接地铁空港线，两站到博多、约十分钟到天神方向。国际线与国内线之间有免费联络巴士。',
      '新干线到博多站；市内地铁三条线（空港线、箱崎线、七隈线）加巴士网，IC 卡（nimoca／Suica 互通）直接刷。',
      '市区步行可行：博多—中洲—天神是一条两公里上下的线，沿河走。',
    ],
    links: [
      { label: '福冈机场', url: 'https://www.fukuoka-airport.jp/' },
      { label: '福冈市旅游信息', url: 'https://yokanavi.com/' },
    ],
    verifyReminders: [
      '国际线—国内线联络巴士当前班次与乘车点',
      '地铁一日券与 IC 卡的取舍（一天三程以上一日券划算）',
      '西铁电车去太宰府的当前票价与换乘（二日市换线）',
      '屋台出摊受天气影响，雨天减少',
    ],
  },
  neighborhoods: [
    {
      id: 'hakata-oldtown',
      title: '博多站与旧市街',
      suited: '要交通便利、又想要老街区的人。',
      image: cityImages['fukuoka-hakata'],
      body: '博多站是枢纽；站西侧旧市街有栉田神社、川端商店街与几座小寺，半天能走完。拉面老店多在站周边。',
      visit: {
        duration: '半天。',
        entry: 'JR／地铁博多站。',
        walk: '博多站 → 栉田神社 → 川端商店街 → 中洲河边。',
        return: '博多站或中洲川端站返回。',
        stay: '首选居住区之一；新干线与机场线同站，进出城都顺。',
        source: { label: 'Yokanavi', url: 'https://yokanavi.com/' },
      },
    },
    {
      id: 'tenjin',
      title: '天神',
      suited: '想住商场与咖啡馆中间的人。',
      image: cityImages['fukuoka-tenjin'],
      body: '天神是商业心脏：地下街极大，百货与品牌集中；巷子里有独立咖啡馆与旧书店。从大濠公园走过来不远。',
      visit: {
        duration: '半天。',
        entry: '地铁天神站或西铁福冈（天神）站。',
        walk: '天神地下街一段 → 新天町商店街 → 往大濠方向。',
        return: '天神站返回。',
        stay: '住处多、吃饭方便；比博多站热闹。',
        source: { label: 'Yokanavi', url: 'https://yokanavi.com/' },
      },
    },
    {
      id: 'nakasu',
      title: '中洲与屋台',
      suited: '想在夜里吃路边摊的人。',
      image: cityImages['fukuoka-nakasu'],
      body: '中洲是夜生活区，那珂川沿岸的屋台是福冈的招牌场景：塑料棚里拉面、关东煮、烤串。独行夜归时结伴更安心。',
      visit: {
        duration: '一个晚上；别把正餐全押在一家摊上。',
        entry: '地铁中洲川端站。',
        walk: '中洲川端站 → 那珂川沿岸屋台群 → 挑一家人不算满的坐下。',
        return: '中洲川端站或步行回天神。',
        stay: '不建议住中洲正中（夜里吵）；住天神走过来。',
        source: { label: 'Yokanavi', url: 'https://yokanavi.com/' },
      },
    },
    {
      id: 'ohori-maizuru',
      title: '大濠公园与舞鹤',
      suited: '想要公园、城迹与安静半天的人。',
      image: cityImages['fukuoka-ohori'],
      body: '大濠公园环湖一周约两公里，旁边是福冈城迹（舞鹤公园）。本地人在此跑步散步，是福冈最松的一段。',
      visit: {
        duration: '半天。',
        entry: '地铁大濠公园站。',
        walk: '环湖一段 → 福冈城迹（残存石垣与橹）→ 公园咖啡馆。',
        return: '大濠公园站返回。',
        stay: '不作居住建议；当中午留白。',
        source: { label: 'Yokanavi', url: 'https://yokanavi.com/' },
      },
    },
  ],
  stay: {
    checkedAt: '2026-09-14',
    intro:
      '福冈的住宿决策很简单：博多站还是天神。两站地铁三分钟，按「进出城方便」还是「晚饭圈在脚下」二选一；中洲住正中要避开。',
    budgetNote:
      '以 ¥700–800/晚为上限：在福冈很宽裕——博多站、天神的中档酒店平日 ¥450–900 常见，是全目录里预算压力最小的日本城市之一。',
    anchors: [
      { title: '贴空港线选', body: '地铁空港线串起博多站—中洲川端—天神—大濠，住在这条线沿线都顺。' },
      { title: '机场就在市区边', body: '博多站地铁两站、出租车十来分钟到机场，到达日不用为交通留缓冲。' },
      { title: '中洲只吃不睡', body: '屋台与夜生活集中在那珂川两岸，住正中会吵——住天神步行可达。' },
    ],
    areas: [
      {
        id: 'hakata-station-stay',
        title: '博多站',
        suitsIf: '以福冈为基地跑太宰府、由布院的人；晚到早走的人。',
        budgetFeel: '这档预算明显宽裕，平日 ¥450–700 就有正经中档。',
        band: { low: 410, high: 730 },
        transit: '新干线＋JR＋地铁空港线同站；去机场两站地铁。',
        food: '站内食街与站东的拉面店群；屋台要过川去中洲。',
        tradeoff: '站周边商务感；夜生活与屋台隔一条那珂川。',
        neighborhoodIds: ['hakata-oldtown'],
      },
      {
        id: 'tenjin-stay',
        title: '天神',
        suitsIf: '想要商圈与晚饭圈在脚下的人。',
        budgetFeel: '这档预算中位偏上；比博多站贵一档。',
        band: { low: 500, high: 910 },
        transit: '地铁空港线天神站＋西铁大牟田线终点；去太宰府方向顺。',
        food: '天神商圈与西中洲步行圈；屋台走过中洲桥就到。',
        tradeoff: '周末夜间商圈吵；去博多站需一站地铁或 15 分钟步行。',
        neighborhoodIds: ['tenjin'],
      },
      {
        id: 'nakasu-stay',
        title: '中洲',
        suitsIf: '想贴着屋台与夜生活住的人。',
        budgetFeel: '这档预算可住到河景中档；周末上浮。',
        band: { low: 450, high: 820 },
        transit: '地铁中洲川端站；夹在博多与天神中间、两边都可步行。',
        food: '屋台群与一兰总本店就在楼下。',
        tradeoff: '夜里吵、街区是成人娱乐区；选房看楼层与朝向。',
        skipIf: '对夜间环境敏感或带家人——住天神走过来吃屋台。',
        neighborhoodIds: ['nakasu'],
      },
    ],
  },
  dayTrips: [
    { direction: '太宰府天满宫', how: '西铁电车约 30 分钟（二日市换乘）', worth: '学问之神天满宫加表参道，半天；平日早去，节假日挤。' },
    { direction: '糸岛', how: 'JR 加巴士约一小时', worth: '海岸与咖啡馆；晴天去，阴天失色。' },
    { direction: '小仓·门司港', how: '新干线或 JR 约 30–60 分钟', worth: '门司港怀旧街区与关门海峡；半天到一天。' },
  ],
  dayTripNote: '太宰府最稳、交通最简；糸岛看天气；门司港给喜欢旧港町的人。',
  eatIntro:
    '福冈的吃围绕豚骨拉面展开，但别只吃拉面：明太子、鳗鱼饭、屋台关东煮与烤串是另一半。屋台按人点单、挤着坐，是体验不是排场。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'ramen', title: '博多拉面',
      intro: '豚骨白汤＋细直面，替玉（加面）是本地习惯——先点小份面，不够再加。',
      restaurants: [
        {
          id: 'ichiran-hq', name: '一兰 总本店', nameEn: 'Ichiran HQ', neighborhood: '中洲／那珂川畔',
          location: { address: '福冈市博多区中洲5-3-2', areaId: 'nakasu', connection: '中洲川端站步行约2分钟；整栋楼是一兰', source: { label: '官网', url: 'https://ichiran.com/' } },
          order: ['天然豚骨拉面', '替玉半份先试试'],
          whyLinger: '一兰的总店就在中洲河边——味集中座位隔板一人一格，是「豚骨拉面到底是什么味」的基准线。',
          practical: '自助购票机点单选口味；营业时间长（以门店为准）。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '官网', url: 'https://ichiran.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=一蘭+総本店' }],
        },
        {
          id: 'hakata-issou', name: '博多一双', nameEn: 'Hakata Issou', neighborhood: '博多站东',
          location: { address: '福冈市博多区博多站东3-1-6', areaId: 'hakata-oldtown', connection: '博多站步行约8分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=博多一双' } },
          order: ['拉面', '替玉'],
          whyLinger: '本地口碑常年靠前的豚骨专门店——泡沫系浓汤的代表，比连锁更接近福冈本地口味。',
          practical: '常年排队，饭点 30 分钟起；店内有日英菜单。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=博多一双' }],
          queueNote: '只收现金；开门时段（11 点前后）人最少。',
        },
      ],
    },
    {
      id: 'regional', title: '明太子与鳗鱼饭',
      intro: '福冈的乡土味：明太子饭和蒸笼鳗鱼饭（せいろ蒸し）是坐下慢慢吃的两类。',
      restaurants: [
        {
          id: 'mentaiju', name: '元祖博多めんたい重', nameEn: 'Ganso Hakata Mentaiju', neighborhood: '西中洲',
          location: { address: '福冈市中央区西中洲6-15', areaId: 'nakasu', connection: '天神站或中洲川端站步行约5分钟', source: { label: '官网', url: 'https://mentaiju.com/' } },
          order: ['めんたい重（明太子盖饭）', '加明太子茶渍'],
          whyLinger: '把整条腌明太子铺在饭上的专门店——福冈名物的定番吃法，早餐时段也开。',
          practical: '早餐时段相对好进；午间高峰等位。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '官网', url: 'https://mentaiju.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=元祖博多めんたい重' }],
        },
        {
          id: 'yoshizuka-unagi', name: '吉塚鳗鱼屋', nameEn: 'Yoshizuka Unagiya', neighborhood: '中洲',
          location: { address: '福冈市博多区中洲2-8-27', areaId: 'hakata-oldtown', connection: '中洲川端站步行约5分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=吉塚うなぎ屋' } },
          order: ['せいろ蒸し（蒸笼鳗鱼饭）', 'うな重'],
          whyLinger: '创业超百年的鳗鱼老铺——蒸笼做法让饭吸满酱汁，是福冈「贵一点但值得」的一餐。',
          practical: '本店楼宇内；午市比晚市容易进。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=吉塚うなぎ屋' }],
        },
      ],
    },
    {
      id: 'yatai', title: '屋台',
      intro: '那珂川沿岸与中洲街边的塑料棚摊子：一人一格、挨着坐，拉面、关东煮、烤串、饺子都有。',
      restaurants: [
        {
          id: 'nakasu-yatai-stalls', name: '中洲屋台群', nameEn: 'Nakasu Yatai Stalls', neighborhood: '中洲那珂川沿岸',
          location: { address: '中洲那珂川通り沿线', areaId: 'nakasu', connection: '中洲川端站出来沿河即见', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=中洲屋台' } },
          order: ['博多拉面小份', '关东煮·烤串几串', '饺子'],
          whyLinger: '福冈夜景的另一半——不指名单独摊：挑一家有空位、菜单有标价的坐下，和邻座聊天才是屋台的本体。',
          practical: '现金为主；先看墙上价目表再坐，雨天部分摊不出。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=中洲屋台' }],
        },
      ],
    },
    {
      id: 'cafe', title: '咖啡',
      intro: '福冈的精品咖啡密度不低，博多站与天神的自家烘焙店适合雨天。',
      restaurants: [
        {
          id: 'rec-coffee', name: 'REC COFFEE 博多', nameEn: 'REC COFFEE Hakata', neighborhood: '博多',
          location: { address: '福冈市博多区博多站前（门店以官网为准）', areaId: 'hakata-oldtown', connection: '博多站步行可达', source: { label: '官网', url: 'https://recoffee.jp/' } },
          order: ['手冲单品', '拿铁与当季甜品'],
          whyLinger: '福冈起家的精品咖啡连锁——自家烘焙、门店宽敞，是等车间隙或雨天最稳的坐住点。',
          practical: '分店多家；伴手礼豆可带走。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '官网', url: 'https://recoffee.jp/' }],
        },
      ],
    },
  ],
  howToOrder: [
    '拉面店先在售票机买票再入座；「替玉」是加面不是加汤。',
    '屋台先找空位再点，现金为主；菜单在棚内墙上。',
    '一人食拉面与屋台都顺；蒸笼鳗鱼饭当正餐。',
  ],
  avoid: [
    '屋台先看价目表再坐——个别摊报价含糊。',
    '一兰之外别排超一小时的队；福冈拉面店密度高，换一家。',
    '中洲深夜拉客（「陪你喝一杯」）一律拒绝。',
  ],
  eatRhythm:
    '早餐酒店或明太子重；午餐拉面；下午咖啡；晚上屋台或鳗鱼饭。拉面留一顿给住处附近的本地店，不只吃名店。',
  allergies: [
    '豚骨汤头无法改清汤；面含蛋者先确认。',
    '明太子是腌渍鳕鱼籽，咸辣，过敏者注意。',
    '屋台共用操作台，交叉污染难免。',
  ],
  guide: {
    city: '福冈',
    checkedAt: '2026-09-15',
    scope: '以公共交通为主的首次福冈行程；签证与入境按本人证件另核官方要求',
    intro: '先把入境资格、网络、交通卡与住处安排好。以下按 2–3 晚、住博多或天神写。',
    topics: [
      japanDocuments,
      japanMobile('福冈机场'),
      {
        id: 'payment', title: '支付与交通卡', summary: 'IC 卡互通，屋台与小店现金为主。',
        stage: 'before' as const,
        recommendation: '九州发 nimoca，与 Suica 等互通；地铁巴士便利店通用。屋台、市场与老店偏现金，备小额纸币硬币。',
        steps: [
          { title: '确认银行卡境外功能', body: '开通境外刷卡；商场与大店收卡，小店偏现金。' },
          { title: '落地办 IC 卡', body: '机场或博多站售票机可买 nimoca；手机已绑 IC 卡可直接用。' },
          { title: '备小额现金', body: '屋台与拉面售票机常见现金场景。' },
        ],
        done: 'IC 卡可用、银行卡确认能刷、备有小额现金。',
        fallback: 'IC 卡站内充值机现金补；卡刷不过用现金。',
        sources: [jnto],
      },
      japanStay('博多站或天神'),
      {
        id: 'arrival', title: '福冈机场 → 酒店', summary: '国际线先联络巴士到国内线，再地铁或打车。',
        stage: 'arrival' as const,
        recommendation: '国际到达：乘免费联络巴士到国内线航站楼换地铁空港线（博多两站、天神方向约十分钟）；行李多直接打车，福冈机场离市区近、车费可控。',
        choices: [
          { title: '联络巴士 + 地铁', body: '国际线→国内线联络巴士免费、班次密；国内线地下即地铁站，两站到博多。' },
          { title: '出租车', body: '到博多站／天神车程约 15–20 分钟；费用比东京大阪机场进城低得多。' },
        ],
        steps: [
          { title: '落地先确认方向', body: '国际线没有地铁口——别在机场里找，直接乘联络巴士或出租车。' },
          { title: '到达厅一次办完小事', body: '买 IC 卡、确认上网、看酒店地址。' },
          { title: '地铁两站概念', body: '空港线：机场→博多→中洲川端→天神，按住处选站下车。' },
        ],
        done: '到酒店，知道返程在哪个航站楼下车。',
        fallback: '深夜到达打正规出租车；确认去的是国际线还是国内线航站楼。',
        sources: [{ label: '福冈机场交通', url: 'https://www.fukuoka-airport.jp/' }],
      },
      {
        id: 'transit', title: '市内交通', summary: '地铁三条线加步行；去太宰府坐西铁。',
        stage: 'during' as const,
        recommendation: '地铁空港线串机场—博多—中洲—天神—大濠，一条线解决大半移动。去太宰府乘西铁（天神站→二日市换乘→太宰府站），与 JR 不通用。',
        steps: [
          { title: '记一条主线', body: '空港线（橙线）：机场—博多—中洲川端—天神—大濠公园。' },
          { title: '去太宰府用西铁', body: '西铁福冈（天神）站出发，二日市换太宰府线；IC 卡可用。' },
          { title: '末班约午夜', body: '屋台散场后步行或短途出租车回住处。' },
          { title: '巴士补充', body: '去百道海滨（福冈塔）方向巴士更顺；上车抽整理券或刷 IC 卡。' },
        ],
        done: '会用 IC 卡坐两条轨道系统、查过末班、知道太宰府换乘。',
        fallback: '西铁与 JR 票不通用——坐错系统出闸再换。',
        sources: [jnto, { label: '西铁电车', url: 'https://www.nishitetsu.co.jp/' }],
      },
    ],
    checklist: [
      { id: 'c-visa', text: '签证要求已按本人证件核实；Visit Japan Web 已填或确认现场可办', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效期覆盖行程；返程与酒店订单离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '上网方案已选定并有备用', topic: '上网与手机' },
      { id: 'c-ic', text: 'IC 卡方案已确认（nimoca 或互通卡）', topic: '支付与交通卡' },
      { id: 'c-cash', text: '银行卡境外功能开通；备有小额现金', topic: '支付与交通卡' },
      { id: 'c-stay', text: '入住时间、寄存与晚到方案已确认', topic: '住宿与入住' },
      { id: 'c-arrival', text: '国际线联络巴士／出租车方案已确认', topic: '福冈机场 → 酒店' },
      { id: 'c-last', text: '已查住处附近地铁末班与太宰府换乘', topic: '市内交通' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：市区一天，太宰府半天',
      note: '住博多或天神。屋台留一个晚上。',
      days: [
        { day: '第一天', body: '抵达入住，中洲屋台或住处附近晚饭。', time: '按落地安排', start: 'FUK → 酒店', return: '中洲', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '栉田神社 → 川端商店街 → 大濠公园与福冈城迹；晚上屋台。', time: '全天', start: '博多旧市街', return: '中洲', links: [{ label: '博多站与旧市街', href: '?tab=places#area-hakata-oldtown' }] },
        { day: '第三天', body: '太宰府天满宫半天，回城拉面收尾去机场。', time: '上午近郊、午后收尾', start: '西铁太宰府', return: '酒店 → 机场', links: [{ label: '看点', href: '?tab=places' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加海滨与留白',
      note: '3 晚骨架上加百道海滨半天与一天留白／糸岛。',
      days: [
        { day: '第一天', body: '抵达入住早睡。', time: '按落地安排', start: 'FUK → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '博多旧市街＋天神散步，晚屋台。', time: '全天', start: '栉田神社', return: '中洲', links: [{ label: '中洲与屋台', href: '?tab=places#area-nakasu' }] },
        { day: '第三天', body: '大濠公园晨走 → 百道海滨与福冈塔黄昏。', time: '上午公园、傍晚海', start: '大濠公园', return: '天神方向', links: [{ label: '大濠公园与舞鹤', href: '?tab=places#area-ohori-maizuru' }] },
        { day: '第四天', body: '太宰府半天；下午留白或糸岛（看天气）。', time: '半天近郊', start: '西铁太宰府', return: '回住处', links: [{ label: '看点', href: '?tab=places' }] },
        { day: '第五天', body: '博多站补买拉面伴手礼，按航班去机场。', time: '上午收尾', start: '住处附近', return: '酒店 → 机场', links: [{ label: '博多站与旧市街', href: '?tab=places#area-hakata-oldtown' }] },
      ],
    },
  },
  safety: {
    city: '福冈',
    checkedAt: '2026-09-15',
    emergencyNote: '福冈治安好，中洲深夜留意拉客。保存酒店日文地址。',
    contacts: [
      { name: '报警', number: '110', dial: '110', use: '盗窃、纠纷、交通事故', source: { label: '日本警察厅', url: 'https://www.npa.go.jp/' }, urgent: true },
      { name: '急救 / 火灾', number: '119', dial: '119', use: '急救车与火警', source: jnto, urgent: true },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '护照与入境许可信息离线保存。',
      '保存酒店日文地址与电话。',
      '境外医疗保险与救援电话另存。',
      '记熟 110／119；纯流量卡不能打电话。',
      '夏季台风多，关注气象厅预警。',
    ],
    alerts: japanAlerts('福冈'),
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['到最近交番报失拿证明。', '联系中国驻福冈总领事馆补办旅行证件（先预约）。', '保留报失证明理赔。', '确认新证件出入境可用再改签。'], sources: [consular, { label: '中国驻福冈总领事馆', url: 'http://fukuoka.china-consulate.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 119。', '非紧急请酒店推荐诊所。', '保留收据与诊断证明走保险。'], sources: [jnto] },
      { id: 'safety-fraud', title: '屋台或拉客纠纷', steps: ['先坐先看价目表；报价含糊就换摊。', '账单争议先拍照再交涉。', '深夜拉客一律拒绝。'], sources: [jnto] },
      { id: 'safety-transport', title: '错过末班或迷路', steps: ['市区尺度小，天神—中洲—博多可步行互达。', '深夜用正规出租车。', '手机没电找便利店或交番。'], sources: [jnto] },
    ],
  },
  relatedGuides: [
    '日本国家页 → /places/japan',
    '大阪城市页 → /places/japan/osaka',
    '东京城市页 → /places/japan/tokyo',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('fukuoka').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}
