import type { CityContent } from './types'
import { EAT_CRITERIA, EAT_EXCLUDE, HELP_PHRASES, consularHotline, consularUse } from './shared'
import { cityImages } from './photoData'
import { CONTENT_CITIES } from '../directory'

const city = (slug: string) => {
  const c = CONTENT_CITIES.find((x) => x.slug === slug)
  if (!c) throw new Error(`missing directory city: ${slug}`)
  return c
}

const kto = { label: '韩国旅游发展局 Visit Korea', url: 'https://www.visitkorea.or.kr/' }
const hikorea = { label: 'Hi Korea（出入境与签证）', url: 'https://www.hikorea.go.kr/' }
const keta = { label: 'K-ETA 官方', url: 'https://www.k-eta.go.kr/' }
const consular = { label: '中国领事服务网', url: 'https://cs.mfa.gov.cn/' }

export const seoul: CityContent = {
  city: city('seoul'),
  checkedAt: '2026-09-14',
  meta: [
    { label: '最佳季节', value: '春秋最好；冬天干冷可达零下，夏天湿热多雨（梅雨＋台风尾）。' },
    { label: '机场', value: '仁川（ICN）为主，AREX 快线直达首尔站；金浦（GMP）近市区多为国内与部分国际线。' },
    { label: '建议停留', value: '3–5 晚。宫殿与市场半天一处，山坡住宅区留一个下午。' },
    { label: '地区标签', value: '东亚 · 半岛城市' },
    { label: '气质', value: '宫殿与高楼之间，市场与山坡住宅区' },
    { label: '核实日期', value: '2026-09-14' },
  ],
  essentials: [
    {
      title: '机场 → 市区',
      body: '仁川进城两条主线：AREX 直达列车到首尔站（约 45 分钟）与普通列车（站站停）；机场巴士按酒店片区选线，深夜有大巴。先定住处片区再选线。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: '仁川机场', url: 'https://www.airport.kr/' }],
    },
    {
      title: '建议住哪',
      body: '第一次来住钟路／明洞—乙支路一带（宫殿与市场步行可达）或弘大／合井（地铁 2 号线与机场线交汇，夜里热闹）。全程一处，不为江南换酒店。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '3 晚排宫殿一天、市场与南山一天、留白；5 晚加山坡住宅区与江南或汉江边。市场当早餐加散步，不当全天。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '首尔的骨架是汉江与地铁环线。慢旅行的做法：住江北老城（钟路）或弘大一侧，每天只走一条线——宫殿线、市场线、山坡线。',
    '景福宫—北村—三清洞是一条能走半天的坡道线；广藏市场、南大门市场是早餐与白天的内容；梨泰院与汉南洞是坡上的另一座城。',
    '江南（狎鸥亭、蚕室）是平行世界：有 COEX 与江边公园，但和江北的节奏完全不同。短行程不硬排。',
    '别把首尔当购物清单。咖啡密度极高，找一家坐住，比多逛一个商场更接近这座城。',
  ],
  gettingThere: {
    intro: [
      '仁川（ICN）：AREX 直达列车到首尔站约 45 分钟，普通列车沿途各站停；机场巴士按片区分线，深夜有 N 系列大巴。金浦（GMP）更靠市区，地铁直达。',
      '市内是地铁网 + T-money 卡（或手机交通卡）。地铁换乘步行长、台阶多，带行李尽量选有电梯的站。',
      '出租车比日本便宜，深夜与跨江可用；Kakao T 是本地叫车应用。高峰过江桥堵，短距离宁地铁。',
    ],
    links: [
      { label: 'AREX 机场铁路', url: 'https://www.arex.or.kr/' },
      { label: '首尔观光 Visit Seoul', url: 'https://www.visitseoul.net/' },
    ],
    verifyReminders: [
      'AREX 直达与普通列车的当前票价、发车间隔',
      'T-money 卡购买点与手机交通卡的兼容性',
      '机场巴士各线路当前停靠站与深夜班次',
      '地铁末班时间（各线不同，约午夜前后）',
    ],
  },
  neighborhoods: [
    {
      id: 'jongno-bukchon',
      title: '钟路与北村',
      suited: '想把宫殿、韩屋村与市场放在步行半径内的人。',
      image: cityImages['seoul-jongno'],
      body: '景福宫、昌德宫在北村两侧，韩屋村本身是住宅区——早上走，轻声走。三清洞背街有咖啡馆和小画廊，比主街好坐。',
      visit: {
        duration: '半天到一天；宫殿择一重点。',
        entry: '地铁 3 号线安国站或景福宫站。',
        walk: '景福宫 → 北村韩屋村 → 三清洞背街；坡道多，穿好走的鞋。',
        return: '安国站或钟路 3 街站返回。',
        stay: '首选居住区之一；夜里比明洞安静，去宫殿和市场都是步行。',
        source: { label: 'Visit Seoul', url: 'https://www.visitseoul.net/' },
      },
    },
    {
      id: 'myeongdong-euljiro',
      title: '明洞与乙支路',
      suited: '第一次来、要购物与吃饭都顺手的人。',
      image: cityImages['seoul-myeongdong'],
      body: '明洞是游客商业区（化妆品与街头小吃），乙支路的旧巷子里是本地食堂与咖啡馆。白天逛乙支路，明洞当路过，不当据点。',
      visit: {
        duration: '2–3 小时。',
        entry: '地铁 4 号线明洞站或 2 号线乙支路入口站。',
        walk: '乙支路老巷 → 明洞主街 → 南山方向看塔（不必上塔）。',
        return: '明洞站返回；晚市人多，看紧随身物。',
        stay: '酒店密集、价格友好；闹中取静选靠乙支路一侧。',
        source: { label: 'Visit Seoul', url: 'https://www.visitseoul.net/' },
      },
    },
    {
      id: 'hongdae-hapjeong',
      title: '弘大与合井',
      suited: '晚上想有生活气、住机场线直达的人。',
      image: cityImages['seoul-hongdae'],
      body: '弘大是大学区夜生活，合井与望远一带是本地咖啡馆与市场。住这里 AREX 直达仁川，夜里回来仍有饭吃。',
      visit: {
        duration: '半天；晚上才算开始。',
        entry: '地铁 2 号线弘大入口站／合井站。',
        walk: '弘大主街 → 合井背街 → 望远市场方向。',
        return: '弘大入口站返回；深夜出租车多但查价。',
        stay: '适合晚睡的人；周末夜里吵，选离主街一两个路口的楼。',
        source: { label: 'Visit Seoul', url: 'https://www.visitseoul.net/' },
      },
    },
    {
      id: 'itaewon-hannam',
      title: '梨泰院与汉南洞',
      suited: '想看坡上街区与国际化一面的的人。',
      image: cityImages['seoul-itaewon'],
      body: '梨泰院坡道与小巷是老的外国人社区；汉南洞更安静、更贵。坡道陡，半天够，别拖行李走。',
      visit: {
        duration: '半天。',
        entry: '地铁 6 号线梨泰院站或汉江镇站。',
        walk: '梨泰院主街拐进背巷 → 往坡上走看市区景观 → 汉南洞咖啡馆。',
        return: '同站返回；坡道回程下坡，注意膝盖。',
        stay: '不建议住坡上（出行靠走陡坡）；当半天散步。',
        source: { label: 'Visit Seoul', url: 'https://www.visitseoul.net/' },
      },
    },
  ],
  dayTrips: [
    { direction: 'DMZ 非军事区', how: '只能跟团巴士，约半天—一天', worth: '政治边界实景。务必用正规旅行社并带护照；天气与安全局势影响开放。' },
    { direction: '水原华城', how: '地铁或 ITX 约一小时', worth: '城墙能走一圈，半天到一天；比市区松。' },
    { direction: '南怡岛／加平', how: '京春线约一个半小时', worth: '枫叶季与冬季热门；平日去，假日人多到失真。' },
  ],
  dayTripNote: 'DMZ 只能跟团且受局势影响；水原华城最稳；南怡岛平日去。',
  eatIntro:
    '首尔的吃从市场开始：广藏市场当早餐，正餐选一处认真吃（烤肉或汤饭），咖啡密度全城最高。辣酱与大蒜是底色，忌口先学两句韩文或用翻译卡。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'market', title: '市场小吃',
      intro: '广藏市场是早餐与上午的内容：绿豆饼、生拌牛肉、紫菜包饭现做现吃。人挤人，吃完就走。',
      restaurants: [
        {
          id: 'buchon-yukhoe', name: '富村生拌牛肉', nameEn: 'Buchon Yukhoe', neighborhood: '广藏市场',
          location: { address: '서울 종로구 자갈비길（广藏市场内）', areaId: 'jongno-bukchon', connection: '地铁钟路5街站9号口步行约3分钟进市场', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=부촌육회+광장시장' } },
          order: ['육회 生拌牛肉', '육회비빔밥 生牛肉拌饭'],
          whyLinger: '广藏市场最有名的生拌牛肉店——连续多年入选米其林必比登推介名单。市场里坐下吃一顿正经的，不只是路过小吃。',
          practical: '在市场巷内取号排队；菜单有图。营业时间以现场为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=부촌육회+광장시장' }],
          queueNote: '饭点取号等 30 分钟起；上午稍早到人少。',
        },
        {
          id: 'monyeo-gimbap', name: '母女紫菜包饭', nameEn: 'Monyeo Gimbap', neighborhood: '广藏市场',
          location: { address: '广藏市场内摊位', areaId: 'jongno-bukchon', connection: '与富村同在市场巷内', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=모녀김밥+광장시장' } },
          order: ['마약김밥 麻药紫菜包饭（蘸芥末酱油）'],
          whyLinger: '「麻药紫菜包饭」的元祖摊——小卷蘸芥末酱油汁，几串就饱的早餐量。',
          practical: '摊位现金与简单电子付；买完站边吃或带走。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=모녀김밥+광장시장' }],
        },
        {
          id: 'sunhee-bindaetteok', name: '顺熙家绿豆饼', nameEn: 'Sunhee Bindaetteok', neighborhood: '广藏市场',
          location: { address: '广藏市场内摊位', areaId: 'jongno-bukchon', connection: '市场巷内按招牌找', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=순희네빈대떡+광장시장' } },
          order: ['녹두빈대떡 绿豆饼', '配米酒（막걸리）'],
          whyLinger: '广藏市场绿豆饼的代表摊——现磨现煎、外脆内软，配一碗米酒就是市场早餐的正解。',
          practical: '摊位现煎；现金与简单电子付。高峰期拼桌坐。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=순희네빈대떡+광장시장' }],
        },
      ],
    },
    {
      id: 'bbq', title: '烤肉',
      intro: '韩式烤肉是两人起跳的正餐：按人份点肉，配菜无限续。一人也有单人烤肉店，但氛围不同。',
      restaurants: [
        {
          id: 'wangbijib', name: '王妃家', nameEn: 'Wangbijib', neighborhood: '明洞',
          location: { address: '서울 중구 명동（明洞本店）', areaId: 'myeongdong-euljiro', connection: '地铁明洞站步行可达；多家分店', source: { label: '官网', url: 'http://www.wangbijib.com/' } },
          order: ['调味排骨（양념갈비）', '猪五花或韩牛套餐'],
          whyLinger: '明洞最有名的烤肉店之一：肉质稳定、有人帮烤，第一次吃韩式烤肉的稳妥选择。',
          practical: '按人份点（两人起点）；晚餐高峰等位。以官网店址为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'http://www.wangbijib.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=왕비집+명동' }],
        },
        {
          id: 'eongteori', name: '荒谬的生肉', nameEn: 'Eongteori Saenggogi', neighborhood: '弘大',
          location: { address: '서울 마포구（弘大店）', areaId: 'hongdae-hapjeong', connection: '地铁弘大入口站步行约8分钟；连锁多处', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=엉터리생고기+홍대' } },
          order: ['烤五花肉＋大酱汤自助套餐'],
          whyLinger: '无限续的烤五花肉专门店——价格固定、大酱汤锅自取，是学生区出身的性价比之选。',
          practical: '自助形式按人头收费；晚市等位常见。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=엉터리생고기+홍대' }],
        },
      ],
    },
    {
      id: 'soup', title: '汤饭与参鸡汤',
      intro: '雪浓汤、参鸡汤是坐下来的热食。冬天尤其合适；参鸡汤在三伏天反而是旺季。',
      restaurants: [
        {
          id: 'tosokchon', name: '土俗村参鸡汤', nameEn: 'Tosokchon', neighborhood: '景福宫东侧',
          location: { address: '서울 종로구 자하문로5길 5', areaId: 'jongno-bukchon', connection: '地铁景福宫站2号口步行约5分钟', source: { label: '官网', url: 'http://tosokchon.com/' } },
          order: ['参鸡汤（삼계탕）', '乌鸡参鸡汤'],
          whyLinger: '景福宫旁最著名的参鸡汤店——一整只童子鸡塞糯米人参，韩屋庭院里吃。逛完宫殿顺路。',
          practical: '店大翻台快但饭点仍排队；一人一份是常态。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'http://tosokchon.com/' }, { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=토속촌+삼계탕' }],
          queueNote: '饭点排 20–40 分钟；开门时段（约10点）人最少。',
        },
        {
          id: 'sinseon-seolnongtang', name: '神仙雪浓汤', nameEn: 'Sinseon Seolnongtang', neighborhood: '连锁（明洞等多处）',
          location: { address: '明洞等多家分店', areaId: 'myeongdong-euljiro', connection: '按住处附近搜「신선설농탕」', source: { label: '官网', url: 'https://www.sinseonfood.com/' } },
          order: ['雪浓汤（설농탕）', '加白切肉拼盘'],
          whyLinger: '雪浓汤连锁的代表——牛骨白汤自己加盐加葱，24 小时店多，深夜或早班机前后都接得上。',
          practical: '桌边自助加料；分店多、营业时间以门店为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.sinseonfood.com/' }],
        },
      ],
    },
    {
      id: 'cafe', title: '咖啡与烘焙',
      intro: '首尔咖啡密度极高，韩屋咖啡馆与烘焙专门店水平都在线。走累了找一家坐住是这座城的正确休息方式。',
      restaurants: [
        {
          id: 'cafe-onion-anguk', name: 'Café Onion 安国店', nameEn: 'Café Onion Anguk', neighborhood: '安国／三清洞方向',
          location: { address: '서울 종로구 계동길 5', areaId: 'jongno-bukchon', connection: '地铁安国站3号口步行约3分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=cafe+onion+anguk' } },
          order: ['盐面包（소금빵）', '招牌 Pandoro 雪山面包', '手冲或拿铁'],
          whyLinger: '韩屋改建的咖啡馆——坐在院子里喝咖啡看瓦檐，是北村散步的收尾点。面包烘焙是强项。',
          practical: '等位常见；院子与室内席位按现场安排。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=cafe+onion+anguk' }],
          queueNote: '周末下午等位长；平日上午最松。',
        },
        {
          id: 'fritz-dohwa', name: 'Fritz Coffee 桃花洞本店', nameEn: 'Fritz Coffee Dohwa', neighborhood: '孔德／麻浦',
          location: { address: '서울 마포구 새창로2길 17', areaId: 'hongdae-hapjeong', connection: '地铁孔德站步行约10分钟', source: { label: '官网', url: 'https://fritz.co.kr/' } },
          order: ['手冲单品', '可颂与当季烘焙'],
          whyLinger: '首尔精品咖啡的代表之一：旧建筑＋海狗标志，豆子自家烘焙。比网红店更接近「本地日常」。',
          practical: '柜台点单；伴手礼豆可带走。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://fritz.co.kr/' }],
        },
      ],
    },
    {
      id: 'anju', title: '炸鸡与下酒菜',
      intro: '炸鸡配啤酒（치맥）是晚上选项；乙支路的户外啤酒摊一条街是更老的本地形态。',
      restaurants: [
        {
          id: 'manseon-hof', name: '万善 Hof', nameEn: 'Manseon Hof', neighborhood: '乙支路3街',
          location: { address: '서울 중구 을지로（乙支路노가리골목）', areaId: 'myeongdong-euljiro', connection: '地铁乙支路3街站附近巷内', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=만선호프+을지로' } },
          order: ['生啤（생맥주）', '노가리 烤干明太鱼'],
          whyLinger: '乙支路「干明太鱼巷」的代表店——傍晚塑料椅坐满下班族，是首尔最市井的喝酒场景。',
          practical: '户外席位先到先得；按人点酒是默认。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=만선호프+을지로' }],
        },
        {
          id: 'kyochon', name: '校村炸鸡', nameEn: 'Kyochon Chicken', neighborhood: '连锁（弘大等多处）',
          location: { address: '弘大等多家分店', areaId: 'hongdae-hapjeong', connection: '按住处附近搜「교촌치킨」', source: { label: '官网', url: 'https://www.kyochon.com/' } },
          order: ['蜂蜜炸鸡（허니콤보）', '原味＋调味半半'],
          whyLinger: '韩国炸鸡连锁的头牌之一——酱油蒜香与蜂蜜系列是招牌，店内吃比外卖更脆。',
          practical: '一份够两人；可堂食或外卖。以门店为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.kyochon.com/' }],
        },
      ],
    },
  ],
  howToOrder: [
    '烤肉店按人份点肉，配菜（반찬）免费续。',
    '市场摊位指着吃或说数量；现金与小面额纸币好用。',
    '一人食找「혼밥」标识或定食店；烤肉可找单人烤肉店。',
    '咖啡馆自助机点单普遍；英文名或拍照取餐。',
  ],
  avoid: [
    '明洞主街的「游客价」小吃摊偏贵；同样东西市场里便宜。',
    '景区门口主动拉客的餐厅与换钱所不进——换钱去银行或正规换钱所。',
    '别为网红店横穿全城；同品类找住处附近的。',
  ],
  eatRhythm:
    '早餐去市场（广藏或住处附近的市场）；午餐汤饭或定食；下午咖啡馆；晚上认真吃烤肉或汤锅。一天最多排一处需要等位的店。',
  allergies: [
    '辣椒酱（고추장）与大蒜几乎无处不在，辣度与忌口写下来给店员看。',
    '海鲜酱（새우젓 虾酱）常用于泡菜与汤——甲壳类过敏注意。',
    '配菜共用夹取，交叉污染难免。',
  ],
  guide: {
    city: '首尔',
    checkedAt: '2026-09-14',
    scope: '以公共交通为主的首次首尔行程；签证与入境按本人证件另核官方要求',
    intro: '先把入境资格、网络、交通卡与住处安排好。以下按 3–5 晚、住江北或弘大一侧写。',
    topics: [
      {
        id: 'documents', title: '证件与入境', summary: '签证／K-ETA 按护照核对，别混用两套规则。', stage: 'before',
        recommendation: '韩国对部分护照免签但需事先办 K-ETA 电子许可；中国大陆护照赴首尔通常需签证（济州岛另有免签政策）。在 Hi Korea 或就近使领馆按本人证件核实，政策调整频繁，以官方当前公告为准。',
        steps: [
          { title: '先按护照查签证路径', body: 'Hi Korea 或韩国使领馆按国籍查：需签证、免签但需 K-ETA、或完全免签是三种不同路径，别套别人的经验。' },
          { title: '需要 K-ETA 的提前在线办', body: 'K-ETA 在官方网站申请（注意辨别仿冒收费网站），批准后与护照关联；出发前确认仍在有效期。' },
          { title: '材料放一起', body: '返程订单、首晚酒店名称地址、同行人联系方式离线保存；入境可能询问。' },
          { title: '入境后核对停留期', body: '按现场通道办理，收好入境许可信息，按获准期限离境。' },
        ],
        done: '入境路径已按证件核实；K-ETA 或签证材料齐备，订单离线可查。',
        fallback: 'K-ETA 状态异常或签证问题先联系官方渠道，不要到机场再处理。',
        sources: [hikorea, keta, consular],
      },
      {
        id: 'mobile', title: '上网与手机', summary: '漫游、eSIM 或落地 SIM 三选一，先查手机支持。', stage: 'before',
        recommendation: '国内运营商韩国漫游包最省事；流量需求大选 eSIM（先确认手机支持）或落地买游客 SIM。仁川到达厅有运营商柜台。',
        steps: [
          { title: '查手机是否支持 eSIM', body: '国行手机多数不支持；按厂商说明确认后再下单。' },
          { title: '按天数比总价', body: '漫游包、eSIM 套餐、落地 SIM 按天数比较；留意计时起点与是否含通话。' },
          { title: '落地先测再离开柜台', body: '关 Wi-Fi 开地图，给同行人发消息；当地卡关闭国内卡数据漫游。' },
        ],
        done: '离开 Wi-Fi 能开地图发消息，套餐到期日明确。',
        fallback: '无网先连机场 Wi-Fi 联系客服；备用漫游包应急。',
        sources: [kto],
      },
      {
        id: 'payment', title: '支付与交通卡', summary: '刷卡高度普及，T-money 管交通，现金备用。', stage: 'before',
        recommendation: '韩国是刷卡社会，多数店收卡。交通用 T-money 卡（地铁、巴士、便利店通用），现金留给市场小摊与找零。',
        steps: [
          { title: '确认银行卡境外功能', body: '开通境外刷卡；韩国店铺 Visa／Mastercard 普及，银联在游客区可用但别当唯一方案。' },
          { title: '落地买 T-money', body: '机场便利店或地铁站售票机可买可充；一人一卡，上下车各刷一次（巴士换乘有折扣规则）。' },
          { title: '备小额现金', body: '市场小摊与个别老店收现金；机场与市区银行、正规换钱所汇率透明，街头私换不要碰。' },
        ],
        done: 'T-money 可用、银行卡确认能刷、备有小额现金。',
        fallback: '卡刷不过用现金；T-money 余额可在便利店退（按规则收手续费）。',
        sources: [{ label: 'T-money', url: 'https://www.tmoney.co.kr/' }, kto],
      },
      {
        id: 'stay', title: '住宿与入住', summary: '钟路或弘大住稳，确认晚到与退房寄存规则。', stage: 'before',
        recommendation: '第一次来住钟路／明洞—乙支路（宫殿与市场步行可达）或弘大（AREX 直达）。韩国酒店与民宿对入住时间、行李寄存规则差异大，订前确认。',
        steps: [
          { title: '按晚间活动圈选片区', body: '把酒店放在晚饭后能走回或一程地铁回的范围；地铁站名≠出门距离，看实际步行路径。' },
          { title: '核对入住与寄存规则', body: '韩国入住时间普遍偏晚（15:00 后常见）；提前到达或退房后寄存行李先问前台。' },
          { title: '确认总价与押金', body: '看付款页含税总价与押金、是否需要本人信用卡；截图保存。' },
          { title: '晚到先问清楚', body: '民宿与小旅馆发消息确认晚到取钥匙；保存韩文地址给司机看。' },
        ],
        done: '入住时间、寄存、晚到方案与到站路径已确认。',
        fallback: '规则不清改订可取消住处；现场纠纷找预订平台。',
        sources: [kto],
      },
      {
        id: 'arrival', title: '仁川机场 → 酒店', summary: 'AREX 到首尔站再换乘，或机场巴士按片区直达。', stage: 'arrival',
        recommendation: '住钟路／首尔站方向：AREX 直达列车最稳。住弘大：AREX 普通列车直达弘大入口站。行李多或深夜到，选对应片区的机场巴士或正规出租车。',
        choices: [
          { title: 'AREX 直达列车', body: '仁川—首尔站约 45 分钟，全车指定席；适合住处在首尔站或换乘方便处。' },
          { title: 'AREX 普通列车', body: '站站停但直达弘大、孔德等市区站；不赶时间更顺路。' },
          { title: '机场巴士', body: '按片区选线（明洞、东大门、江南等）；深夜有 N 系列。先查酒店最近停靠站。' },
        ],
        steps: [
          { title: '落地前存好整条路线', body: '交通方式、下车站、末班时间截图；用预计出关时间判断。' },
          { title: '到达厅一次办完小事', body: '买 T-money、确认上网、看酒店地址；柜台都在到达层。' },
          { title: '按标识找车站或巴士站台', body: 'AREX 站与巴士乘车站标识清楚；巴士按线路编号找站台。' },
          { title: '到站后先找地面再导航', body: '首尔站等大站地下复杂，出站后再开步行导航。' },
        ],
        done: '到酒店，知道返程在哪个站／站台上车。',
        fallback: '深夜到达用机场大巴或正规出租车；不上揽客车。',
        sources: [{ label: '仁川机场交通', url: 'https://www.airport.kr/' }, { label: 'AREX', url: 'https://www.arex.or.kr/' }],
      },
      {
        id: 'transit', title: '市内交通', summary: '地铁网密集，T-money 一卡到底，注意末班。', stage: 'during',
        recommendation: '地铁覆盖全城，中文报站与标识普及。换乘通道长、台阶多——带行李选有电梯出口；巴士换乘有折扣但要先搞清上下车各刷一次。',
        steps: [
          { title: '查线看方向与出口', body: '地铁按线路号与方向找站台；记下出口编号，大站错出口多走一公里。' },
          { title: '巴士上下各刷一次', body: 'T-money 巴士上车刷一次、下车刷一次才有换乘折扣；现金投币不找零备零钱。' },
          { title: '记住末班约午夜', body: '各线末班不同；深夜用 Kakao T 或正规出租车，弘大江南深夜打车要排队。' },
          { title: '过江留时间', body: '汉江两岸靠桥与隧道，高峰堵；江南江北往返算足时间。' },
        ],
        done: '会用 T-money 坐地铁巴士、查末班、知道住处最近出口。',
        fallback: '迷路回最近地铁站闸口看地图；出租车亮「빈차」（空车）灯才停。',
        sources: [kto, { label: 'Visit Seoul 交通', url: 'https://www.visitseoul.net/' }],
      },
    ],
    checklist: [
      { id: 'c-visa', text: '签证／K-ETA 路径已按本人证件核实并在有效期', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效期覆盖行程；返程与酒店订单离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '上网方案已选定并有备用', topic: '上网与手机' },
      { id: 'c-tmoney', text: 'T-money 购买方式已确认', topic: '支付与交通卡' },
      { id: 'c-cash', text: '银行卡境外功能开通；备有小额现金', topic: '支付与交通卡' },
      { id: 'c-stay', text: '入住时间、寄存与晚到方案已确认', topic: '住宿与入住' },
      { id: 'c-arrival', text: 'AREX／机场巴士路线与下车站已截图', topic: '仁川机场 → 酒店' },
      { id: 'c-last', text: '已查住处附近地铁末班', topic: '市内交通' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：宫殿一天，市场一天',
      note: '住钟路或弘大。每天一个方向，宫殿与市场各留半天。',
      days: [
        { day: '第一天', body: '抵达入住，住处附近吃晚饭早睡。', time: '按落地安排', start: 'ICN → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '景福宫或昌德宫择一 → 北村早走 → 三清洞咖啡馆；晚回住处附近吃。', time: '上午宫殿、下午慢走', start: '安国站方向', return: '钟路／住处', links: [{ label: '钟路与北村', href: '?tab=places#area-jongno-bukchon' }] },
        { day: '第三天', body: '广藏市场早餐加散步，按航班收尾去机场。', time: '上午市场、午后收尾', start: '住处 → 广藏市场', return: '酒店 → 机场', links: [{ label: '看点', href: '?tab=places' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加山坡与汉江',
      note: '3 晚骨架上加梨泰院／汉南洞半天与留白一天；留白补天气。',
      days: [
        { day: '第一天', body: '抵达入住早睡。', time: '按落地安排', start: 'ICN → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '宫殿 + 北村 + 三清洞一天。', time: '全天', start: '安国站', return: '钟路', links: [{ label: '钟路与北村', href: '?tab=places#area-jongno-bukchon' }] },
        { day: '第三天', body: '广藏市场早餐 → 明洞／乙支路 → 南山公园黄昏。', time: '上午市场、傍晚南山', start: '广藏市场', return: '明洞站方向', links: [{ label: '明洞与乙支路', href: '?tab=places#area-myeongdong-euljiro' }] },
        { day: '第四天', body: '梨泰院—汉南洞上坡散步 + 咖啡馆；或留白补体力。', time: '半天上坡、半天留白', start: '梨泰院站', return: '回住处方向', links: [{ label: '梨泰院与汉南洞', href: '?tab=places#area-itaewon-hannam' }] },
        { day: '第五天', body: '弘大／合井慢走或补买，按航班去机场。', time: '上午慢走、午后收尾', start: '住处附近', return: '酒店 → 机场', links: [{ label: '弘大与合井', href: '?tab=places#area-hongdae-hapjeong' }] },
      ],
    },
  },
  safety: {
    city: '首尔',
    checkedAt: '2026-09-14',
    emergencyNote: '首尔治安好，主要留意闹市区夜间纠纷、换钱与拉客。保存酒店韩文地址。',
    contacts: [
      { name: '报警', number: '112', dial: '112', use: '盗窃、纠纷、交通事故', source: { label: '韩国警察厅', url: 'https://www.police.go.kr/' }, urgent: true },
      { name: '急救 / 火灾', number: '119', dial: '119', use: '急救车与火警（有外语服务）', source: kto, urgent: true },
      { name: '旅游咨询', number: '1330', dial: '1330', use: 'KTO 旅游热线，多语种 24 小时', source: kto },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '签证／K-ETA 状态确认截图离线保存。',
      '保存酒店韩文地址与电话。',
      '境外医疗保险与救援电话另存。',
      '记熟 112／119／1330；纯流量卡不能打电话。',
      '冬季备防滑鞋与保暖层；夏季梅雨带雨具。',
      '夜间闹市区看紧随身物，拒绝拉客。',
    ],
    alerts: [
      { title: '梨泰院坡道与人群', body: '万圣夜等节庆期间梨泰院人群密度极高——2022 年踩踏事故后政府加强人流管控。节庆夜避开窄巷，跟着官方人流指引走。', source: kto },
      { title: '街头换钱与拉客', body: '换钱只去银行或挂牌正规换钱所；街头「私人换钱」与拉客店不碰。', source: kto },
      { title: '出租车与深夜交通', body: '只乘正规出租车（亮「빈차」灯），要求打表；国际出租车与 Kakao T 可作预约选项。', source: kto },
      { title: '天气', body: '冬季严寒可达零下十度以上，夏季梅雨与台风尾。按季节备衣并关注气象预报。', source: kto },
    ],
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['到最近派出所报失拿证明。', '联系中国驻韩国大使馆补办旅行证件（先预约）。', '保留报失证明理赔。', '确认新证件出入境可用再改签。'], sources: [consular, { label: '中国驻韩国大使馆', url: 'http://kr.china-embassy.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 119（有外语协助）。', '非紧急请酒店推荐诊所；大医院有国际诊疗中心。', '保留收据与诊断证明走保险。'], sources: [kto] },
      { id: 'safety-crowd', title: '拥挤或踩踏风险', steps: ['节庆人群密度异常升高时主动离开窄巷。', '不逆人流、不蹲下捡拾物品，靠墙边找出口。', '与同行人约定失散集合点。'], sources: [kto] },
      { id: 'safety-fraud', title: '换钱或消费纠纷', steps: ['非正规换钱发生损失先拨 112 报警留证。', '账单争议先拍照再交涉，不满可拨 1330 旅游热线求助。', '刷卡异常立即联系发卡行止付。'], sources: [kto] },
      { id: 'safety-transport', title: '错过末班或迷路', steps: ['回最近地铁站闸口看地图。', '深夜用 Kakao T 或正规出租车排队区。', '手机没电找便利店或警亭求助。'], sources: [kto] },
    ],
  },
  relatedGuides: [
    '韩国国家页 → /places/south-korea',
    '东京城市页 → /places/japan/tokyo',
    '香港城市页 → /places/hong-kong',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('seoul').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}

export const jeju: CityContent = {
  city: city('jeju'),
  checkedAt: '2026-09-15',
  meta: [
    { label: '最佳季节', value: '春（油菜花与樱）秋（芒草与晴日）最好；夏湿热多台风，冬风大但汉拿山雪景好。' },
    { label: '机场', value: '济州国际机场（CJU）在济州市区边上，到市中心二十分钟上下。' },
    { label: '建议停留', value: '3–4 晚。岛比想象大：济州市、东岸（城山）、南岸（西归浦）各留一天，汉拿山看天气。' },
    { label: '地区标签', value: '东亚 · 海岛' },
    { label: '气质', value: '火山岛、海女与黑猪肉，风比城市多' },
    { label: '核实日期', value: '2026-09-15' },
  ],
  essentials: [
    {
      title: '机场 → 住处',
      body: '济州机场在济州市区北缘，巴士与出租车都方便。没有地铁，岛内移动靠巴士网、出租车或包车；中国大陆驾照不能在韩国租车（韩国不承认中国驾照且无国际驾照途径），别按自驾攻略做计划。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: '济州国际机场', url: 'https://www.airport.co.kr/jeju/' }],
    },
    {
      title: '建议住哪',
      body: '第一次来住济州市（老济州或新济州，机场近、巴士枢纽全）为主基地；想把东岸城山日出峰当清晨内容可在城山加一晚。不自驾的话别住太偏的民宿。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '3 晚排济州市一天、东岸城山一天、西归浦一天；4 晚加汉拿山或西线。海岛行程看天气，留一天机动。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '济州是一座岛当一座城用：济州市在北岸（机场与老市区），西归浦在南岸，中间是汉拿山。慢旅行的做法是住济州市，按方向分天走。',
    '老济州市区有东门市场与海边的龙渊；新济州（连洞）是商店与餐馆密集的新区。东岸的城山日出峰与涉地可支是明信片面，西归浦的瀑布与每日市场更本地。',
    '汉拿山是韩国最高峰，登顶线需要提前预约且受天气管制；城板岳与观音寺两条登顶线之外，御里牧等半山线更松。',
    '海女文化、黑猪肉、橘子与海风是济州的日常内容。这座岛奖励留空白的人——咖啡馆看海一下午是正经安排。',
  ],
  gettingThere: {
    intro: [
      '济州国际机场（CJU）：与济州市区一体，机场巴士与各线公交进城，出租车排队区按方向分。深夜到达班次减少，优先出租车。',
      '岛内无轨道交通：干线与支线巴士成网（T-money 可用），班次间隔比城市大；出租车与包车按天谈。',
      '重要提醒：中国大陆驾照在韩国不能租车（韩国不承认中国驾照，也无法换取国际驾照）。不自驾的行程按「巴士＋出租车＋步行」排。',
    ],
    links: [
      { label: '济州国际机场', url: 'https://www.airport.co.kr/jeju/' },
      { label: 'Visit Jeju', url: 'https://www.visitjeju.net/' },
    ],
    verifyReminders: [
      '机场到济州市区／西归浦的巴士线路与末班',
      '汉拿山登顶路线的预约规则与当日管制（按天气）',
      '东岸巴士班次间隔（周末与平日不同）',
      '包车／出租车的本地叫车方式（Kakao T 需韩国手机号或国际卡）',
    ],
  },
  neighborhoods: [
    {
      id: 'jeju-old-town',
      title: '老济州（济州市中心）',
      suited: '第一次来、要市场与巴士枢纽都在步行半径的人。',
      image: cityImages['jeju-oldtown'],
      body: '东门市场、龙渊吊桥、观德亭一带是老济州的核心；中央路地下街连着商店街。住这里，机场二十分钟、巴士总站步行可达。',
      visit: {
        duration: '半天到一天；市场当早餐。',
        entry: '巴士到中央路或东门市场站。',
        walk: '东门市场 → 中央路商店街 → 龙渊吊桥与海边散步道。',
        return: '中央路站或步行回住处。',
        stay: '首选居住区；老旅馆与酒店都有，选靠巴士总站的。',
        source: { label: 'Visit Jeju', url: 'https://www.visitjeju.net/' },
      },
    },
    {
      id: 'jeju-new-town',
      title: '新济州（连洞）',
      suited: '想要餐馆密度与购物便利的人。',
      image: cityImages['jeju-newtown'],
      body: '连洞（莲洞）是机场南侧的新区：免税店、商店街与餐馆集中，夜里比老济州热闹。离机场更近，巴士线路密。',
      visit: {
        duration: '半天；主要是吃与买。',
        entry: '巴士到连洞／新济州一带。',
        walk: '宝健路（神话街）一带 → 往海边方向走。',
        return: '就近巴士站返回。',
        stay: '住处密集的现代区；比老济州新、稍贵。',
        source: { label: 'Visit Jeju', url: 'https://www.visitjeju.net/' },
      },
    },
    {
      id: 'seongsan-east',
      title: '城山与东岸',
      suited: '想看日出峰清晨、海女与东岸海的人。',
      image: cityImages['jeju-seongsan'],
      body: '城山日出峰是济州的标志；山脚有海女表演（天气允许），旁边的涉地可支是火山岩海岸。东岸风大，防风外套常备。',
      visit: {
        duration: '一天；日出峰留清晨或傍晚避团客。',
        entry: '济州市外巴士总站乘东岸线约一个半小时。',
        walk: '城山日出峰 → 海女屋 → 涉地可支（分两段走，中间可打车）。',
        return: '城山或涉地可支乘巴士返回；记好末班。',
        stay: '想看日出可加一晚城山住处；否则回济州市。',
        source: { label: 'Visit Jeju', url: 'https://www.visitjeju.net/' },
      },
    },
    {
      id: 'seogwipo',
      title: '西归浦',
      suited: '想要瀑布、市场与更松南岸的人。',
      image: cityImages['jeju-seogwipo'],
      body: '南岸的西归浦更暖更慢：正房瀑布与天地渊瀑布在市区步行半径，每日偶来市场比东门市场更本地。',
      visit: {
        duration: '一天。',
        entry: '济州市乘 600 路机场巴士或急行巴士约一个多小时。',
        walk: '正房瀑布 → 西归浦港边 → 每日偶来市场。',
        return: '同线巴士返回；末班较早，下午就定回程。',
        stay: '可作第二基地；比济州市安静，去南线景点顺。',
        source: { label: 'Visit Jeju', url: 'https://www.visitjeju.net/' },
      },
    },
  ],
  dayTrips: [
    { direction: '汉拿山', how: '巴士到城板岳或观音寺登山口', worth: '韩国最高峰；白鹿潭登顶线需提前网上预约且有每日名额与天气管制，半山线（御里牧等）不需登顶许可。' },
    { direction: '牛岛', how: '城山港轮渡约 15 分钟', worth: '环岛半天到一天；受风浪影响停航常见，出发前查当日运行。' },
    { direction: '西线（涯月—翰林）', how: '巴士西向约一小时', worth: '海岸咖啡馆与透明小船；给喜欢看海坐住的人。' },
  ],
  dayTripNote: '汉拿山看天气与预约；牛岛看风浪；两条都去不了时西归浦与西线是好退路。',
  eatIntro:
    '济州的名物是黑猪肉与海产：烤黑猪肉当正餐，鲍鱼粥与海女海鲜当东岸内容，东门市场与偶来市场管白天的小吃。橘子与橘子咖啡是岛上甜品。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'black-pork', title: '烤黑猪肉',
      intro: '济州黑猪肉比半岛的更厚更香，按人份烤。老济州的「黑猪肉街」一整条都是。',
      restaurants: [
        {
          id: 'dombedon', name: '돔베돈（Dombedon）', nameEn: 'Dombedon', neighborhood: '老济州黑猪肉街',
          location: { address: '제주시 관덕로15길 25（黑猪肉街）', areaId: 'jeju-old-town', connection: '中央路／观德亭步行约5分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=돔베돈+제주' } },
          order: ['黑猪五花肉（흑돼지 오겹살）', '黑猪颈肉'],
          whyLinger: '黑猪肉街上最有名的店之一——厚切黑猪五花烤到焦边，配鳀鱼酱汤（멜조림）是济州式吃法。',
          practical: '按人份点（两人起点常见）；晚市等位。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=돔베돈+제주' }],
          queueNote: '饭点取号等位；黑猪肉街多家同等级店可换。',
        },
      ],
    },
    {
      id: 'seafood', title: '海鲜与鲍鱼',
      intro: '东岸与港边的海产店：鲍鱼粥、海产汤、烤带鱼是济州限定。',
      restaurants: [
        {
          id: 'myeongjin-jeonbok', name: '명진전복（明珍鲍鱼）', nameEn: 'Myeongjin Jeonbok', neighborhood: '城山方向（东岸）',
          location: { address: '제주시 구좌읍（东岸，往城山路上）', areaId: 'seongsan-east', connection: '东岸巴士沿线；去城山顺路', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=명진전복+제주' } },
          order: ['전복죽 鲍鱼粥', '전복돌솥밥 鲍鱼石锅饭', '烤鲍鱼'],
          whyLinger: '东岸最有名的鲍鱼专门店——粥里铺满鲍鱼片，是城山日出峰行程的顺路午餐。',
          practical: '店小等位长；开门时段或下午错峰。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=명진전복+제주' }],
        },
        {
          id: 'samseonghyeol-haemultang', name: '三姓穴海鲜汤', nameEn: 'Samseonghyeol Haemultang', neighborhood: '老济州',
          location: { address: '제주시 선덕로5길 20', areaId: 'jeju-old-town', connection: '三姓穴景点旁，老济州步行可达', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=삼성혈해물탕+제주' } },
          order: ['해물탕 海鲜汤（整章鱼下锅）', '鲍鱼加料'],
          whyLinger: '济州海鲜汤的代表店——整只活章鱼与鲍鱼下锅，两人起跳的正餐，老济州晚间内容。',
          practical: '两人起点；按人数配锅。饭点等位。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=삼성혈해물탕+제주' }],
        },
      ],
    },
    {
      id: 'market', title: '市场小吃',
      intro: '东门市场（济州市）与每日偶来市场（西归浦）是白天的吃处：现做小吃加水果摊。',
      restaurants: [
        {
          id: 'dongmun-market-stalls', name: '东门市场群', nameEn: 'Dongmun Market Stalls', neighborhood: '老济州',
          location: { address: '제주시 관덕로14길 20（东门传统市场）', areaId: 'jeju-old-town', connection: '观德亭步行约3分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=동문재래시장+제주' } },
          order: ['黑猪肉卷（흑돼지말이）', '橘子汁与橘子年糕', '紫菜包饭'],
          whyLinger: '济州最大的传统市场——夜市摊区晚上开，白天吃现做小吃与买橘子，是老济州散步的固定一站。',
          practical: '摊位现金与卡均可；夜市摊区傍晚起。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=동문재래시장+제주' }],
        },
      ],
    },
    {
      id: 'cafe', title: '海边咖啡与橘子',
      intro: '济州咖啡馆密度高，东岸与涯月的海景店是「看海坐住」的正经内容。',
      restaurants: [
        {
          id: 'cafe-delmoondo', name: 'Cafe Delmoondo 咸德', nameEn: 'Cafe Delmoondo Hamdeok', neighborhood: '咸德海边',
          location: { address: '제주시 조천읍 함덕리（咸德海水浴场旁）', areaId: 'seongsan-east', connection: '咸德海水浴场旁；东岸巴士到咸德站', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=카페델문도+함덕' } },
          order: ['冰美式＋花生拿铁（우도땅콩）', '烘焙'],
          whyLinger: '咸德海边平台咖啡馆——座位就在沙滩上方，东岸行程最顺的「坐住看海」点。',
          practical: '海景位先到先得；风浪大时露台关闭。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=카페델문도+함덕' }],
        },
      ],
    },
  ],
  howToOrder: [
    '烤黑猪肉按人份点，两人起点是常态；配菜免费续。',
    '海鲜汤两人一锅起；鲍鱼粥一人一份可当单人正餐。',
    '市场摊位指着吃；橘子按袋买可讲价。',
    '咖啡馆自助机点单普及；英文名或拍照取餐。',
  ],
  avoid: [
    '海产店先看活鱼池边的时价——「时价」店先问总价再点。',
    '牛岛与日出峰脚下的餐馆偏游客价；回市区吃。',
    '包车司机推荐的「熟人店」自己判断；先看菜单价。',
  ],
  eatRhythm:
    '早餐市场或鲍鱼粥；午餐按当天方向在东岸／南岸吃海产；下午海景咖啡馆；晚上老济州烤黑猪肉或海鲜汤。',
  allergies: [
    '海鲜汤与鲍鱼粥对甲壳类／贝类过敏者不友好；黑猪肉店是纯肉选择。',
    '鳀鱼酱（멜젓）常见于蘸料——鱼介过敏注意。',
    '济州橘子制品普遍，果酸过敏者留意甜品。',
  ],
  guide: {
    city: '济州岛',
    checkedAt: '2026-09-15',
    scope: '不自驾、以巴士＋出租车为主的首次济州行程；签证与入境规则单独核对',
    intro: '济州与半岛的规则不同：入境政策、岛内交通都要单独安排。以下按 3–4 晚、住济州市写。',
    topics: [
      {
        id: 'documents', title: '证件与入境', summary: '济州有独立的免签路径，但与半岛规则不同，按证件逐条核。', stage: 'before',
        recommendation: '济州岛对部分护照有「直飞济州免签」政策（限在济州停留、不得前往半岛本土）；中国大陆普通护照历史上适用该政策，但有被婉拒入境的案例，且经首尔等本土城市转机前往济州需要韩国签证。护照有效性、直航安排与最新政策都在 Hi Korea 或使领馆页面核实。',
        steps: [
          { title: '分清「直飞济州」与「经本土转机」', body: '免签政策通常只覆盖国际航班／客轮直达济州的路径；经仁川、金浦等本土机场转机属入境韩国本土，需签证。' },
          { title: '按本人证件核实当前政策', body: '免签适用范围与停留期按 Hi Korea／使领馆当前公告；政策可能随时调整。' },
          { title: '备齐行程证明材料', body: '返程机票订单、全程酒店订单、行程单离线保存——济州免签入境时边检可能要求出示。' },
          { title: '入境后确认停留期限与范围', body: '免签入境通常限济州岛范围，不能转往首尔等本土城市；按获准期限离境。' },
        ],
        done: '直航与免签路径已按证件核实；订单与行程材料离线可查。',
        fallback: '政策不清或需经本土转机时先办韩国签证，不要到机场再处理。',
        sources: [hikorea, kto, consular],
      },
      {
        id: 'mobile', title: '上网与手机', summary: '漫游、eSIM 或落地 SIM 三选一。', stage: 'before',
        recommendation: '国内运营商韩国漫游包最省事；流量需求大选 eSIM（先确认手机支持）或落地买游客 SIM。济州机场到达厅有运营商柜台。',
        steps: [
          { title: '查手机是否支持 eSIM', body: '国行手机多数不支持；按厂商说明确认后再下单。' },
          { title: '按天数比总价', body: '漫游包、eSIM、落地 SIM 按天数比较；留意计时起点。' },
          { title: '落地先测再离开柜台', body: '关 Wi-Fi 开地图发消息；济州信号在山区与海岸可能弱，离线地图先下。' },
        ],
        done: '离开 Wi-Fi 能开地图发消息；离线地图已下载。',
        fallback: '无网先连机场／便利店 Wi-Fi；备用漫游包应急。',
        sources: [kto],
      },
      {
        id: 'payment', title: '支付与交通卡', summary: '刷卡普及，T-money 管巴士，现金备市场。', stage: 'before',
        recommendation: '济州与半岛一样是刷卡社会；巴士用 T-money（上下车各刷一次）。市场小摊与海产店备现金。',
        steps: [
          { title: '确认银行卡境外功能', body: '开通境外刷卡；Visa／Mastercard 普及。' },
          { title: '落地买 T-money', body: '机场便利店可买可充；济州巴士长途按里程计价，上下车各刷一次。' },
          { title: '备小额现金', body: '市场摊与小店现金好用；机场与市区银行换钱透明。' },
        ],
        done: 'T-money 可用、银行卡能刷、备有现金。',
        fallback: '巴士可投现金但按里程计价麻烦，优先刷卡。',
        sources: [kto, { label: 'T-money', url: 'https://www.tmoney.co.kr/' }],
      },
      {
        id: 'stay', title: '住宿与入住', summary: '住济州市靠巴士枢纽，不自驾别住太偏。', stage: 'before',
        recommendation: '第一次来住老济州（东门市场／巴士总站附近）或新济州连洞；城山可加一晚看日出。不自驾的情况下，海边偏僻民宿意味着吃与行都受限，订前看步行可达的餐馆与巴士站。',
        steps: [
          { title: '按巴士线路选住处', body: '住处离巴士站步行 10 分钟内是硬条件；看站到济州市外巴士总站的线路。' },
          { title: '核对入住与寄存', body: '民宿多，确认晚到取钥匙方式与退房寄存。' },
          { title: '看餐饮半径', body: '地图数住处步行圈内餐馆——济州很多片区晚上没有选择。' },
        ],
        done: '住处巴士可达、餐饮半径确认、晚到方案清楚。',
        fallback: '位置太偏改订济州市区可取消的住处。',
        sources: [kto],
      },
      {
        id: 'arrival', title: '济州机场 → 酒店', summary: '机场就在市区边，巴士或出租车二十分钟。', stage: 'arrival',
        recommendation: '住老济州／新济州：机场巴士与市内线多条可达，出租车排队区按近远途分道。住西归浦：600 路机场巴士直达约一个多小时。深夜到达优先出租车。',
        choices: [
          { title: '巴士（济州市方向）', body: '到达层外巴士站；用 T-money 上下各刷一次。' },
          { title: '出租车', body: '按方向分近途（济州市）与远途（西归浦等）候车区；到市区车费低。' },
          { title: '600 路（西归浦方向）', body: '机场直达西归浦各酒店区；班次以现场为准。' },
        ],
        steps: [
          { title: '落地前存好路线', body: '巴士线号或出租车候车区截图；韩文酒店地址备好。' },
          { title: '到达厅一次办完小事', body: '便利店买 T-money、确认上网。' },
          { title: '按方向找候车区', body: '出租车近远途分排队；巴士按线号找站台。' },
        ],
        done: '到酒店，知道返程巴士站或叫车方式。',
        fallback: '深夜到达打正规出租车；Kakao T 需韩国账号，请酒店叫车更稳。',
        sources: [{ label: '济州国际机场', url: 'https://www.airport.co.kr/jeju/' }, kto],
      },
      {
        id: 'transit', title: '岛内交通', summary: '无轨道交通：巴士成网但间隔大，出租车补缝。', stage: 'during',
        recommendation: '济州巴士分干线（红色急行）、支线与观光循环线，T-money 通用；去东岸西归浦各约一到一个半小时。班次间隔 15–40 分钟常见，错过一班行程就乱——每天按班次表排。',
        steps: [
          { title: '按班次表排行程', body: '出发前查当天巴士时刻（NAVER 地图或 KakaoMap 比 Google 准）；把「错过这班怎么办」想好。' },
          { title: '长途上下各刷一次', body: '里程计价，下车忘刷按全程计。' },
          { title: '出租车补缝', body: '景点之间接驳用出租车；请店家或酒店叫车，路边拦车在海滨可行。' },
          { title: '别按自驾攻略走', body: '中国大陆驾照不能在韩国租车；电动自行车与摩托租赁对游客也有限制，别指望。' },
        ],
        done: '会用巴士网＋出租车组合、查过当天班次、有错过班次的备选。',
        fallback: '错过末班巴士请景点咨询台叫出租车；记酒店韩文地址。',
        sources: [kto, { label: 'Visit Jeju 交通', url: 'https://www.visitjeju.net/' }],
      },
    ],
    checklist: [
      { id: 'c-visa', text: '直飞济州免签路径与停留范围已按证件核实', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效；返程机票、全程酒店订单与行程单离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '上网方案已选定；离线地图已下载', topic: '上网与手机' },
      { id: 'c-tmoney', text: 'T-money 购买方式已确认', topic: '支付与交通卡' },
      { id: 'c-cash', text: '银行卡境外功能开通；备有小额现金', topic: '支付与交通卡' },
      { id: 'c-stay', text: '住处巴士可达、餐饮半径与晚到方案已确认', topic: '住宿与入住' },
      { id: 'c-arrival', text: '机场到住处的巴士线或出租车方案已截图', topic: '济州机场 → 酒店' },
      { id: 'c-bus', text: '东岸／西归浦当天班次与末班已查', topic: '岛内交通' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：济州市、东岸、西归浦各一天',
      note: '住济州市为基地。东岸赶早班巴士，西归浦算好末班。',
      days: [
        { day: '第一天', body: '抵达入住，东门市场与老济州走一圈，晚烤黑猪肉。', time: '按落地安排', start: 'CJU → 酒店', return: '老济州', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '早班巴士去城山日出峰 → 海女屋 → 涉地可支；回程顺路鲍鱼粥或咸德海边咖啡。', time: '全天东岸', start: '济州市外巴士总站', return: '济州市', links: [{ label: '城山与东岸', href: '?tab=places#area-seongsan-east' }] },
        { day: '第三天', body: '西归浦正房瀑布加每日偶来市场，下午回济州市按航班收尾。', time: '上午南岸、午后收尾', start: '600 路西归浦', return: '酒店 → 机场', links: [{ label: '看点', href: '?tab=places' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加汉拿山与西线',
      note: '3 晚骨架上加汉拿山一天（看天气与预约）与西线／留白一天。',
      days: [
        { day: '第一天', body: '抵达入住早睡，老济州散步。', time: '按落地安排', start: 'CJU → 酒店', return: '老济州', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '东岸一天：城山日出峰 + 涉地可支 + 海产。', time: '全天东岸', start: '巴士总站', return: '济州市', links: [{ label: '城山与东岸', href: '?tab=places#area-seongsan-east' }] },
        { day: '第三天', body: '汉拿山半山线或登顶线（按预约与天气）；不成行则换西归浦。', time: '全天山区', start: '登山口', return: '济州市', links: [{ label: '看点', href: '?tab=places' }] },
        { day: '第四天', body: '西线涯月海岸咖啡＋留白；或牛岛（看风浪）。', time: '半天海岸、半天留白', start: '涯月方向', return: '济州市', links: [{ label: '看点', href: '?tab=places' }] },
        { day: '第五天', body: '老济州补买橘子伴手礼，按航班去机场。', time: '上午收尾', start: '住处附近', return: '酒店 → 机场', links: [{ label: '老济州', href: '?tab=places#area-jeju-old-town' }] },
      ],
    },
  },
  safety: {
    city: '济州岛',
    checkedAt: '2026-09-15',
    emergencyNote: '济州治安好；主要风险是台风与大风导致的交通停摆、海岸风浪与登山意外。保存酒店韩文地址。',
    contacts: [
      { name: '报警', number: '112', dial: '112', use: '盗窃、纠纷、交通事故', source: { label: '韩国警察厅', url: 'https://www.police.go.kr/' }, urgent: true },
      { name: '急救 / 火灾', number: '119', dial: '119', use: '急救车与火警（有外语服务）', source: kto, urgent: true },
      { name: '旅游咨询热线', number: '1330', dial: '1330', use: '旅游问询与翻译协助', source: kto },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '护照与入境许可信息离线保存。',
      '保存酒店韩文地址与电话。',
      '境外医疗保险与救援电话另存。',
      '台风季（夏末秋初）关注航班与景点开放。',
      '登山带足水与防风层；汉拿山按管制走。',
    ],
    alerts: [
      { title: '台风与大风', body: '济州风大是常态；台风季航班与牛岛轮渡可能停航，行程留机动。', source: kto },
      { title: '海岸风浪', body: '海边岩石湿滑，风暴天不靠近礁石；海女表演与涉地可支步道受天气管制。', source: { label: 'Visit Jeju', url: 'https://www.visitjeju.net/' } },
      { title: '登山管制', body: '汉拿山登顶需预约且按天气开关；半山线也注意封山公告，穿登山鞋而非跑鞋。', source: kto },
      { title: '巴士末班早', body: '郊区线路末班早（下午五六点常见），错过只能出租车，行程按班次表排。', source: kto },
    ],
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['到最近派出所报失拿证明。', '联系中国驻济州总领事馆补办旅行证件（先预约）。', '保留报失证明理赔。', '免签入境者注意：补证与出境手续按使领馆指引。'], sources: [consular, { label: '中国驻济州总领事馆', url: 'http://jeju.china-consulate.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 119。', '非紧急请酒店推荐医院；济州市区医院集中。', '保留收据与诊断证明走保险。'], sources: [kto] },
      { id: 'safety-transport', title: '巴士误班或滞留', steps: ['查 NAVER 地图下一班与备选线路。', '请景点咨询台或店家叫出租车。', '记酒店韩文地址给司机看。'], sources: [kto] },
      { id: 'safety-weather', title: '台风天滞留', steps: ['联系航空公司改签或住宿续住。', '室内替代：博物馆、市场、咖啡馆。', '海边与山区行程取消，不硬闯。'], sources: [kto] },
    ],
  },
  relatedGuides: [
    '韩国国家页 → /places/south-korea',
    '首尔城市页 → /places/south-korea/seoul',
    '釜山城市页 → /places/south-korea/busan',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    '免签政策适用于直飞济州路径且有被拒入境个案，务必按证件与航班安排再核官方公告。',
    `官方入口：${city('jeju').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}

export const busan: CityContent = {
  city: city('busan'),
  checkedAt: '2026-09-15',
  meta: [
    { label: '最佳季节', value: '春秋最好；夏天是海滩季但湿热多台风尾，冬天海风冷。' },
    { label: '机场', value: '金海（PUS）在江西区，轻轨接地铁进城约一小时；釜山站有 KTX 直连首尔。' },
    { label: '建议停留', value: '2–3 晚。港区市集一天、海云台与海岸一天，山坡村落半天。' },
    { label: '地区标签', value: '东亚 · 港口城市' },
    { label: '气质', value: '鱼市、山坡村与海滩，比首尔松' },
    { label: '核实日期', value: '2026-09-15' },
  ],
  essentials: [
    {
      title: '机场 → 市区',
      body: '金海机场（PUS）乘轻轨到沙上站换地铁 2 号线进城；到西面约 40 分钟、南浦约一小时。深夜到达有机场巴士或出租车。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: '金海国际机场', url: 'https://www.airport.co.kr/gimhae/' }],
    },
    {
      title: '建议住哪',
      body: '按玩法选：要市集与老港住南浦／札嘎其一带；要海滩住海云台（离市区远，通勤 40 分钟）；要平衡住西面（地铁 1、2 号线交汇）。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '2 晚排南浦市集一天、海云台海岸一天；3 晚加甘川文化村或海东龙宫寺。釜山东西长，按海岸分段住别来回跑。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '釜山是山城与港口的合体：地铁线沿山谷与海岸铺开，南浦洞—札嘎其是老港市集面，海云台—广安里是东边的海滩面。慢旅行按海岸分段，不按清单跑。',
    '札嘎其鱼市与富平罐头市场管吃；甘川文化村在山坡上，半天走完；海云台海滩加冬柏岛是全天内容。',
    '海东龙宫寺在北边海岸、梵鱼寺在山里——两处都是「比市区远但值得」的半天项。',
    '釜山的吃围绕海产与猪肉汤饭：市场现切生鱼片、汤饭当早餐、烤肠一条街当晚上内容。',
  ],
  gettingThere: {
    intro: [
      '金海机场（PUS）：轻轨（釜山-金海轻电铁）到沙上站换地铁 2 号线；到西面约 40 分钟。机场巴士按片区选线。',
      'KTX 到釜山站（首尔出发约 2 小时 40 分）；釜山站地铁 1 号线接南浦与西面方向。',
      '市内地铁四条线加巴士；海岸景点（海东龙宫寺等）靠巴士或出租车接驳。',
    ],
    links: [
      { label: '金海国际机场', url: 'https://www.airport.co.kr/gimhae/' },
      { label: 'Visit Busan', url: 'https://www.visitbusan.net/' },
    ],
    verifyReminders: [
      '金海轻轨与地铁 2 号线换乘动线（沙上站）',
      '海云台蓝线海岸列车（Blue Line Park）当前票价与班次',
      '去海东龙宫寺的巴士线路与末班',
      '地铁末班约午夜前后',
    ],
  },
  neighborhoods: [
    {
      id: 'nampo-jagalchi',
      title: '南浦与札嘎其',
      suited: '要吃鱼市、罐头市场与老港氛围的人。',
      image: cityImages['busan-nampo'],
      body: '札嘎其市场是韩国最大鱼市，楼里现点现切；富平罐头市场白天是市场、晚上变夜市摊区。龙头山公园与釜山塔在旁边。',
      visit: {
        duration: '半天加一晚；夜市傍晚起。',
        entry: '地铁 1 号线札嘎其站或南浦站。',
        walk: '札嘎其市场 → 国际市场 → 富平罐头市场 → 龙头山公园。',
        return: '南浦站返回。',
        stay: '首选居住区之一；老港氛围浓，釜山站一站地铁。',
        source: { label: 'Visit Busan', url: 'https://www.visitbusan.net/' },
      },
    },
    {
      id: 'seomyeon',
      title: '西面',
      suited: '要交通中枢与本地餐馆密度的人。',
      image: cityImages['busan-seomyeon'],
      body: '西面是 1、2 号线交汇的商业中心：乐天百货与地下街之外，巷子里是汤饭店与烤肠街（西面乐天后巷）。',
      visit: {
        duration: '半天；主要是吃与换乘。',
        entry: '地铁西面站。',
        walk: '西面乐天一带 → 后巷餐馆群 → 田浦洞咖啡街方向。',
        return: '西面站返回。',
        stay: '交通最顺的居住区；去南浦与海云台都一条线。',
        source: { label: 'Visit Busan', url: 'https://www.visitbusan.net/' },
      },
    },
    {
      id: 'haeundae-dongbaek',
      title: '海云台与冬柏岛',
      suited: '想要海滩与海边步道的人。',
      image: cityImages['busan-haeundae'],
      body: '海云台是韩国最出名的海滩；冬柏岛（동백섬）环木栈道一圈看广安大桥。蓝线海岸列车沿海岸往北到松亭。',
      visit: {
        duration: '一天；海滩加冬柏岛环线。',
        entry: '地铁 2 号线海云台站。',
        walk: '海云台沙滩 → 冬柏岛木栈道环线 → 海边咖啡馆。',
        return: '海云台站或蓝线列车返回。',
        stay: '海滩度假型住处；离市区远，按「住海边」而非「住市区」决策。',
        source: { label: 'Visit Busan', url: 'https://www.visitbusan.net/' },
      },
    },
    {
      id: 'gwangalli',
      title: '广安里',
      suited: '想看广安大桥夜景与更本地海滩的人。',
      image: cityImages['busan-gwangalli'],
      body: '广安里海滩正对广安大桥，夜景是釜山名片；民乐洞一侧的咖啡馆与生鱼片店比海云台本地。',
      visit: {
        duration: '半天到一晚；黄昏加夜景最好。',
        entry: '地铁 2 号线广安站步行约 10 分钟。',
        walk: '广安里沙滩 → 民乐洞咖啡街 → 夜景看桥。',
        return: '广安站或金莲山站返回。',
        stay: '比海云台便宜的看海选项；夜里热闹。',
        source: { label: 'Visit Busan', url: 'https://www.visitbusan.net/' },
      },
    },
    {
      id: 'gamcheon',
      title: '甘川文化村与山坡',
      suited: '想看山坡村落与巷弄壁画的人。',
      image: cityImages['busan-gamcheon'],
      body: '甘川文化村是沿山坡建的彩色村落，原先是难民聚落。坡道陡、台阶多，小巴上山再慢慢走下来。',
      visit: {
        duration: '半天。',
        entry: '地铁 1 号线土城站换小巴上山。',
        walk: '村口展望台 → 主街 → 巷弄下行（岔路多，按主路走）。',
        return: '山脚小巴回土城站。',
        stay: '不作居住建议；当半天行程。',
        source: { label: 'Visit Busan', url: 'https://www.visitbusan.net/' },
      },
    },
  ],
  dayTrips: [
    { direction: '海东龙宫寺', how: '海云台换巴士约 30 分钟', worth: '海边崖上的寺院，韩国少有的临海寺；半天，早上人少。' },
    { direction: '梵鱼寺', how: '地铁 1 号线梵鱼寺站换巴士', worth: '山里的大寺，秋天枫叶好；半天。' },
    { direction: '机张海岸', how: '东海线列车约 40 分钟', worth: '更北的本地海岸与烤蛤蜊村；给多一天的人。' },
  ],
  dayTripNote: '海东龙宫寺与海云台同向最顺；梵鱼寺是山里方向，别与海岸排同一天。',
  eatIntro:
    '釜山的底色是海产与猪肉汤饭：札嘎其现切生鱼片、富平夜市小吃、西面烤肠与汤饭店。比首尔便宜，比首尔咸鲜。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'gukbap', title: '猪肉汤饭',
      intro: '猪肉汤饭（돼지국밥）是釜山的灵魂食物：白汤肉饭自加盐虾酱，早餐到深夜都有。',
      restaurants: [
        {
          id: 'songjeong-gukbap', name: '松亭三代汤饭', nameEn: 'Songjeong 3-dae Gukbap', neighborhood: '西面／釜山镇',
          location: { address: '부산 부산진구 서면로68번길 29', areaId: 'seomyeon', connection: '西面站步行约10分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=송정3대국밥+부산' } },
          order: ['猪肉汤饭（돼지국밥）', '白切肉（수육）加盘'],
          whyLinger: '三代传下来的汤饭老店——白汤自调味（盐、虾酱、韭菜），是理解釜山味道的第一碗。',
          practical: '开业早，早餐顺路；小菜与调味自助。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=송정3대국밥+부산' }],
        },
        {
          id: 'ssangdungi-gukbap', name: '双胞胎猪肉汤饭', nameEn: 'Ssangdungi Dwaeji Gukbap', neighborhood: '西面',
          location: { address: '부산 부산진구（西面本店）', areaId: 'seomyeon', connection: '西面站步行可达', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=쌍둥이돼지국밥+부산' } },
          order: ['猪肉汤饭', '内脏汤饭（내장국밥）'],
          whyLinger: '西面最有名的汤饭店之一——分量大、肉多，本地人与游客混坐的深夜食堂。',
          practical: '营业到深夜（以门店为准）；一人一碗是常态。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=쌍둥이돼지국밥+부산' }],
        },
      ],
    },
    {
      id: 'seafood-market', title: '札嘎其市场',
      intro: '一楼挑鱼、二楼代客料理：生鱼片拼盘、烤鳗鱼、海鲜锅。问清代收料理费再下单。',
      restaurants: [
        {
          id: 'jagalchi-market-hall', name: '札嘎其市场食堂区', nameEn: 'Jagalchi Market', neighborhood: '札嘎其',
          location: { address: '부산 중구 자갈치해안로 52（札嘎其市场）', areaId: 'nampo-jagalchi', connection: '地铁札嘎其站10号口步行约2分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=자갈치시장+부산' } },
          order: ['生鱼片拼盘（회）', '烤鳗鱼（장어구이）', '海鲜锅'],
          whyLinger: '韩国最大鱼市——楼下选鱼楼上吃，问清代料理费；不指名单摊，看水箱鲜活度与明码价。',
          practical: '先谈总价再坐下；卡与现金均可但现金好讲价。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=자갈치시장+부산' }],
        },
      ],
    },
    {
      id: 'night-market', title: '富平罐头市场与夜市',
      intro: '白天是传统市场，晚上摊区变身夜市：饺子、糖饼、烤肉串边走边吃。',
      restaurants: [
        {
          id: 'bupyeong-night-stalls', name: '富平罐头市场夜市', nameEn: 'Bupyeong Night Market', neighborhood: '南浦／富平',
          location: { address: '부산 중구 부평1길（富平市场内摊区）', areaId: 'nampo-jagalchi', connection: '札嘎其站或南浦站步行可达', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=부평깡통시장' } },
          order: ['糖饼（씨앗호떡 坚果糖饼）', '饺子·烤肉串', '鱼糕串'],
          whyLinger: '「罐头市场」的夜市摊区是釜山夜间散步的固定内容——比札嘎其便宜随意，甜咸都有。',
          practical: '摊区傍晚起；现金与简单电子付。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=부평깡통시장' }],
        },
      ],
    },
    {
      id: 'cafe', title: '海边咖啡',
      intro: '广安里与海云台的看海咖啡馆是釜山下午的正经安排。',
      restaurants: [
        {
          id: 'momos-oncheoncheon', name: 'Momos Coffee 温泉场', nameEn: 'Momos Coffee', neighborhood: '温泉川（온천천）',
          location: { address: '부산 부산진구 온천천시민공원旁', areaId: 'seomyeon', connection: '温泉场站一带；从西面可打车', source: { label: '官网', url: 'https://www.momos.co.kr/' } },
          order: ['手冲单品', '拿铁'],
          whyLinger: '釜山起家、世界咖啡师大赛冠军店——仓库改造的烘焙空间，本地咖啡地标。',
          practical: '空间大可久坐；伴手礼豆可带走。',
          verifiedAt: '2026-09-15',
          sources: [{ label: '官网', url: 'https://www.momos.co.kr/' }],
        },
      ],
    },
  ],
  howToOrder: [
    '汤饭先上原汤，桌边盐、虾酱、韭菜自己加。',
    '札嘎其先问「代料理费」与总价再坐；水箱挑鱼可以指。',
    '夜市摊指着吃；鱼糕串按串计费。',
    '一人食汤饭最顺；生鱼片与海鲜锅两人起跳。',
  ],
  avoid: [
    '札嘎其「时价」海鲜先问总价；不写价的店不进。',
    '海云台沙滩边主街餐馆偏游客价；巷子里找本地店。',
    '甘川村里餐厅少价高；回南浦或西面吃。',
  ],
  eatRhythm:
    '早餐汤饭；午餐市场生鱼片或夜市摊；下午看海咖啡；晚上烤肠或海鲜锅。海云台住的话留一顿给民乐洞生鱼片巷。',
  allergies: [
    '虾酱（새우젓）是汤饭标配调味——甲壳类过敏跳过。',
    '生鱼片与海鲜锅对海鲜过敏者不友好；汤饭是纯猪牛选择。',
    '夜市摊共用操作台，交叉污染难免。',
  ],
  guide: {
    city: '釜山',
    checkedAt: '2026-09-15',
    scope: '以公共交通为主的首次釜山行程；签证与入境按本人证件另核官方要求',
    intro: '先把入境资格、网络、交通卡与住处安排好。以下按 2–3 晚、住南浦或西面写。',
    topics: [
      {
        id: 'documents', title: '证件与入境', summary: '签证／K-ETA 按护照核对；直飞釜山与经首尔转机规则不同。', stage: 'before',
        recommendation: '韩国对部分护照免签但需事先办 K-ETA；中国大陆护照通常需签证。直飞釜山金海机场与经首尔转机入境都按「入境韩国」规则办，在 Hi Korea 或就近使领馆按本人证件核实，以官方当前公告为准。',
        steps: [
          { title: '先按护照查签证路径', body: 'Hi Korea 或韩国使领馆按国籍查：需签证、免签但需 K-ETA、或完全免签是三种不同路径。' },
          { title: '需要 K-ETA 的提前在线办', body: '官方网站申请（辨别仿冒收费网站），批准后与护照关联；出发前确认仍在有效期。' },
          { title: '材料放一起', body: '返程订单、首晚酒店名称地址、同行人联系方式离线保存。' },
          { title: '入境后核对停留期', body: '按现场通道办理，按获准期限离境。' },
        ],
        done: '入境路径已按证件核实；K-ETA 或签证材料齐备。',
        fallback: '签证问题先联系官方渠道，不要到机场再处理。',
        sources: [hikorea, keta, consular],
      },
      {
        id: 'mobile', title: '上网与手机', summary: '漫游、eSIM 或落地 SIM 三选一。', stage: 'before',
        recommendation: '国内运营商韩国漫游包最省事；流量需求大选 eSIM（先确认手机支持）或落地买游客 SIM。金海机场到达厅有运营商柜台。',
        steps: [
          { title: '查手机是否支持 eSIM', body: '国行手机多数不支持；按厂商说明确认。' },
          { title: '按天数比总价', body: '漫游包、eSIM、落地 SIM 按天数比较。' },
          { title: '落地先测再离开柜台', body: '关 Wi-Fi 开地图发消息；当地卡关闭国内卡数据漫游。' },
        ],
        done: '离开 Wi-Fi 能开地图发消息。',
        fallback: '无网先连机场 Wi-Fi；备用漫游包应急。',
        sources: [kto],
      },
      {
        id: 'payment', title: '支付与交通卡', summary: '刷卡普及，T-money 管交通，现金备市场。', stage: 'before',
        recommendation: '釜山与首尔一样是刷卡社会；地铁巴士用 T-money，市场小摊备现金。',
        steps: [
          { title: '确认银行卡境外功能', body: '开通境外刷卡；Visa／Mastercard 普及。' },
          { title: '落地买 T-money', body: '机场便利店或地铁站可买可充；巴士上下各刷一次。' },
          { title: '备小额现金', body: '鱼市与小摊现金好用好讲价；正规换钱所汇率透明。' },
        ],
        done: 'T-money 可用、银行卡能刷、备有现金。',
        fallback: '卡刷不过用现金；T-money 余额便利店退（按规则）。',
        sources: [kto, { label: 'T-money', url: 'https://www.tmoney.co.kr/' }],
      },
      {
        id: 'stay', title: '住宿与入住', summary: '南浦吃市集、西面当枢纽、海云台住海边——先选玩法再选区。', stage: 'before',
        recommendation: '要市集与老港住南浦／札嘎其；要交通平衡住西面（地铁交汇）；要海滩住海云台但接受离市区远。釜山东西向长，住一头跑另一头是浪费行程。',
        steps: [
          { title: '按玩法圈片区', body: '主要吃与市场选南浦；要海滩度假选海云台；都想要选西面折中。' },
          { title: '核对入住与寄存', body: '韩国入住普遍 15:00 后；寄存与晚到先问。' },
          { title: '确认总价与押金', body: '看付款页含税总价；民宿确认取钥匙方式。' },
        ],
        done: '片区按玩法选定、入住与晚到方案清楚。',
        fallback: '规则不清改订可取消住处。',
        sources: [kto],
      },
      {
        id: 'arrival', title: '金海机场 → 酒店', summary: '轻轨到沙上换地铁；深夜机场巴士或出租车。', stage: 'arrival',
        recommendation: '住西面／南浦：金海轻轨到沙上站换地铁 2 号线（西面直达）。住海云台：机场巴士直达海云台方向更顺，或轻轨换地铁到底。深夜到达用机场巴士或正规出租车。',
        choices: [
          { title: '轻轨 + 地铁', body: '金海轻轨到沙上站换 2 号线；T-money 一刷到底，到西面约 40 分钟。' },
          { title: '机场巴士', body: '按片区分线（西面／南浦／海云台方向）；深夜班次以现场为准。' },
          { title: '出租车', body: '到西面约 30 分钟；远途到海云台贵但直达。' },
        ],
        steps: [
          { title: '落地前存好整条路线', body: '交通方式、换乘站、末班时间截图。' },
          { title: '到达厅一次办完小事', body: '便利店买 T-money、确认上网。' },
          { title: '轻轨在航站楼外', body: '按标识出站乘轻轨；沙上站同站换 2 号线。' },
        ],
        done: '到酒店，知道返程在哪个站上车。',
        fallback: '深夜到达用机场巴士或正规出租车。',
        sources: [{ label: '金海国际机场', url: 'https://www.airport.co.kr/gimhae/' }, kto],
      },
      {
        id: 'transit', title: '市内交通', summary: '地铁四条线覆盖主要片区，海岸景点靠巴士补。', stage: 'during',
        recommendation: '地铁 1 号线串釜山站—南浦—西面，2 号线去西面—广安—海云台。甘川文化村小巴接驳，海东龙宫寺靠巴士；蓝线海岸列车是海云台—松亭的海岸观光车。',
        steps: [
          { title: '记两条主线', body: '1 号线管老城港，2 号线管新城与海云台；西面是换乘中心。' },
          { title: '海岸段用巴士或蓝线', body: '海东龙宫寺等海岸点地铁不到，查巴士班次；蓝线列车按段购票或通票。' },
          { title: '末班约午夜', body: '深夜出租车可用；海云台回南浦车程长，算末班。' },
          { title: '坡道与小巴', body: '甘川等山坡点换小巴；穿舒适的鞋。' },
        ],
        done: '会用地铁两主线、查过海岸巴士与末班。',
        fallback: '迷路回最近地铁站；出租车亮空车灯才停。',
        sources: [kto, { label: 'Visit Busan 交通', url: 'https://www.visitbusan.net/' }],
      },
    ],
    checklist: [
      { id: 'c-visa', text: '签证／K-ETA 路径已按本人证件核实', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效期覆盖行程；订单离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '上网方案已选定并有备用', topic: '上网与手机' },
      { id: 'c-tmoney', text: 'T-money 购买方式已确认', topic: '支付与交通卡' },
      { id: 'c-cash', text: '银行卡境外功能开通；备有小额现金', topic: '支付与交通卡' },
      { id: 'c-stay', text: '片区已按玩法选定；晚到方案已确认', topic: '住宿与入住' },
      { id: 'c-arrival', text: '轻轨／巴士路线与下车站已截图', topic: '金海机场 → 酒店' },
      { id: 'c-coast', text: '海岸巴士班次与地铁末班已查', topic: '市内交通' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：市集一天，海岸一天',
      note: '住南浦或西面。市集日走港区，海岸日走海云台。',
      days: [
        { day: '第一天', body: '抵达入住，南浦／住处附近晚饭。', time: '按落地安排', start: 'PUS → 酒店', return: '南浦', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '札嘎其市场早餐 → 国际市场 → 甘川文化村下午 → 富平夜市晚饭。', time: '上午市场、下午山坡', start: '札嘎其', return: '富平夜市', links: [{ label: '南浦与札嘎其', href: '?tab=places#area-nampo-jagalchi' }] },
        { day: '第三天', body: '海云台海滩加冬柏岛环线，按航班或 KTX 收尾。', time: '上午海岸、午后收尾', start: '海云台', return: '酒店 → 机场／车站', links: [{ label: '看点', href: '?tab=places' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加寺与广安里',
      note: '3 晚骨架上加海东龙宫寺半天与广安里一晚。',
      days: [
        { day: '第一天', body: '抵达入住早睡。', time: '按落地安排', start: 'PUS → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '札嘎其＋甘川文化村＋富平夜市。', time: '全天', start: '札嘎其', return: '南浦', links: [{ label: '甘川文化村与山坡', href: '?tab=places#area-gamcheon' }] },
        { day: '第三天', body: '海东龙宫寺半天 → 海云台海滩黄昏。', time: '上午寺、下午海', start: '海东龙宫寺', return: '海云台', links: [{ label: '看点', href: '?tab=places' }] },
        { day: '第四天', body: '冬柏岛环线 → 广安里海滩与夜景；或留白。', time: '全天海岸', start: '海云台', return: '广安里', links: [{ label: '广安里', href: '?tab=places#area-gwangalli' }] },
        { day: '第五天', body: '西面补买或汤饭收尾，按航班／KTX 离开。', time: '上午收尾', start: '西面', return: '酒店 → 机场／车站', links: [{ label: '西面', href: '?tab=places#area-seomyeon' }] },
      ],
    },
  },
  safety: {
    city: '釜山',
    checkedAt: '2026-09-15',
    emergencyNote: '釜山治安好；留意鱼市时价纠纷、海岸风浪与山坡台阶。保存酒店韩文地址。',
    contacts: [
      { name: '报警', number: '112', dial: '112', use: '盗窃、纠纷、交通事故', source: { label: '韩国警察厅', url: 'https://www.police.go.kr/' }, urgent: true },
      { name: '急救 / 火灾', number: '119', dial: '119', use: '急救车与火警（有外语服务）', source: kto, urgent: true },
      { name: '旅游咨询热线', number: '1330', dial: '1330', use: '旅游问询与翻译协助', source: kto },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '护照与入境许可信息离线保存。',
      '保存酒店韩文地址与电话。',
      '境外医疗保险与救援电话另存。',
      '夏季台风尾影响海岸与航班，关注天气。',
      '山坡村落台阶多，穿防滑鞋。',
    ],
    alerts: [
      { title: '台风与海浪', body: '夏末秋初台风尾扫釜山；海云台浪大时禁下水，看旗语与广播。', source: kto },
      { title: '鱼市时价', body: '札嘎其与海产生鱼片店先问总价与代料理费再坐；不写价的谨慎。', source: { label: 'Visit Busan', url: 'https://www.visitbusan.net/' } },
      { title: '山坡与台阶', body: '甘川等坡道村落台阶陡、雨天滑；行李别带，慢慢走。', source: kto },
      { title: '末班与深夜', body: '海云台回市区地铁末班约午夜；错过出租车车程长费高。', source: kto },
    ],
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['到最近派出所报失拿证明。', '联系中国驻釜山总领事馆补办旅行证件（先预约）。', '保留报失证明理赔。', '确认新证件出入境可用再改签。'], sources: [consular, { label: '中国驻釜山总领事馆', url: 'http://busan.china-consulate.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 119。', '非紧急请酒店推荐医院；西面与南浦医院集中。', '保留收据与诊断证明走保险。'], sources: [kto] },
      { id: 'safety-fraud', title: '海鲜账单纠纷', steps: ['下单前先拍价目与确认代料理费。', '争议先拍照留证再交涉。', '纠纷升级拨 112 或 1330 求助。'], sources: [kto] },
      { id: 'safety-transport', title: '错过末班或迷路', steps: ['回最近地铁站闸口看地图。', '深夜正规出租车；记酒店韩文地址。', '手机没电找便利店求助。'], sources: [kto] },
    ],
  },
  relatedGuides: [
    '韩国国家页 → /places/south-korea',
    '首尔城市页 → /places/south-korea/seoul',
    '济州岛城市页 → /places/south-korea/jeju',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('busan').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}
