import type { CityContent } from './types'
import { EAT_CRITERIA, EAT_EXCLUDE, HELP_PHRASES, consularHotline, consularUse } from './shared'
import { cityImages } from './photoData'
import { CONTENT_CITIES } from '../directory'

const city = (slug: string) => {
  const c = CONTENT_CITIES.find((x) => x.slug === slug)
  if (!c) throw new Error(`missing directory city: ${slug}`)
  return c
}

const stb = { label: '新加坡旅游局', url: 'https://www.visitsingapore.com/' }
const ica = { label: '新加坡移民与关卡局 ICA', url: 'https://www.ica.gov.sg/' }
const sgaCard = { label: 'SG Arrival Card', url: 'https://eservices.ica.gov.sg/sgarrivalcard/' }
const consular = { label: '中国领事服务网', url: 'https://cs.mfa.gov.cn/' }
const macauTourism = { label: '澳门旅游局', url: 'https://www.macaotourism.gov.mo/' }
const macauPolice = { label: '澳门治安警察局', url: 'https://www.fsm.gov.mo/' }

export const singapore: CityContent = {
  city: city('singapore'),
  checkedAt: '2026-09-14',
  meta: [
    { label: '最佳季节', value: '全年炎热多雨；11–1 月雨更多，2–4 月相对干爽。随时备雨具。' },
    { label: '机场', value: '樟宜（SIN）本身就是景点；地铁 EW 线进城约 30–40 分钟。' },
    { label: '建议停留', value: '3–4 晚。城市小、轨道密；食阁、街区与滨海湾各留半天。' },
    { label: '地区标签', value: '东南亚 · 城市国家' },
    { label: '气质', value: '秩序感与食阁烟火并存的热带城市' },
    { label: '核实日期', value: '2026-09-14' },
  ],
  essentials: [
    {
      title: '机场 → 市区',
      body: '樟宜机场（SIN）进城：地铁东西线（EW）到市区约 30–40 分钟最稳；Grab 与出租车按路程。樟宜本身是景点——Jewel 的雨漩涡值得留一小时。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: '樟宜机场', url: 'https://www.changiairport.com/' }],
    },
    {
      title: '建议住哪',
      body: '住地铁沿线：武吉士—政府大厦一带居中，牛车水（Chinatown）吃饭最顺，或滨海湾方向。城市小，住哪都不远，选轨道近的。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '3 晚排滨海湾半天、街区（牛车水／小印度／甘榜格南）一天、食阁与留白；4 晚加圣淘沙或动物园。每天一个方向加一顿食阁。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '新加坡小、轨道密、秩序强——慢旅行的做法是每天一个方向加一顿食阁，别排满。地铁（MRT）覆盖全城，EZ-Link 卡一卡到底。',
    '牛车水、小印度、甘榜格南是三个族裔的街区，各半天；滨海湾金沙与花园是地标半天；食阁（hawker centre）是每天的饭。',
    '这座城的贵是真实存在的：住宿与酒贵，食阁与轨道便宜。预算分配往「住与吃」倾斜，景点大多免费或低价。',
    '别把新加坡当「转机顺路」——它值得三晚，食阁一项就值回。',
  ],
  gettingThere: {
    intro: [
      '樟宜（SIN）：地铁 EW 线到市区约 30–40 分钟最稳；Grab 与出租车按路程。机场与市区间有免费巴士到部分酒店（按官网）。',
      '市内靠 MRT 加 EZ-Link 卡（或 SimplyGo 用银行卡直接刷），覆盖全城。巴士与 Grab 补充；步行在有顶棚连廊多。',
      '去圣淘沙：地铁到 HarbourFront 再换 Sentosa Express 或缆车；去动物园地铁＋接驳巴士。',
    ],
    links: [
      { label: 'EZ-Link', url: 'https://www.ezlink.com.sg/' },
      { label: 'SMRT 地铁', url: 'https://www.smrt.com.sg/' },
    ],
    verifyReminders: [
      'SG Arrival Card 的填写时限（入境前三天内）',
      'EZ-Link 与 SimplyGo（银行卡直接刷）的当前规则',
      '滨海湾花园花穹与云雾林的当前票价',
      '食阁与景点的营业时间',
    ],
  },
  neighborhoods: [
    {
      id: 'chinatown',
      title: '牛车水',
      suited: '想吃好、看华埠历史的人。',
      image: cityImages['sg-chinatown'],
      body: '新加坡华埠：佛牙寺、麦士威食阁、老店屋与中药行。麦士威食阁的天天海南鸡饭是地标；上午走庙，下午食阁。',
      visit: {
        duration: '半天到一天。',
        entry: 'MRT Chinatown 站。',
        walk: '佛牙寺 → 麦士威食阁 → 老店屋巷内乱走。',
        return: 'MRT 回；食阁晚市收得早，赶早。',
        stay: '首选居住区之一；吃喝最集中。',
        source: stb,
      },
    },
    {
      id: 'little-india',
      title: '小印度',
      suited: '想看印度街区与庙的人。',
      image: cityImages['sg-little-india'],
      body: '小印度是花环、香料与印度庙的街区；慕斯达发中心 24 小时营业什么都有。周末晚上人多，上午去最舒服。',
      visit: {
        duration: '半天。',
        entry: 'MRT Little India 站。',
        walk: '维拉玛卡里雅曼庙 → 实龙岗路主街 → 慕斯达发方向。',
        return: 'MRT 回；周末晚人多看好随身物。',
        stay: '不建议住这一带（人多吵）；半天拜访。',
        source: stb,
      },
    },
    {
      id: 'kampong-glam',
      title: '甘榜格南',
      suited: '想看马来区、苏丹回教堂与哈芝巷的人。',
      image: cityImages['sg-kampong-glam'],
      body: '甘榜格南是马来与阿拉伯街区：苏丹回教堂金色圆顶、哈芝巷（Haji Lane）的小店与咖啡馆。半天够，适合与小印度同日或分开。',
      visit: {
        duration: '半天。',
        entry: 'MRT Bugis 站步行。',
        walk: '苏丹回教堂 → 哈芝巷 → 阿拉伯街布料店。',
        return: 'Bugis 站回；哈芝巷小店下午开。',
        stay: '不住这一带；半天拜访。',
        source: stb,
      },
    },
    {
      id: 'marina-bay',
      title: '滨海湾与金沙',
      suited: '想看地标与花园的人。',
      image: cityImages['sg-marina-bay'],
      body: '滨海湾金沙、滨海湾花园（花穹＋云雾林）、鱼尾狮公园在一圈里。黄昏看金沙亮灯与超级树灯光秀；白天热，室内馆躲太阳。',
      visit: {
        duration: '半天（黄昏最好）。',
        entry: 'MRT Bayfront 站。',
        walk: '鱼尾狮 → 金沙商场 → 滨海湾花园超级树。',
        return: 'MRT 回；超级树灯光秀按官网时间。',
        stay: '金沙酒店贵；看景不必住景里。',
        source: stb,
      },
    },
  ],
  dayTrips: [
    { direction: '新山（马来西亚）', how: '跨境巴士／火车过关约 1–1.5 小时', worth: '最近的一日游跨国；过关排队久，行程松才去。' },
    { direction: '巴淡岛（印尼）', how: '渡轮约一小时', worth: '免税购物与海岛；要办印尼签证／落地签，先查。' },
    { direction: '乌敏岛', how: '地铁＋渡轮约一个半小时', worth: '新加坡仅存的乡村岛，骑车看红树林；半天到一天。' },
  ],
  dayTripNote: '新山与巴淡岛要过关，行程松才排；乌敏岛是新加坡内部的安静一日。',
  eatIntro:
    '新加坡的吃在食阁：hawker centre 是这座城的食堂，海南鸡饭、叻沙、炒粿条、肉骨茶各占一摊。一天两顿食阁不为过。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'hawker', title: '食阁（Hawker Centre）',
      intro: '麦士威、老巴刹、牛车水大厦食阁是城市食堂：便宜、多样。找排队长的摊通常不差，先占位再点单。',
      restaurants: [
        {
          id: 'tian-tian', name: '天天海南鸡饭', nameEn: 'Tian Tian Hainanese Chicken Rice', neighborhood: '牛车水（麦士威食阁）',
          location: { address: 'Maxwell Food Centre, 1 Kadayanallur St（摊位 #01-10/11）', areaId: 'chinatown', connection: 'MRT Chinatown／Maxwell 站步行可达', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Tian+Tian+Hainanese+Chicken+Rice' } },
          order: ['海南鸡饭（分白鸡／烧鸡）'],
          whyLinger: '全城最出名的一碟鸡饭——排队是常态，但麦士威整层都值得吃，把它当起点而非全部。',
          practical: '早午市最好；摊位现金或刷卡以现场为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Tian+Tian+Hainanese+Chicken+Rice' }],
          queueNote: '午市排长队；早去或接受等候，同层其他摊一样好吃。',
        },
        {
          id: 'lao-ban', name: '老伴豆花', nameEn: 'Lao Ban Soya Beancurd', neighborhood: '牛车水（麦士威食阁）',
          location: { address: 'Maxwell Food Centre 摊位（按场内指引）', areaId: 'chinatown', connection: '同麦士威食阁', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Lao+Ban+Soya+Beancurd+Maxwell' } },
          order: ['原味豆花（冷热均可）'],
          whyLinger: '鸡饭之后的甜点答案——滑嫩豆花，一份正好收尾。',
          practical: '午市到下午；售完即止。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Lao+Ban+Soya+Beancurd+Maxwell' }],
        },
      ],
    },
    {
      id: 'chicken-rice', title: '海南鸡饭',
      intro: '国菜：白斩鸡配油饭、姜蓉与辣椒酱。天天最出名，但街坊店的往往一样好。',
      restaurants: [
        {
          id: 'boon-tong-kee', name: '文东记', nameEn: 'Boon Tong Kee', neighborhood: 'Balestier（多家分店）',
          location: { address: '399/401/403 Balestier Rd（总店）', connection: 'Grab 或巴士自市区约15分钟', source: { label: '官网', url: 'https://www.boontongkee.com.sg/' } },
          order: ['白切鸡饭', '脆皮豆腐等家常菜'],
          whyLinger: '从街边摊做到连锁的鸡饭名店——总店在马里士他，宵夜时段也开，适合不想排队吃天天的替代。',
          practical: '营业到深夜（以官网为准）；多家分店。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.boontongkee.com.sg/' }],
        },
        {
          id: 'tiong-bahru-chicken-rice', name: '中峇鲁海南无骨鸡饭', nameEn: 'Tiong Bahru Hainanese Boneless Chicken Rice', neighborhood: '中峇鲁',
          location: { address: 'Tiong Bahru Market 食阁内, 30 Seng Poh Rd', connection: 'MRT Tiong Bahru 站步行约10分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Tiong+Bahru+Chicken+Rice' } },
          order: ['无骨鸡饭', '鸡杂或例汤'],
          whyLinger: '中峇鲁巴刹楼上的老摊——无骨鸡饭配姜蓉辣酱，街坊价，顺路逛中峇鲁老街区。',
          practical: '早午市；现金为主。食阁内先占位。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Tiong+Bahru+Chicken+Rice' }],
        },
        {
          id: 'hawker-chan', name: '了凡香港油鸡饭面', nameEn: 'Hawker Chan', neighborhood: '牛车水大厦食阁',
          location: { address: 'Chinatown Complex Food Centre 摊位, 335 Smith St', areaId: 'chinatown', connection: 'MRT Chinatown 站步行约5分钟', source: { label: '官网', url: 'https://www.hawkerchan.com/' } },
          order: ['油鸡饭', '油鸡面'],
          whyLinger: '史上第一颗米其林星的街头摊——香港油鸡饭的档口版。与天天并列的「朝圣店」，两家吃哪边见仁见智。',
          practical: '午市到傍晚；排队点餐。多家分店，总摊在牛车水大厦。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.hawkerchan.com/' }],
          queueNote: '饭点排队；分店（如 Smith St 门店）分流更快。',
        },
      ],
    },
    {
      id: 'laksa', title: '叻沙与娘惹餐',
      intro: '椰浆咖喱汤面是娘惹菜的代表；加东方向有老店。辣中带椰香，与泰式咖喱不同路数。',
      restaurants: [
        {
          id: 'katong-laksa-328', name: '328 加东叻沙', nameEn: '328 Katong Laksa', neighborhood: '加东（Katong）',
          location: { address: '216 East Coast Rd', connection: '巴士自市区约20–30分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=328+Katong+Laksa' } },
          order: ['叻沙（配勺，不用筷子）', 'Otah 乌打'],
          whyLinger: '加东叻沙的名店——汤底椰香浓、面条剪短只用勺吃。顺路逛加东娘惹店屋。',
          practical: '早到傍晚；现金与卡以现场为准。多家分店。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=328+Katong+Laksa' }],
        },
        {
          id: 'sungei-road-laksa', name: '结霜桥叻沙', nameEn: 'Sungei Road Laksa', neighborhood: 'Jalan Berseh（小印度旁）',
          location: { address: '27 Jalan Berseh #01-100', areaId: 'little-india', connection: 'MRT Jalan Besar／Little India 站步行可达', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Sungei+Road+Laksa' } },
          order: ['叻沙（炭炉汤底）'],
          whyLinger: '还在用炭炉熬汤的老摊——与加东派不同路数，汤更清但香。小印度散步顺路。',
          practical: '早午市为主；现金。座位少。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Sungei+Road+Laksa' }],
        },
      ],
    },
    {
      id: 'bak-kut-teh', title: '肉骨茶',
      intro: '新加坡肉骨茶是白胡椒清汤派（与马来西亚药材派不同）；配油条与饭，汤可免费续。',
      restaurants: [
        {
          id: 'song-fa', name: '松发肉骨茶', nameEn: 'Song Fa Bak Kut Teh', neighborhood: '新桥路（牛车水）',
          location: { address: '11 New Bridge Rd #01-01', areaId: 'chinatown', connection: 'MRT Clarke Quay／Chinatown 站步行可达', source: { label: '官网', url: 'https://www.songfa.com.sg/' } },
          order: ['招牌肉骨茶（排骨）', '油条', '卤味配菜'],
          whyLinger: '白胡椒派的代表连锁——新桥路老店最有气，汤免费续到饱。',
          practical: '午晚餐高峰排队；多家分店就近选。以官网为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.songfa.com.sg/' }],
          queueNote: '饭点排队；分店多，就近换一家即可。',
        },
        {
          id: 'ng-ah-sio', name: '黄亚细肉骨茶', nameEn: 'Ng Ah Sio Bak Kut Teh', neighborhood: 'Rangoon Rd（小印度旁）',
          location: { address: '208 Rangoon Rd', areaId: 'little-india', connection: 'MRT Farrer Park 站步行约8分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Ng+Ah+Sio+Bak+Kut+Teh' } },
          order: ['肉骨茶', '潮州卤味'],
          whyLinger: '与松发齐名的老字号——胡椒味更冲，店面是上世纪的样子。小印度散步后的一顿。',
          practical: '早到下午为主；现金与卡以现场为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Ng+Ah+Sio+Bak+Kut+Teh' }],
        },
      ],
    },
    {
      id: 'kopitiam', title: 'Kopitiam 与咖椰吐司',
      intro: '传统咖啡店卖咖椰吐司、半熟蛋、咖啡——本地早餐仪式。kopi 加炼乳、kopi-o 黑咖啡。',
      restaurants: [
        {
          id: 'ya-kun', name: '亚坤', nameEn: 'Ya Kun Kaya Toast', neighborhood: '远东广场（多家分店）',
          location: { address: 'Far East Square, 18 China St（创始店）', areaId: 'chinatown', connection: 'MRT Raffles Place／Chinatown 步行可达', source: { label: '官网', url: 'https://www.yakun.com/' } },
          order: ['咖椰吐司套餐（吐司＋半熟蛋＋咖啡）'],
          whyLinger: '1944 年起家的咖椰吐司连锁——远东广场创始店保留老店气氛，早餐的标准答案。',
          practical: '早上开；多家分店。以官网为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.yakun.com/' }],
        },
        {
          id: 'chin-mee-chin', name: '真美珍', nameEn: 'Chin Mee Chin Confectionery', neighborhood: '加东（East Coast Rd）',
          location: { address: '204 East Coast Rd', connection: '巴士自市区约20–30分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Chin+Mee+Chin+Confectionery' } },
          order: ['咖椰烤面包', '瑞士卷／杯子蛋糕', '咖啡'],
          whyLinger: '上世纪的老饼家——重新开业的店屋老店，炭烤面包配自家 kaya。与加东散步同半天。',
          practical: '早上到下午；周一休（以现场为准）。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Chin+Mee+Chin+Confectionery' }],
        },
        {
          id: 'killiney', name: 'Killiney Kopitiam', nameEn: 'Killiney Kopitiam', neighborhood: 'Killiney Rd（乌节路后街）',
          location: { address: '67 Killiney Rd', connection: 'MRT Somerset 站步行约10分钟', source: { label: '官网', url: 'https://killiney-kopitiam.com/' } },
          order: ['咖椰吐司', '半熟蛋＋咖啡', '咖喱鸡或叻沙简餐'],
          whyLinger: '1919 年起家的老牌咖啡店——乌节路后街的老店屋，比亚坤更旧一派的 kopitiam 场面。',
          practical: '早到傍晚；多家分店，总店在 Killiney Rd。以官网为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://killiney-kopitiam.com/' }],
        },
      ],
    },
  ],
  howToOrder: [
    '食阁先占位（放包纸巾是本地习惯）再各摊点单。',
    '海南鸡饭说 chicken rice，分白鸡／烧鸡。',
    '肉骨茶免费续汤，喝完举手加。',
    '食阁多数收现金或刷卡；部分摊只收现金。',
  ],
  avoid: [
    '滨海湾与金沙商场内餐厅价格虚高；同样东西食阁便宜一半。',
    '景区门口的「免税」店按需要买，不凑热闹。',
    '食阁晚市很多摊收得早，别饿着等到八点。',
  ],
  eatRhythm:
    '早餐 kopitiam（咖椰吐司＋半熟蛋）；午餐食阁（鸡饭或叻沙）；下午娘惹糕点；晚上食阁或小馆。一天两顿食阁正常。',
  allergies: [
    '椰浆与叁巴（虾酱）普遍。',
    '花生常用在沙嗲酱与糕点。',
    '清真与非清真分开；穆斯林摊位不卖猪肉。',
  ],
  guide: {
    city: '新加坡',
    checkedAt: '2026-09-14',
    scope: '以地铁为主的首次新加坡行程；签证按本人证件另核官方要求',
    intro: '新加坡小、秩序强、食阁密。以下按 3–4 晚写。',
    topics: [
      {
        id: 'documents', title: '证件与入境', summary: '免签／签证按护照；SG Arrival Card 提前填。', stage: 'before',
        recommendation: '新加坡对中国大陆护照有免签安排（以当前公告为准），但入境前须在 ICA 官网填 SG Arrival Card（入境前三天内）。其他护照按规定核对。',
        steps: [
          { title: '先按护照核免签资格', body: 'ICA 页面按国籍核对；需要签证的提前办。' },
          { title: '入境前三天内填 SG Arrival Card', body: '在 ICA 官方电子服务填写，生成确认码；截图离线保存。官网免费，注意辨别仿冒。' },
          { title: '材料放一起', body: '返程订单、酒店信息、足额现金离线保存。' },
          { title: '自助通道或人工', body: '持护照走自助通关（符合条件者）或人工通道；核对入境许可期限。' },
        ],
        done: '免签资格核实、SG Arrival Card 已填、订单离线可查。',
        fallback: '入境问题先联系 ICA；不要到机场再处理签证。',
        sources: [ica, sgaCard, consular],
      },
      {
        id: 'mobile', title: '上网与手机', summary: '漫游、eSIM 或落地 SIM 都行；轨道与食阁靠网。', stage: 'before',
        recommendation: '新加坡漫游包、eSIM、落地 SIM 都方便。樟宜机场到达厅有运营商柜台；Grab 与地图靠网。',
        steps: [
          { title: '三选一按天数比', body: '漫游按天、eSIM 按流量、落地 SIM 综合最划算；按行程天数选。' },
          { title: '装好 Grab 与翻译', body: '叫车用 Grab；翻译应用装马来语／淡米尔语／英语包（新加坡官方语言多）。' },
          { title: '樟宜机场本身留时间', body: 'Jewel 雨漩涡与室内瀑布值得一小时；到达或离开时留。' },
        ],
        done: '离 Wi-Fi 能开地图、Grab 能叫车。',
        fallback: '落地柜台即办；樟宜 Wi-Fi 免费且快。',
        sources: [stb],
      },
      {
        id: 'payment', title: '支付与 EZ-Link', summary: '刷卡极普及，EZ-Link 或 SimplyGo 管交通。', stage: 'before',
        recommendation: '新加坡是刷卡社会：多数店收卡与电子支付。交通用 EZ-Link 卡或 SimplyGo（银行卡直接刷闸机）；现金备零头。',
        steps: [
          { title: '拿 EZ-Link 或开 SimplyGo', body: 'EZ-Link 在机场或地铁站买；SimplyGo 用支持的银行卡直接刷闸机，最省事。' },
          { title: '备少量现金', body: '食阁部分摊与小贩只收现金；备小额新币。' },
          { title: '刷卡看币种', body: '提示转人民币计价选 SGD；保存大额收据。' },
        ],
        done: 'EZ-Link／SimplyGo 可用、银行卡确认能刷、备有小额现金。',
        fallback: '卡刷不过用现金；EZ-Link 余额地铁站可退。',
        sources: [{ label: 'EZ-Link', url: 'https://www.ezlink.com.sg/' }, stb],
      },
      {
        id: 'stay', title: '住宿与入住', summary: '住地铁沿线；贵是常态，位置换便利。', stage: 'before',
        recommendation: '新加坡住宿贵是常态；住地铁沿线（武吉士、牛车水、政府大厦方向）位置换便利。胶囊与青旅是省钱选项。',
        steps: [
          { title: '按轨道选片区', body: '住处离地铁站步行十分钟内；城市小，住哪都不远但轨道近更省。' },
          { title: '预算分配', body: '住宿占大头；食阁与轨道便宜，景点多免费，钱往住与吃上倾斜。' },
          { title: '确认入住与行李', body: '入住时间普遍下午；早到寄存。看取消规则与是否含早（食阁更值得）。' },
        ],
        done: '住处离地铁近、总价与取消规则已确认。',
        fallback: '预算紧选胶囊或青旅；位置优先轨道。',
        sources: [stb],
      },
      {
        id: 'arrival', title: '樟宜机场 → 酒店', summary: '地铁 EW 线进城最稳，或 Grab／出租车。', stage: 'arrival',
        recommendation: '行李少：地铁东西线（EW）到市区约 30–40 分钟最便宜；行李多或深夜到选 Grab／出租。樟宜本身留一小时看 Jewel。',
        steps: [
          { title: '先看 Jewel 再进城', body: '到达后可先走 Jewel（连接航站楼）看雨漩涡与室内瀑布；再进地铁。' },
          { title: '地铁 EW 线进城', body: '机场站坐 EW 线到市区（按住处选 Tanah Merah 换向或直达段）。' },
          { title: 'Grab／出租', body: '按 App 价；出租在到达层排队，按表计费。' },
          { title: '到站补最后一段', body: '地铁站到住处用 Grab 或步行；有顶棚连廊多。' },
        ],
        done: '到酒店，知道回程坐地铁或叫车。',
        fallback: '地铁停运改 Grab／出租；深夜只有车。',
        sources: [{ label: '樟宜机场', url: 'https://www.changiairport.com/' }, { label: 'SMRT', url: 'https://www.smrt.com.sg/' }],
      },
      {
        id: 'transit', title: '市内交通', summary: 'MRT 覆盖全城，EZ-Link 一卡到底。', stage: 'during',
        recommendation: '地铁（MRT）是骨架，EZ-Link 或 SimplyGo 刷闸机。巴士与 Grab 补充；有顶棚连廊与地下通道多，热天与雨天友好。',
        steps: [
          { title: '按线色找方向', body: 'MRT 按线色（EW 绿、NS 红等）与终点站名找方向；换乘在站内。' },
          { title: 'SimplyGo 最省事', body: '支持的银行卡直接刷闸机，不用买卡；确认自己的卡支持。' },
          { title: '圣淘沙与动物园', body: '圣淘沙 HarbourFront 换 Sentosa Express；动物园地铁＋接驳巴士。' },
          { title: '记住靠左行', body: '新加坡靠左行；过马路先看右。' },
        ],
        done: '会坐 MRT、会用 EZ-Link／SimplyGo、知道靠左行。',
        fallback: '轨道不熟先坐一段；Grab 叫不到换出租扬招。',
        sources: [{ label: 'SMRT', url: 'https://www.smrt.com.sg/' }, stb],
      },
    ],
    checklist: [
      { id: 'c-visa', text: '免签资格已核实；SG Arrival Card 已填（入境前三天内）', topic: '证件与入境' },
      { id: 'c-passport', text: '护照有效期覆盖行程；订单离线保存', topic: '证件与入境' },
      { id: 'c-net', text: '上网方案选定（漫游／eSIM／落地 SIM）', topic: '上网与手机' },
      { id: 'c-ezlink', text: 'EZ-Link 或 SimplyGo 方案已确认', topic: '支付与 EZ-Link' },
      { id: 'c-cash', text: '备小额现金；银行卡境外功能开通', topic: '支付与 EZ-Link' },
      { id: 'c-stay', text: '住处离地铁步行可达；入住与寄存确认', topic: '住宿与入住' },
      { id: 'c-jewel', text: '樟宜 Jewel 已排在到达或离开时段', topic: '樟宜机场 → 酒店' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：街区一天，滨海湾半天',
      note: '住地铁沿线。每天一个方向加一顿食阁。',
      days: [
        { day: '第一天', body: '抵达入住，麦士威食阁或住处附近晚饭。', time: '按落地安排', start: 'SIN → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '上午牛车水（佛牙寺＋麦士威）→ 下午小印度或甘榜格南 → 黄昏滨海湾看金沙亮灯。', time: '全天，黄昏滨海湾', start: 'Chinatown', return: 'Bayfront／住处', links: [{ label: '牛车水', href: '?tab=places#area-chinatown' }] },
        { day: '第三天', body: '上午滨海湾花园或国家博物馆（雨天选项），午后去机场看 Jewel。', time: '半天、午后收尾', start: '按所选', return: '酒店 → 机场', links: [{ label: '看点', href: '?tab=places' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加圣淘沙或慢走',
      note: '新加坡 3 晚紧凑、5 晚宽松：加圣淘沙一天与留白。',
      days: [
        { day: '第一天', body: '抵达入住，食阁晚饭。', time: '按落地安排', start: 'SIN → 酒店', return: '住处附近', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '牛车水＋小印度或甘榜格南；黄昏滨海湾。', time: '全天', start: 'Chinatown', return: 'Bayfront', links: [{ label: '牛车水', href: '?tab=places#area-chinatown' }] },
        { day: '第三天', body: '滨海湾花园半天＋国家博物馆半天；晚上食阁。', time: '两个半天', start: 'Bayfront', return: '住处附近', links: [{ label: '滨海湾', href: '?tab=places#area-marina-bay' }] },
        { day: '第四天', body: '圣淘沙一天（海滩或环球影城）或留白。', time: '近郊一天', start: 'HarbourFront', return: '住处', links: [{ label: '看点', href: '?tab=places' }] },
        { day: '第五天', body: '住处附近慢走补买，去机场看 Jewel。', time: '上午慢走、午后收尾', start: '住处附近', return: '酒店 → 机场', links: [{ label: '甘榜格南', href: '?tab=places#area-kampong-glam' }] },
      ],
    },
  },
  safety: {
    city: '新加坡',
    checkedAt: '2026-09-14',
    emergencyNote: '新加坡治安极好，主要注意法规严格（乱扔垃圾、地铁禁食饮、公共场所吸烟罚则）。靠左行，过马路先看右。',
    contacts: [
      { name: '报警', number: '999', dial: '999', use: '盗窃、纠纷、交通事故', source: { label: '新加坡警察部队', url: 'https://www.police.gov.sg/' }, urgent: true },
      { name: '急救 / 火警', number: '995', dial: '995', use: '急救车与火警', source: stb, urgent: true },
      { name: '旅游咨询', number: '1800-736-2000', dial: '18007362000', use: 'STB 旅游热线', source: stb },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '免签资格与 SG Arrival Card 确认截图离线保存。',
      '新加坡靠左行——过马路先看右。',
      '法规严格：地铁禁食饮、公共场所禁烟、不乱扔垃圾。',
      '境外医疗保险另存。',
      '记住 999／995。',
      '雨季备雨具；室内空调强带薄外套。',
    ],
    alerts: [
      { title: '法规严格', body: '地铁与公交内禁食饮（罚款）、公共场所吸烟限指定区、乱扔垃圾罚款。遵守标识，别以身试法。', source: stb },
      { title: '靠左行', body: '过马路先看右；扶手电梯站左侧让行。', source: stb },
      { title: '天气与室内温差', body: '室外湿热、室内空调冷；备薄外套与雨具。', source: stb },
      { title: '食阁占位习惯', body: '食阁先占位（放包纸巾是本地习惯）再点单；占了的位别坐。', source: stb },
    ],
    scenarios: [
      { id: 'safety-documents', title: '护照丢了', steps: ['警局报失拿证明。', '联系中国驻新加坡大使馆补办旅行证件。', '保留报失证明理赔。', '出境手续留足时间。'], sources: [consular, { label: '中国驻新加坡大使馆', url: 'http://sg.china-embassy.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 995。', '非紧急请酒店推荐诊所或公立医院；质量高但自费贵。', '保留收据走保险。'], sources: [stb] },
      { id: 'safety-regulation', title: '违反法规被罚', steps: ['地铁内饮食、乱扔垃圾、公共场所吸烟都有罚则。', '收到罚单按流程缴；争议找相关部门申诉。', '不确定能不能做时先看不远处有没有标识。'], sources: [stb] },
      { id: 'safety-fraud', title: '消费纠纷', steps: ['新加坡消费环境规范，纠纷少；价格争议先留证再交涉。', '出租车打表规范；Grab 按 App 价。', '纠纷找 CASE（消费者协会）或 STB。'], sources: [stb] },
      { id: 'safety-transport', title: '坐错线或叫不到车', steps: ['MRT 换乘在站内；坐错换向方便。', 'Grab 叫不到换出租扬招或地铁。', '手机没电找地铁站服务台或商场。'], sources: [stb] },
    ],
  },
  relatedGuides: [
    '吉隆坡城市页 → /places/malaysia/kuala-lumpur',
    '槟城城市页 → /places/malaysia/penang',
    '香港城市页 → /places/hong-kong',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('singapore').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}

export const macau: CityContent = {
  city: city('macau'),
  checkedAt: '2026-09-14',
  meta: [
    { label: '最佳季节', value: '10–12 月与 3–4 月最舒服；夏湿热多台风，冬阴冷。' },
    { label: '机场', value: '澳门国际（MFM）小；多数经香港或珠海陆路口岸进出。' },
    { label: '建议停留', value: '2–3 晚。澳门小，历史城区一天、路氹一天、留白；比香港松。' },
    { label: '地区标签', value: '东亚 · 特别行政区' },
    { label: '气质', value: '历史城区、葡式石板路与赌场的并置' },
    { label: '核实日期', value: '2026-09-14' },
  ],
  essentials: [
    {
      title: '口岸与机场',
      body: '澳门多数经珠海拱北／横琴口岸或香港（港珠澳大桥巴士、喷射飞航）进出；澳门机场（MFM）小，航线有限。按你的进出方向选口岸。',
      action: { label: '查看抵达步骤', to: '?tab=practical#guide-arrival' },
      links: [{ label: '澳门机场', url: 'https://www.macau-airport.com/' }],
    },
    {
      title: '建议住哪',
      body: '住历史城区（大三巴—议事亭前地一带）或路氹（赌场度假村集中）。第一次来住历史城区更有味道；路氹是度假玩法。',
      action: { label: '订房前逐项检查', to: '?tab=practical#guide-stay' },
    },
    {
      title: '建议晚数',
      body: '2 晚够看历史城区与路氹各一天；3 晚加路环或留白。澳门比香港小、更慢，适合当作粤港行程的一段。',
      action: { label: '展开每天安排', to: '?tab=itinerary#plan-three' },
    },
  ],
  overview: [
    '澳门的骨架是两片：半岛的历史城区（大三巴、议事亭前地、妈阁庙）与路氹的赌场度假村。慢旅行住半岛，把路氹当半天到一天的外出。',
    '历史城区是世界遗产：葡式石板路、教堂、庙与老楼挨在一起。上午走大三巴一线，下午走妈阁—岗顶一线，慢走就够。',
    '路氹（金沙、威尼斯人、永利方向）是另一种澳门：室内商场、表演与赌场。看一次就够，别把它当全部。',
    '别把澳门当「香港顺路半日」——它值得两晚，历史城区一项就值回。',
  ],
  gettingThere: {
    intro: [
      '进出澳门：多数经珠海口岸（拱北／横琴）或香港（港珠澳大桥金巴、喷射飞航船）。澳门机场（MFM）小，直飞航线有限。',
      '市内：半岛步行与巴士为主；路氹靠发财车（赌场免费接驳）与巴士。出租车少且贵，发财车是最省钱的跨区方式。',
      '去路环：巴士约 40 分钟，安德鲁饼店与十月初五马路是安静的一端。',
    ],
    links: [
      { label: '澳门旅游局', url: 'https://www.macaotourism.gov.mo/' },
      { label: '治安警察局', url: 'https://www.fsm.gov.mo/' },
    ],
    verifyReminders: [
      '拱北／横琴口岸当前通关时间与人流',
      '港珠澳大桥金巴与喷射飞航的当前班次',
      '发财车（赌场接驳）的当前线路与规则',
      '澳门通卡（Macau Pass）的购买与使用',
    ],
  },
  neighborhoods: [
    {
      id: 'historic-centre',
      title: '历史城区（大三巴—议事亭）',
      suited: '所有第一次来的人；世界遗产核心区。',
      image: cityImages['mo-historic'],
      body: '议事亭前地、大三巴、大炮台、玫瑰堂在一圈里；葡式石板路与老店屋。上午走，避开团队人潮。',
      visit: {
        duration: '半天到一天。',
        entry: '步行；发财车或巴士到议事亭前地附近。',
        walk: '议事亭前地 → 玫瑰堂 → 大三巴 → 大炮台（俯瞰）；巷内老店慢慢看。',
        return: '步行回住处或发财车；大三巴一带白天人多。',
        stay: '首选居住区；住这里等于住在世界遗产里。',
        source: macauTourism,
      },
    },
    {
      id: 'ma-gau-a-ma',
      title: '妈阁—岗顶',
      suited: '想看更早的澳门与庙的人。',
      image: cityImages['mo-ma-gau'],
      body: '妈阁庙是澳门名字的由来；岗顶前地、何东图书馆、圣若瑟修院在一条线上。比大三巴一线人少，下午走。',
      visit: {
        duration: '半天。',
        entry: '巴士或步行从议事亭前地方向。',
        walk: '妈阁庙 → 港务局大楼 → 岗顶前地 → 何东图书馆。',
        return: '巴士或步行回；下午人少安静。',
        stay: '不建议住深处；半天拜访。',
        source: macauTourism,
      },
    },
    {
      id: 'cotai',
      title: '路氹（Cotai）',
      suited: '想看赌场度假村与室内商场的人。',
      image: cityImages['mo-cotai'],
      body: '威尼斯人、巴黎人、永利皇宫等集中在路氹；室内运河、表演与赌场是另一种澳门。半天到一天，看一次就够。',
      visit: {
        duration: '半天到一天。',
        entry: '发财车（免费接驳）从口岸或半岛到各赌场。',
        walk: '威尼斯人室内运河 → 巴黎人铁塔 → 永利皇宫缆车（看喷泉）。',
        return: '发财车回半岛或口岸；赌场内 21 岁以下禁入。',
        stay: '度假村酒店是度假玩法；第一次来住半岛更有味道。',
        source: macauTourism,
      },
    },
    {
      id: 'coloane',
      title: '路环',
      suited: '想看澳门最安静一端的人。',
      image: cityImages['mo-coloane'],
      body: '路环是澳门的乡野：十月初五马路、圣方济各圣堂、安德鲁饼店（蛋挞发源地）。巴士 40 分钟到，半天到一天。',
      visit: {
        duration: '半天到一天。',
        entry: '巴士从半岛或路氹。',
        walk: '十月初五马路 → 圣方济各圣堂 → 安德鲁饼店 → 海边走一段。',
        return: '巴士回；路环人少，节奏最慢。',
        stay: '不住路环；半天到一天外出。',
        source: macauTourism,
      },
    },
  ],
  dayTrips: [
    { direction: '珠海', how: '拱北／横琴口岸过关即达', worth: '过关就是珠海市区；长隆海洋王国在横琴，一天。' },
    { direction: '香港', how: '港珠澳大桥金巴约 40 分钟或喷射飞航约一小时', worth: '港澳同日往返常见；金巴便宜班次密。' },
    { direction: '深圳', how: '蛇口船或经珠海／广州转', worth: '深圳过关即达；行程顺路时排。' },
  ],
  dayTripNote: '珠海过关即达最轻松；香港金巴班次密值得一日；深圳顺路才排。',
  eatIntro:
    '澳门的吃是葡国菜、粤式与老街小吃的混合：葡挞、猪扒包、水蟹粥、葡国鸡各占一席。历史城区老店密集，走哪吃哪。',
  eatCriteria: EAT_CRITERIA,
  eatExclude: EAT_EXCLUDE,
  categories: [
    {
      id: 'portuguese', title: '葡国菜',
      intro: '葡国鸡、马介休（腌鳕鱼）、非洲鸡是澳门葡国菜代表。半岛老店比官也街更本地，当正餐一次。',
      restaurants: [
        {
          id: 'litoral', name: '海湾餐厅', nameEn: 'Restaurante Litoral', neighborhood: '妈阁方向',
          location: { address: 'Rua do Almirante Sérgio 261A（下环／妈阁一带）', areaId: 'ma-gau-a-ma', connection: '巴士或步行自议事亭前地约15分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Restaurante+Litoral+Macau' } },
          order: ['葡国鸡', '马介休球', '焗鸭饭'],
          whyLinger: '澳门土生菜（Macanese）的老牌代表——不是葡萄牙菜翻版，是这座城自己长出来的味道。',
          practical: '午晚餐；订位更稳。以现场为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Restaurante+Litoral+Macau' }],
        },
        {
          id: 'fat-siu-lau', name: '佛笑楼', nameEn: 'Fat Siu Lau', neighborhood: '福隆新街（历史城区）',
          location: { address: 'Rua da Felicidade 64（福隆新街）', areaId: 'historic-centre', connection: '议事亭前地步行约5分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Fat+Siu+Lau+Macau' } },
          order: ['烧乳鸽（招牌）', '葡国菜家常款'],
          whyLinger: '1903 年开的老酒楼——福隆新街红门脸里最老的一间，烧乳鸽是镇店菜。',
          practical: '午晚餐；价格高于茶餐厅，当正餐安排。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Fat+Siu+Lau+Macau' }],
        },
      ],
    },
    {
      id: 'egg-tart', title: '葡挞与饼店',
      intro: '安德鲁（路环）与玛嘉烈（半岛）是葡挞两大源头；现烤的最好。',
      restaurants: [
        {
          id: 'lord-stows', name: '安德鲁饼店', nameEn: "Lord Stow's Bakery", neighborhood: '路环市区',
          location: { address: '路环市区打缆街（圣方济各圣堂旁）', areaId: 'coloane', connection: '巴士自半岛约40分钟', source: { label: '官网', url: 'https://www.lordstow.com/' } },
          order: ['现烤葡挞', '咸点与咖啡'],
          whyLinger: '葡挞的发源地——1989 年安德鲁在路环开的这间小店就是原点。买一盒坐在十月初五马路海边吃。',
          practical: '早上开；现烤时段最好。多家分店，总店在路环。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '官网', url: 'https://www.lordstow.com/' }],
        },
        {
          id: 'margarets', name: '玛嘉烈蛋挞', nameEn: "Margaret's Café e Nata", neighborhood: '新马路／南湾',
          location: { address: 'Rua Alm. Costa Cabral（新马路旁巷内）', areaId: 'historic-centre', connection: '议事亭前地步行约8分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Margaret%27s+Caf%C3%A9+e+Nata' } },
          order: ['葡挞', '三明治与咖啡'],
          whyLinger: '安德鲁前妻玛嘉烈的店——半岛这边的葡挞源头，不必专程跑路环也吃得到原味。',
          practical: '早上开；巷内小店找招牌。现金方便。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Margaret%27s+Caf%C3%A9+e+Nata' }],
        },
      ],
    },
    {
      id: 'street-snack', title: '老街小吃',
      intro: '猪扒包、水蟹粥、云吞面是老城小吃。大三巴到议事亭前地一路都是，边逛边吃。',
      restaurants: [
        {
          id: 'wong-chi-kee', name: '黄枝记', nameEn: 'Wong Chi Kei', neighborhood: '议事亭前地',
          location: { address: '议事亭前地 17 号', areaId: 'historic-centre', connection: '步行，广场边上', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Wong+Chi+Kei+Macau' } },
          order: ['虾子捞面', '鲜虾云吞面', '水蟹粥（晚市）'],
          whyLinger: '议事亭前地旁的老面家——竹升面弹牙、虾子面是招牌。逛历史城区中途的正经饭。',
          practical: '午晚餐；饭点排队。以现场为准。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Wong+Chi+Kei+Macau' }],
        },
        {
          id: 'tai-lei-loi-kei', name: '大利来记', nameEn: 'Tai Lei Loi Kei', neighborhood: '氹仔旧城区',
          location: { address: '氹仔巴波沙总督前地（官也街方向）', connection: '巴士或发财车到氹仔再步行', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Tai+Lei+Loi+Kei' } },
          order: ['猪扒包（下午出炉）', '奶茶'],
          whyLinger: '猪扒包的名店——氹仔总店下午出炉排队。配官也街散步正好。',
          practical: '猪扒包下午出炉时段最新鲜；多家分店。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Tai+Lei+Loi+Kei' }],
          queueNote: '出炉时段排队；分店与外卖档可分散。',
        },
      ],
    },
    {
      id: 'cha-chaan-teng', title: '茶餐厅与粤式',
      intro: '澳门茶餐厅与粤式点心同香港一脉；老茶楼是早茶选项。',
      restaurants: [
        {
          id: 'nam-peng', name: '南屏雅叙', nameEn: 'Nam Peng Café', neighborhood: '十月初五日街（历史城区旁）',
          location: { address: '十月初五日街 85–87 号', areaId: 'historic-centre', connection: '议事亭前地步行约10分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Nam+Peng+Cafe+Macau' } },
          order: ['南屏文治（三明治）', '奶茶／咖啡', '叉蛋治'],
          whyLinger: '1966 年的老冰室——绿色卡座与手写价目表都还在，澳门茶餐厅的活标本。',
          practical: '早茶到下午；现金方便。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Nam+Peng+Cafe+Macau' }],
        },
        {
          id: 'lung-wa', name: '龙华茶楼', nameEn: 'Lung Wa Tea House', neighborhood: '红街市',
          location: { address: '提督市北街 3 号（红街市旁）', connection: '巴士或步行自大三巴方向约15分钟', source: { label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Lung+Wa+Tea+House+Macau' } },
          order: ['传统点心自取', '普洱／香片'],
          whyLinger: '1962 年开的老茶楼——点心车自取、老茶客看报，澳门仅存的传统早茶场面。',
          practical: '早茶时段（上午）最好；现金。',
          verifiedAt: '2026-09-14',
          sources: [{ label: '地图检索', url: 'https://www.google.com/maps/search/?api=1&query=Lung+Wa+Tea+House+Macau' }],
        },
      ],
    },
  ],
  howToOrder: [
    '饼店现烤葡挞按个买；手信店试吃再决定。',
    '茶餐厅口头点单或画单；猪扒包要现炸。',
    '葡国菜餐厅看当日推荐；马介休有多种做法。',
    '老街小吃摊现金为主。',
  ],
  avoid: [
    '大三巴到议事亭主街的「游客价」手信店偏贵；钜记咀香园连锁价格透明。',
    '赌场内餐厅与表演票价虚高；看免费表演（喷泉、缆车）就够。',
    '路边「兑换」与拉客不进；换钱去银行或口岸正规点。',
  ],
  eatRhythm:
    '早餐茶楼或茶餐厅；午餐老街小吃边走边吃；下午葡挞；晚餐水蟹粥或葡国菜。一天多顿小份。',
  allergies: [
    '葡挞与饼店点心普遍含蛋奶。',
    '花生糖与杏仁饼是坚果重地。',
    '粤式与葡国菜多含猪肉与海鲜。',
  ],
  guide: {
    city: '澳门',
    checkedAt: '2026-09-14',
    scope: '以步行与巴士为主的澳门行程；签证／签注按本人证件另核官方要求',
    intro: '澳门小，住半岛、路氹当外出。以下按 2–3 晚写。',
    topics: [
      {
        id: 'documents', title: '证件与签注', summary: '大陆居民用往来港澳通行证＋澳门签注；其他护照按规定。', stage: 'before',
        recommendation: '大陆居民赴澳门需「往来港澳通行证」与澳门签注（个人游 G 签或团队 L 签，按户籍与政策）；港澳通行证与签注在公安出入境办理。其他护照按澳门治安警察局规定核对。',
        steps: [
          { title: '先办证与签注', body: '大陆户籍在公安出入境办港澳通行证与澳门签注；签注类型（个人游／团队）按户籍与当前政策核对。' },
          { title: '核验证件覆盖行程', body: '通行证与签注有效期覆盖行程；复印与照片备份。' },
          { title: '材料放一起', body: '返程订单、首晚住宿信息离线保存；入境可能询问。' },
          { title: '入境核对停留期', body: '澳门给游客的停留期按证件类型；核对入境章／小票上的期限。' },
        ],
        done: '通行证与签注齐备、订单离线可查。',
        fallback: '证件问题找签发机关或治安警察局咨询。',
        sources: [macauPolice, { label: '国家移民管理局', url: 'https://www.nia.gov.cn/' }],
      },
      {
        id: 'mobile', title: '上网与手机', summary: '漫游最方便；澳门小，流量需求不大。', stage: 'before',
        recommendation: '澳门多数酒店与赌场有免费 Wi-Fi；国内运营商澳门漫游包最省事，落地即用。流量需求不大，漫游通常够。',
        steps: [
          { title: '漫游包先开好', body: '国内运营商澳门漫游包按天计费；出发前开好，落地即用。' },
          { title: '免费 Wi-Fi 作补充', body: '酒店、赌场、部分公共区有免费 Wi-Fi；不依赖但有备份。' },
          { title: '地图与支付提前装', body: '离线地图与微信支付／支付宝（澳门普遍支持）提前装好。' },
        ],
        done: '漫游可用；离线地图与支付已装。',
        fallback: '漫游失败连酒店／赌场 Wi-Fi；市区 SIM 卡店可办。',
        sources: [macauTourism],
      },
      {
        id: 'payment', title: '支付与澳门通', summary: '现金与移动支付并存；澳门通或现金管巴士。', stage: 'before',
        recommendation: '澳门微信／支付宝支付普及；现金（港币与澳门币通用）用于小店与巴士。澳门通（Macau Pass）刷巴士；发财车免费。',
        steps: [
          { title: '备港币或澳门币现金', body: '港币在澳门通用（按 1:1 用，汇率略亏但方便）；小额现金用于巴士与小店。' },
          { title: '移动支付先确认', body: '微信／支付宝在澳门多数店可用；确认境外支付已开通。' },
          { title: '澳门通看需要', body: '巴士投币现金也行；坐得多买澳门通（便利店有售）。' },
        ],
        done: '现金够、移动支付可用、巴士零钱备好。',
        fallback: '现金不够找银行 ATM；移动支付失败用现金。',
        sources: [{ label: '澳门通', url: 'https://www.macaupass.com/' }, macauTourism],
      },
      {
        id: 'stay', title: '住宿与入住', summary: '住历史城区或路氹；发财车是跨区利器。', stage: 'before',
        recommendation: '第一次来住历史城区（大三巴—议事亭方向）更有味道；路氹是度假玩法。发财车（赌场免费接驳）连接口岸、半岛与路氹，是最省钱的跨区方式。',
        steps: [
          { title: '按玩法选片区', body: '历史城区住半岛；纯度假与赌场选路氹。多数人选半岛。' },
          { title: '确认接送与晚到', body: '很多酒店有发财车或接驳；晚到问清前台。' },
          { title: '看硬条件', body: '老城酒店可能旧；看近期评价与实拍。' },
          { title: '保存地址', body: '中英文地址截图；司机多数懂中文。' },
        ],
        done: '住处位置、发财车接驳与晚到方案已确认。',
        fallback: '到店不符先找平台协调；发财车线路变化先查。',
        sources: [macauTourism],
      },
      {
        id: 'arrival', title: '口岸／机场 → 酒店', summary: '多数经口岸进；发财车免费接。', stage: 'arrival',
        recommendation: '经珠海拱北／横琴口岸或香港（金巴／喷射飞航）进出；过关后发财车免费到各酒店。澳门机场（MFM）小，直飞航线有限。',
        steps: [
          { title: '按进出方向选口岸', body: '珠海方向：拱北（市区近但人多）或横琴（新、去路氹顺）；香港方向：金巴或喷射飞航。' },
          { title: '过关后找发财车', body: '口岸出口有各赌场／酒店免费接驳车；按住处选线路。' },
          { title: '澳门机场落地', body: '机场小，发财车或巴士进城；出租车少。' },
          { title: '最后一段', body: '发财车到酒店或最近点；半岛窄巷导航完最后一段。' },
        ],
        done: '到酒店，知道回程去哪个口岸。',
        fallback: '发财车排队久换巴士或出租；口岸人流大留时间。',
        sources: [{ label: '治安警察局（口岸）', url: 'https://www.fsm.gov.mo/' }, macauTourism],
      },
      {
        id: 'transit', title: '市内交通', summary: '半岛步行、发财车跨区、巴士补充。', stage: 'during',
        recommendation: '半岛历史城区全靠走；半岛—路氹靠发财车（免费）或巴士。出租车少且贵，发财车是主力。巴士投币或澳门通。',
        steps: [
          { title: '发财车是主力', body: '口岸、码头、半岛、路氹之间各赌场免费接驳；按住处选线路，免费坐。' },
          { title: '巴士补充', body: '巴士投币现金或澳门通；去路环坐巴士约 40 分钟。' },
          { title: '半岛步行', body: '历史城区窄巷坡道多，穿好走的鞋；议事亭到大三巴一路都是内容。' },
          { title: '靠右行', body: '澳门靠右行（与大陆同）；过马路先看左。' },
        ],
        done: '会坐发财车、知道巴士投币、知道靠右行。',
        fallback: '发财车排队换巴士；迷路回主路或问赌场职员。',
        sources: [macauTourism, macauPolice],
      },
    ],
    checklist: [
      { id: 'c-visa', text: '通行证与澳门签注齐备且在有效期', topic: '证件与签注' },
      { id: 'c-passport', text: '证件复印与照片备份；订单离线保存', topic: '证件与签注' },
      { id: 'c-net', text: '澳门漫游包已开；离线地图与支付已装', topic: '上网与手机' },
      { id: 'c-cash', text: '备港币／澳门币小额现金；移动支付已开通', topic: '支付与澳门通' },
      { id: 'c-shuttle', text: '发财车线路已查（按住处选）', topic: '口岸／机场 → 酒店' },
      { id: 'c-border', text: '已查口岸通关时间与人流', topic: '口岸／机场 → 酒店' },
    ],
  },
  itinerary: {
    threeNights: {
      title: '3 晚：历史城区一天，路氹一天',
      note: '住半岛。历史城区慢走，路氹当外出。',
      days: [
        { day: '第一天', body: '抵达入住，议事亭前地一带慢走晚饭。', time: '按落地安排', start: '口岸／机场 → 酒店', return: '历史城区', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '上午大三巴—大炮台 → 下午妈阁—岗顶一线 → 晚回住处。', time: '全天慢走', start: '议事亭前地', return: '妈阁／住处', links: [{ label: '历史城区', href: '?tab=places#area-historic-centre' }] },
        { day: '第三天', body: '上午路氹（威尼斯人／巴黎人）半天，午后返程。', time: '半天外出、午后收尾', start: '发财车 → 路氹', return: '酒店 → 口岸', links: [{ label: '路氹', href: '?tab=places#area-cotai' }] },
      ],
    },
    fiveNights: {
      title: '5 晚：加路环与留白',
      note: '澳门 3 晚够；5 晚加路环半天、珠海或香港一日、留白。',
      days: [
        { day: '第一天', body: '抵达入住，历史城区慢走晚饭。', time: '按落地安排', start: '口岸／机场 → 酒店', return: '历史城区', links: [{ label: '抵达步骤', href: '?tab=practical#guide-arrival' }] },
        { day: '第二天', body: '历史城区一天（大三巴—议事亭—妈阁—岗顶）。', time: '全天', start: '议事亭', return: '妈阁／住处', links: [{ label: '历史城区', href: '?tab=places#area-historic-centre' }] },
        { day: '第三天', body: '路氹半天（赌场度假村看一次）＋路环半天（十月初五马路）。', time: '两个半天', start: '发财车 → 路氹', return: '路环／住处', links: [{ label: '路环', href: '?tab=places#area-coloane' }] },
        { day: '第四天', body: '珠海长隆或香港一日（金巴往返），或留白。', time: '近郊一天', start: '按所选', return: '回澳门', links: [{ label: '看点', href: '?tab=places' }] },
        { day: '第五天', body: '历史城区补漏、买手信，返程。', time: '上午慢走、午后收尾', start: '历史城区', return: '酒店 → 口岸', links: [{ label: '历史城区', href: '?tab=places#area-historic-centre' }] },
      ],
    },
  },
  safety: {
    city: '澳门',
    checkedAt: '2026-09-14',
    emergencyNote: '澳门治安好，主要留意口岸人流、赌场规则与台风。靠右行（与大陆同）。',
    contacts: [
      { name: '报警', number: '999', dial: '999', use: '盗窃、纠纷、交通事故', source: macauPolice, urgent: true },
      { name: '急救 / 火警', number: '999', dial: '999', use: '急救车与火警（统一号码）', source: macauTourism, urgent: true },
      { name: '旅游热线', number: '+853-2833 3000', dial: '+85328333000', use: '澳门旅游局热线', source: macauTourism },
      { name: '领事保护', number: '+86-10-12308', dial: '+861012308', use: consularUse, source: consularHotline },
    ],
    phrases: HELP_PHRASES,
    preparation: [
      '通行证与签注确认截图离线保存。',
      '澳门靠右行（与大陆同）；过马路先看左。',
      '赌场 21 岁以下禁入；看免费表演就够。',
      '境外医疗保险另存。',
      '台风季（夏秋）留意预警；口岸人流大时留时间。',
      '记住 999。',
    ],
    alerts: [
      { title: '口岸人流', body: '拱北口岸节假日人流极大；过关留足时间，别掐点赶车。', source: macauPolice },
      { title: '台风', body: '夏秋台风可能停班停船；行程留弹性，关注气象预警。', source: macauTourism },
      { title: '赌场规则', body: '21 岁以下禁入；内场拍照有限制；看免费表演与缆车就够，不必进赌区。', source: macauTourism },
      { title: '靠右行', body: '澳门靠右行（与大陆同，与香港相反）；过马路先看左。', source: macauTourism },
    ],
    scenarios: [
      { id: 'safety-documents', title: '证件丢了', steps: ['到治安警察局报失拿证明。', '联系外交部驻澳门特派员公署或签发机关咨询补办。', '保留报失证明理赔。', '出境手续留足时间。'], sources: [consular, { label: '外交部驻澳门特派员公署', url: 'https://www.mfa.gov.cn/' }] },
      { id: 'safety-medical', title: '需要就医', steps: ['紧急拨 999。', '非紧急请酒店推荐诊所或仁伯爵综合医院。', '保留收据走保险。'], sources: [macauTourism] },
      { id: 'safety-border', title: '口岸排队或证件问题', steps: ['口岸人流大时改横琴或错峰。', '证件问题找口岸边检或治安警察局。', '回程留足过关时间，别掐点。'], sources: [macauPolice] },
      { id: 'safety-fraud', title: '消费或兑换纠纷', steps: ['路边「兑换」不进；换钱去银行或口岸正规点。', '价格争议先留证再交涉。', '纠纷拨 999 或找旅游局。'], sources: [macauTourism] },
      { id: 'safety-transport', title: '发财车排队或坐错', steps: ['发财车排队久换巴士或出租。', '坐错车在下一站下车换向；赌场职员可指路。', '手机没电找酒店前台或赌场服务台。'], sources: [macauTourism] },
    ],
  },
  relatedGuides: [
    '香港城市页 → /places/hong-kong',
    '台北城市页 → /places/taiwan/taipei',
    '珠海／深圳方向行程（规划中）',
  ],
  sourcesNote: [
    '街区、看点与交通信息来自官方公开资料与通用旅行常识，核对日期见上。',
    '店单按「可核实」标准收录：每家店留核实日期与来源；营业与排队信息以现场和官网为准。',
    `官方入口：${city('macau').officialLinks.map((l) => l.label).join('、')}。`,
  ],
}
